# Public Service Announcements

“Now get out of here! Go hide somewhere!” Francis told Aspen, flicking his hand to emphasize himself. He watched her dash out of the room, the thin fabric fluttering in her wake. He held himself upright for a few seconds after she left, staying cheery and positive; as soon as he knew she would not turn around, he tilted back on his ankles, leaning on a creaky washing machine. His facade cracked, his frustration and sadness breaking through. The machine whirled onward, puncturing the air with squeaks from its drum every revolution. Francis buried his forehead between his thumb and forefinger, squinting angrily into his palm. 
	Ay, ¡soy demasiado viejo para esto! Aspen, that poor girl. I hope my help somewhat compensates for her demon-of-a-husband’s behavior. He looked heavenwards, dropping his hand to rest on his stubbly chin. She’s a sweet girl, y’know? She’s just so kind, a pure soul. She doesn’t deserve this. 
	He kept pondering, conjuring unrealistically easy solutions that would never work even in an alternate universe, but acted as placeboes for his vengeful desires. At times like this, when anger clouded his conscience, he tended to revert to his native style of speaking, a mash of Spanish, English and other languages, a habit encouraged by his popular port town’s many travelers and his bisabuela. Uy, these ideas son locas. He flicked his hand again as if wiping his mind clear. Pushing off the machine, he bent over and rotated laundry loads, dirty clothes to washer, washer to dryer or hanging, dried clothes folded, waiting for Adonis’ clothes to be done cleaning. He had put them in for a fast cycle, so it should take only fifteen minutes. Francis only planned enough time for them to wash, not dry, so hopefully Adonis could use his big-spy-brain and figure out how to hang-dry them on his shower bar. 
	While he kept waiting, Francis remembered the first time he met Aspen. It was not so long ago, but it was not surprising to Francis in the least that she did not seem to remember him. It was only just a couple weeks ago, now that I think about it. 
	The strategies and methods of folding fabrics into different, neater shapes is so monotonous it’s easy for the mind to wander. Francis could picture the morning perfectly, every sensation and sight so realistic it was like a screen playing. 
He was in the downstairs coat closet-turned-infirmary, straightening and organizing his tools and vials. He was new, forced into working at this exquisite mansion under threat of his children being tortured. They had already been gone for many days, his Ambar and Coliban, but the thought of losing them permanently hurt so much he sacrificed himself to this mausoleum. 
He put the Aspirin to the left side, Ibuprofen in the middle. As he dug into his bag for more of his drugs, someone jumped him by pounding on his door loudly. A scrawny girl ran in, gasping and explaining in short bursts a situation that had just happened upstairs. Confused, he followed her to a room up the stairs and in the center of the manor. His eyes widened as he beheld the scene. Blood. Glass. Half-closed shades. Dark wood stained darker with the random pools of maroon blood. So. Much. Blood. A woman. Passed out on the floor, jade shards spilling from her limp fingers. Her blonde hair swirled over her face, hiding her paleness. He jumped to her, kneeling next to her limp form, pushing her shoulder so she gently rolled onto her back. He put his ear next to her chest, near her nose, squeezing her wrist. He heard a faint beating, felt slight breathing ruffle his hair, and a fluttering pulse in her wrist. 
“She’s alive,” he said into the air, not directing the comment to any one of the ten maids floating around in a terrified state. “Is this the Miss of the house? What happened to put her in such a state?”
A manservant offered, “Sir, I believe you are a newcomer? Well, yes this is Miss Aspen-Fauna and... Sir Odin ‘put her in this state.’”
“....her husband?” Francis asked, shocked that one man could be so despicable to his spouse that he professed to love. The maid simply nodded. 
Francis picked her up, struggling to hold her snugly in his arms because of her limpness. He carried her downstairs and back to his small office, cradling her head on his bicep, for once grateful for his stomach pudge that cushioned her body. He lay her on a small cot crammed in the corner, gently took off her dress and draped a smock on her, trying to respect her modesty while also tending to her wounds as fast as he could. He dabbed her cuts, first removing blood then disinfecting them, then wrapping soft gauze all the way up her arms. He treated her neck, then partially through wrapping her legs, he was summoned by Odin. He did not oversee the rest of her care, but he later heard from one of the other two nurses that she had taken only a little over twenty-seven hours to recover and start walking around again. 
Present-day Francis snapped out of his trance as the washing machine’s alarm buzzed. He wrapped up his thoughts with a couple last lines: I risk myself to fight for freedom for those who can’t. I fight to free Adonis and Sampson, Aspen, and my friends who have lost their children the same as me. Those thoughts satisfied him, stoppering his other distracting thoughts like a cork, containing them for later so he could focus on the actions he needed to take to actually help all the persons he just vowed himself to. So, he plopped Adonis’ sopping clothes at the bottom of a hamper and deposited the nicely folded ones on top. 
Exiting the laundry room back into the main hall, he wandered around while trying to look purposeful and run into someone from Aspen’s search party. 
Eventually, a manservant dashed around a corner and caught up to Francis, asking, “have you seen Miss around at all?”
“You know, I do believe I just saw her go to the movie room in the finished basement,” Francis beamed at him, forcing a dopey innocence into his face. The maid talked into a small walkie-talkie he pulled from his pocket and sprinted back to the direction from whence he came from. Francis immediately cut back and found the closest concealed entrance to a servant’s stairwell. Most of the servants did not bother to learn the creaky back passageways, for fear of roaches, rotting planks, and spiders, but Francis saw it both as a useful skill and an easy getaway when needed. Most recently, the tunnels had fulfilled the second need more than the first. 
He got lost on a couple turns, but he managed to get out near Adonis’ room. He knocked on the door, then pulled out a small lock pick of his own, which he had made himself out of an old nail, that fit most of the doors in the mansion and let himself in. Strange there’s no guards posted, Francis thought. Oh, well, I guess they’re either looking for Aspen or hiding from Odin.
“Hello Adonis! How’re you doing today?” Francis asked, dropping his hamper of clothes and pushing the door closed with his heel. Adonis started, flinging out his arms and gathering something beneath him as he kneeled on the rug, not very cleverly hiding something. 
“Ah-! H-hi Francis! I’m doing super g-great!” Adonis stuttered while pressing his face into the rug to hide the guilty blush that rose on his cheeks. Francis stood back with his arms crossed, trying to suppress a snicker. He found the whole situation to be quite funny.
“I’m assuming you’re hiding something that is Miss Aspen-Fauna’s?” Francis asked rather cheekily. 
“Yes,”Adonis said slowly, still hunched over and pressing into the rug. He paused, and when he spoke again, he sounded afraid. “Are you going to tell Odin?”
Francis’ desire to snicker dissipated. He had almost forgotten that Adonis had been kidnapped and thrusted into a lifestyle where he knew none of the rules except the fact that danger was always lingering, ready to attack. Despite having years of professional training, anyone would be panicked by a sudden twist like that. Sympathy flooded Francis’ limbs, dragging his arms from folded upon each other to dangling by his sides. Francis understood fear. “...no. I’m not going to tell Odin. Come on up now. I’ve got your clothes for you.” 
Adonis fluidly lifted his torso, revealing the dress and shoes. He twisted around, facing Francis, and propped one knee up, resting the other knee flat on the rug and wrapped his arms around his standing knee. Francis carefully transferred the folded clothes from his basket onto Adonis’ bed, and his eyes caught on the delicate canopy ravaged by many long tears. 
Francis flicked his finger tip at it. “What’s all this?”
Adonis glanced up and nonchalantly said, “Oh, that’s how I keep track of the days I’m here. Each slash is one time I wish I could’ve punched Odin.”
“You wish to hit him only once every day?” Francis chuckled.
“Of course not. The longer the slash, the more punches he deserved,” Adonis smiled. He reached for his sopping wet clothes from Francis and went into the bathroom to drape them. Walking back, he asked, “Francis, what time is it? Don’t you have something to do? Not that I want you out, you just seem to have too much free time.”
“Yeah, I should go, I do have other errands to attend to with the staff,” he folded the dress and laid it upon the shoes at the bottom of his basket. “I’ll return these to Aspen. Do you want me to take that hairband too? I’m assuming it’s not yours?”
Adonis paused, not realizing that he had been absent-mindedly fiddling with the band again. “...no, actually. I’ll keep it.”
“Alrighty then! Have a good day Adonis!” Francis smiled wryly and left in his cheery manner. Adonis muttered something about drugs ruining his day under his breath, waving goodbye to Francis. 
 Francis finished his house rounds by finally dropping off the basket to Aspen’s closet, rushing back to the laundry room to put his overcoat and boots back on, then catching up with the other house staff at the front of the mansion to help prepare the ten or so vans going out. Today, a big supply truck carrying food was going to come to the mouth of the valley, and the staff were told to pick up the food and store it away so the truck did not have to come fully into the valley. Francis was a driver, and as he got in his car, he noticed he would not have a passenger like some of the others did. Instead of a person in the passenger chair, there was a stack of papers reaching shoulder high with a note stuck to them: Distribute to town after pick up. Every house needs one. Francis’ stomach twisted as he saw a block of words printed across each sheet. The papers looked almost identical to the one he had received months ago, a time where he thought that this ‘Odin’ was a crackpot pushing out fantasies of power. A time before Odin’s deranged fantasies became reality. 

Good day to you all, citizens of Briarcliff Valley. 
A reminder that all social media is monitored and banned. Outside influences poison good values, and constantly feeling the need to prove yourself to your ‘online friends’ is needy and unnecessary. Any and all pictures and posts on any platform will be deleted. Keep in mind we are trying to build a society where flaunting your self-worth will be unnecessary. 
This is a final call to all children and families; children, there is a place you can live without the restrictions of your families, with plenty of food, games and other children. Families, you need to send your children to camp at the Manor. It is a nature experience, 100% safe, loving, and a nurturing environment for them to grow, play, and explore! Please do not hesitate to send all children to the Manor. A caravan will be arranged to retrieve them if necessary.
Free scarves are available to all. As winter closes in and supply chains dwindle, please do not hesitate to inquire one of our helpers for winter gear or food. Food is resupplied biweekly. If you have extra non-perishable food, please give it to a helper, or put it in a box in the square next to the flag pole so that you can share your good fortune with others less fortunate than you. Strong communities stay together! If you help someone now, they will help you in the future.
Finally, remember to keep both your Briarcliff Valley flags and U.S.A. flags flying. Show support and patriotism as we prepare to expand our idyllic and perfect living experience to other communities in the near future. Rejoice and pray that others will soon know our redemption and joy!
Have a wonderful day!
Business inquiries: +1(989)7217-6431
or
cassie.blankhurst.1@BriarCliff.Living.com

	Propaganda. Francis’ head swirled as he read the entire paper. Propaganda at its finest. He was disgusted. His eyes burned and throbbed. He wanted to scream and rip the papers into tiny shreds. 
	But he didn’t.
	He started the car. Revved the engine along with the other drivers. Ignored his revulsion. 
	He hated Odin. He hated shoving such nonsense down his neighbors’, his friends’, throats. But who was he to play God and fight a self-pleasing dictator?

↞⇼↠

	The cars wended leisurely through Briarcliff, working from the front of the manor and turning south to the mouth of the valley. Ironically, Francis had to admit that Briarcliff was the perfect place for Odin to begin taking over whatever he was going to take over. Secluded, rarely heard of, and only having one main entrance into the town would be a massive advantage to him. 
Even under normal circumstances, food had to be delivered on big trucks to the area, and it was a tricky process as the grade of the mountain road was sometimes too steep for the deliveries. The trucks normally would drive to one of the two big food markets or some of the smaller gas stations to drop off their load, but recently the drivers had been instructed to park at the mouth and wait for the vans to drive up; the ruse being the road was too slick and dangerous with black ice for the haulers. 
Francis pulled up and parked his car behind the others, leaving room behind him for the rest of the caravan to park. He walked up to the truck driver leaning on the side of the hood, greeting him with a handshake. The driver stretched his arm back inside momentarily to put out his cigarette. The rest of the crew began unloading and transferring the food into the vans, putting stuff that did not require ice soon into Francis’ van so he would have enough time to deliver the posters. 
“Hey, man, what’s it like in the outside world?” Francis asked, relaxing on the closed door.
“Nothing much,” the driver responded. He thought for a moment then said, “Actually, there’s this strange sickness called ‘corona’ that some scientists are freaked about.”
“Oh? Corona? Like the beer?” Francis asked again, confused.
“Yeah. Strange thing. It supposedly spreads really quickly, but it’s not in the U.S. yet. I think we’ll be ok. Y’know, modern medicine and all that; I can’t see it getting too bad. Plus you mountain folks are so secluded you probably won’t even hear about it or nothin’,” the driver said, nonchalantly flicking his hand. 
The driver made other small talk with him, about weather, about politics. They conversed for a while, as Francis did not feel inclined to help unload. If anyone complained about it, he could always just say his back was acting up again.
Francis glanced back to see the progress of the other workers, noticing they were almost done reorganizing the food in the backs of the vans. “Well, hey man, thanks for bringing all this up. It’s been a real pleasure meeting you,” Francis smiled and clasped the driver’s shoulder. “And let us know if anything more happens with this ‘corona.’”
“Of course. Y’all have a good day now,” the driver tipped his hat and hopped back into his high seat. The vans turned back down the road, heading back to the mansion for redistribution instructions. Francis waved them off, listening to the dwindling sound of the engines to go away completely before he got back into his own van. 
Though he started the engine, he did not drive off right away. Francis sat in the heat blasting from the vents and pulled out his old phone and searched up ‘corona.’ Millions of results came up, mostly of beer, but towards the bottom of the first page, multiple articles spoke about doctors’ concerns. COVID-19: fast moving, variations, only a few seconds needed for transmission? Symptoms include coughing, fever, headache, muscle aches… the symptoms went on and on. Hmmm...interesting. I don’t think Odin would like it if this somehow got into the house…  
He put his phone back in his pocket and split off from the main road, veering into the heart of town. He retied his scarf and threw on another sweatshirt underneath his coat; the windchill was brutal today. He dragged himself to every door, slipping a piece of paper underneath the bottom edge. 
The sun crept from the eastern sky to the low western sky. And he still trudged from eave to eave. Eventually, all of the papers were gone, forced upon Briarcliff. 
Francis dropped heavily into his van’s chair for the last time that day. He buried his face into his ice-caked mittens. The ice froze his cheeks, but he did not even notice the pain. He wept. He wept for Coliban and Ambar.
