# Blurred Lines

November 27, 3:17 P.M.: Thanksgiving was very quickly approaching. And after Thanksgiving, there were only a couple of weeks until Christmas, then a few days until New Year’s and the year 2020 would begin. Time cycles, repeats annually, makes and retells stories, moving quickly and slowly, blurring by and standing out all while each second was exactly the same length as the previous. Sam hated that even though every minute in this house was just as short as each other, they somehow seemed to take years for one to pass. 
	His whole body seared in pain. It was just as it was when he first got to the manor, but even worse. He shook on his side, screaming as every minute was an eternity. It was dark all around him. His hands did not work right. He coughed, blood came out of his mouth and nose. The rough floor scraped his legs and arms as he writhed. He screamed until his throat gave out, and no one could hear him anymore. 
And he was not the only person who knew this pain. Sam knew, somewhere around him, somewhere outside the shackles of his body, others endured just as he did. Maybe ten, maybe hundreds, maybe thousands. Only the room, the dark, tall room knew. The room of madness and insanity and confusion and sickness and a million other horrible experiences. The room of blood and suffering and mystery and things unseen.
His mother stood over him, a watery apparition, condemning him for not having integrity in his position. His brothers and sisters crowded around him, asking him questions, but he couldn’t hear a word they said. They all melted away as his head spun and he dry heaved, nothing coming up as he hadn’t eaten in hours. Or was it days? Or only minutes?
Blood dripped from his nose, tears dripped from his eyes, sweat dripped from his forehead, all splashing on the floor, drawing patterns as he wriggled. Time dripped, sloshing, melding together into a blurry painful haze with no beginning and no end.

↞⇼↠
	
	November 25, 7:43 A.M.: it had been three days since the propaganda posters had been distributed. Adonis had not seen any of them personally, but he had heard snatches of information from the chatty guards and maids. Right now, he was twiddling his lockpick between his knuckles and straining to hear anything going on outside his doors, squinting his eyes tightly as if that could make him listen better. At approximately 7:45 every other morning, there was a small gap of time, twenty seconds on average, of a blindspot as the guards rotated. The guards standing at the door would walk out of the hall in unison to the right, and the new guards would stroll in from the left, and the curve of the walls would hide the view of Adonis’ and Sam’s doors momentarily. The guards seemingly rotated at random, but after being imprisoned for a few weeks, Adonis was beginning to notice a pattern. Today, the guards should rotate again at 1:15 in the afternoon.
	Sam and Adonis needed to strategize today; Adonis thought the next meeting with Selena would be tomorrow, and they needed to think of what to do. He glanced at the clock on his bedside table again; eight, seven, six, five, four, three, two...now! A moment later than his countdown, the guards’ footsteps started. 
Adonis leapt up, shoved his lockpick in the door, flicked it until it caught, let himself out, yanked the door until it was centimeters away from the jamb, gently guided it the rest of the way closed, slid on his socks down to Sam’s room. On his now-left, the footsteps faded, and on his right, the new guards could be heard getting closer and closer. I hope Sam is awake by now, although Adonis knew Sam likely wasn’t. Adonis was not necessarily a morning person, rather an all-over person, as his anxiety messed up his sleeping schedule. Sam was a consistent sleeper, and he consistently tried to sleep past noon. 
The lock clicked open. Adonis jumped in, rotated back to the door, pulled and locked it, backing away, muffling his labored breathing with a blanket he snatched from Sam’s bed. The guards stepped into position, completely oblivious and unassuming. Adonis grinned evilly. I’m really surprised I pulled that off, to be completely honest. I kinda thought I was finally going to meet God. 
He put the lockpick on Sam’s bureau and crept to his bedside, wondering how to wake him up as quietly as possible. Sam typically was a violent wake-upper, meaning he sometimes would lash out physically or vocally if you surprised him awake. So, Adonis carefully reached his hand around Sam’s torso as he slept on his side, hovering it slightly off of him, then tightened his and pushed the blanket he held onto Sam’s face at the same time. Sam immediately jerked awake, his pupils wide, and tried to yell, but Adonis gripped him and shoved the blanket into his mouth. Sam blinked hard, slowly calming back down. Adonis released the blanket and held a finger to his lips while staring deep into Sam’s eyes. Removing his arm, Adonis tip-toed to the bathroom and beckoned for Sam to follow him. 
“Good morning,” Adonis formally greeted Sam. Sam dropped to the tile floor and leaned against the wall.
“No. Bad morning. Too early,” Sam yawned widely. “What are you doing here?”
“Well, I think Odin is going to have us meet with Selena again tomorrow? Am I right?” Sam nodded. “Then we need to strategize. I believe we have five-ish hours before the guards rotate again and I can leave, so until then we just need to talk quietly.”
Sam thunked his head on the wall and closed his eyes. “Adonis, you didn’t think this through. What about the people who drop food off to us? What’re they gonna think when you’re not in your room, but here? How would we even say anything important to Selena with Jeff hovering right over us as well as feeding us a script?”
“Admittedly, I did forget about the meals. But! I did think of a strategy for the call tomorrow,” Adonis started talking faster, getting excited to present his ideas to Sam that he had thought about all night. “I guess for the meals, I can just hide in here somewhere and you can greet the maid and tell them I’m sick or something so they won’t see me. Anyways; strategy. I think we can probably guess what Odin wants us to say. Something like, we’re doing well, everything is on time, we are closing in on the mansion, we’ve found a way in, we don’t need backup, everything seems fine. So, using that, we can think of words to say for that!”
Sam clearly didn’t understand Adonis’ full idea: “Obviously we’re going to be speaking. What do you mean ‘we can think of words?’”
Adonis leaned onto his knees and placed his hands in front of himself, balancing weight on his knuckles. “We can hide a code in our words. I propose something simple, such as every first letter of every word or something. Do you see what I mean now?”
Sam jerked forward. His eyes widened. “Adonis, you’re a genius.” Adonis nodded enthusiastically. “Although, maybe not that code, because it can be cracked a little too easily.”
Sam dashed from the bathroom and returned with a short, dull, nub of a pencil and a small pad of paper. He stated simply, “now we make our code.”
They sat on the cold tiles for hours, only interrupted twice by the meal deliveries. Finally, minutes away from the guard’s rotation Adonis would use to leave, they came up with the perfect sequence.

↞⇼↠
	
November 26, 10:24 A.M.: The phone sat in the middle of the triangle. The triangle was wrapped in a half circle. The triangle’s points were Sam, Adonis and Jeff sitting across from each other in the library, Adonis and Sam tensely waiting for Odin to say something. The half circle was an entourage of guards zoning out while trying to look anywhere but Odin’s gaze. Odin leaned back in his chair, crossed his legs and tapped his lip with his right forefinger.
“So,” Odin started. “You both know what to say. More importantly, you should both know what to not say.” Adonis and Sam nodded. On the outside, they were both coolly staring at Odin, calm. On the inside, they were nervously hoping they could get their whole message out without being interrupted. 
Odin slowly perused their faces, enjoying watching them squirm under his stare. He narrowed his eyes, uncrossed his legs, and dragged his phone in to himself. As he dialed Selena’s number, Adonis and Sam looked at each other sideways. Sam subtly nodded. The triangle all turned back to the phone as Odin replaced it in the middle. It only rang twice before she picked up.
“Hello?” Selena asked. Odin flicked his fingers at them.
Adonis obliged. “Hi Selena! The mission is going well. We will keep calling you two or three times a week.”
Sam started his part: “Today, however, I see us interrogating suspects about the countless ordeals during everything we’ve done that we’ve heard of. We’ll ask them lots of stuff. Because, y’know, every other thing might be important.” 
“We will keep you posted on that as well. Maybe we should write our first letters to the agency. Some of our information could be too important to say over the phone,” Adonis finished. He was for once grateful that his hands were bound behind him so that Odin couldn’t see them shaking.
“...wow! You boys certainly seem very productive,” Selena responded, slightly taken aback by their language. This is definitely planned. She brushed it off as they were likely rehearsing what they were going to say before they called so they could say it quickly. Service was spotty in the mountains, plus they probably had to be quiet to prevent discovery of their hideout. But I think it’s probably a good thing that it’s protocol for the agency to record calls. 
Odin wasn’t liking how structured their sentences were sounding either. He turned them over and over in his mind, but he couldn’t quite pin what was off about them, other than just sounding awkward and choppy. 
“Jefferson is there with you guys too, right?” Selena asked. The pair looked to Odin for guidance. Odin slashed his hand over his neck. 
Why shouldn’t he have to talk? Why should we have to do all the dancing around? Sam’s cockiness made him want to slap the smug look off of Odin’s stupid face. 
“N-no, he’s not here right now, he went down to-” Adonis improvised.
“Actually, I think he just got back,” Sam cut in. He delighted in watching Odin squirm. Sam flicked his fingers at Odin, prompting him, fisting control from Odin and holding it in his own palms. 
Odin clenched his jaw and quietly said hello. Adonis sat in shock, wishing that Sam had not done that to himself. Sam smiled. It was the little victories that were going to carry him through this. All he had succeeded in doing was making Odin say hello, but it was enough to go against what he wanted, and that was enough to make Sam happy. Besides, Odin never specified before this call that he wasn’t going to talk. 
“Bye, Selena! We’ll talk with you soon!” Adonis ended the call. The phone clicked off, hanging up from the other side of the line. Adonis thunked his head on the table. Sam mirrored Odin’s stance, both relaxed in every way except for the cold war they fought with their eyes. 
Sam melded his fear into confidence.
“Guards,” Odin called, only moving his mouth. “Take him to the basement. You can bring the short one back to his room.”
“Ha! You think a basement is going to scare me? A little darkness is going to whip me into shape?”
Adonis groaned inwardly. Sometimes, Sam really didn’t know when to shut up.
“This darkness will. I don’t think you’ve seen the other basement, have you?” The guards closed in on Adonis and Sam, yanking them out of their chairs. “Goodbye Sam. I do wonder how your trip will be.”

↞⇼↠
	
The agents were escorted out of the room. Odin stayed behind, thinking over the call yet again. Something is not right about this. They had no time to prepare before the call, right? I gave them no time, yet both their sentences were poorly constructed, a bunch of unintelligible words slapped together. There must be a code, but what was it? Odin struggled to remember each word they said, knowing it would be important to solving whatever they had hidden within their word tangle. If only I had the smarts to record the call. I will do that from now on.

Odin didn’t know the code, but unknown to him as well, a small, square piece of paper tucked inside of an empty conditioner bottle, did. 
Hi Selena! The mission is going well. We will keep trying to tell you what is going on about two or three times a week. Today, However, I See us Interrogating Suspects about the Countless Ordeals During Everything we’ve heard of. We’ll ask them lots of stuff. Because, you know, every other thing might be important. We will keep you updated on that. Maybe we should write our FIRST LETTERS to the agency. Some of this could be too important to say over the phone. 
The sheet had tons of scribbles, underlining and rewrites all over it. Adonis and Sam had ended up straying slightly from their script, as they couldn’t have it right next to them, but it had the same meaning. 
The first few sentences were gibberish. The fourth, sixth, and eighth sentences were all important; the sixth and eighth were instructions: pay attention to every other sentence, look at the first letters of words. When going back to the fourth sentence, all the first letters spelled out were THISUISATCODEWHO. 
Ideally, Selena would eliminate some letters with a bit of guesswork and extract ‘THIS IS CODE.’

↞⇼↠

	“What are you doing, Sampson?” Adonis raged as soon as the doors of the library closed behind them. “Now you’re the idiot not thinking things through!”
	Sam knew Adonis’ angry words were coming from a deep place of care, but that didn’t make them sting any less. “Honestly, I thought he was bluffing. I didn’t think he would actually drug us when he needs us for communication with Selena!” Sam shot back.
	“I don’t think anyone here is too important to Odin for him to not punish!” The guards leading Sam and Adonis stayed silent as they lashed at each other. “We are in a game, Sam! A game where neither of us know the rules and no one will tell them to us! The only part of this that isn’t a game is if you die while playing, you will actually die! Don’t make such stupid decisions on your own! Use some integrity.”
	Sam burned to yell back at Adonis, but he knew that Adonis was right. He was being a cocky idiot, throwing himself into the fire without caring how much the flames scarred him. 
	Adonis noticed the guards starting to lead them in different directions. “I love you, Sam. Stay safe, bro.”
	Sam’s throat swelled and he stared at a light to prevent tears from coming out. He had cried in front of Adonis before, but he wasn’t about to cry in front of these guards. “Love you too, Adonis. I promise I’ll be ok,” friends, the rarest kind. Platonic soulmates, bros, brothers from different mothers, whatever you called them; Sam and Adonis were inseparable for life.
	Sam’s guard led him down stairs, and as they rounded the stairs to the bottom floor, the guard tentatively asked Sam, “Why did you do that? Surely you knew there would be consequences, so why take the risk?”
Sam thought for a moment, digging in himself to find the truest reason for his actions. “I guess a part of me thought he wouldn’t really make his threat true. Even though I can be quite pessimistic, I try to see the best in people. And sometimes I definitely don’t think things through, as much as I get annoyed at Adonis for it.” He thought for a moment more then added, “I find that I often put others before myself as well. It’s a bad habit, but I don’t have a lot of awareness of self-preservation.”
The guard nodded, understanding that almost self-sabotaging behavior.
Sam twisted his neck as far back as it could go to look at the guard. He asked, “Am I going to die from this?”
After a long pause, the guard answered, “...no. But by the end, you might wish that you had. I certainly don’t envy your position.”
“Well, if I won’t die, bring it on; I can handle it.” The guard smiled a weak sad smile, heavy with knowing, at Sam. The guard stopped in front of a stern-looking woman, and the young guard gently undid Sam’s cuffs and left them on a table, to be put back on when he re-emerged from the room. The guard tried to smile supportively at Sam again, then waved and walked out of the hall. Well, he was pleasant. I hope I meet him again in the future.
“Good luck in there. Eat this,” the woman held out a pill. 
“No,” Sam defied simply.
“Don’t worry, it’s a pain killer. Here, use this to wash it down,” she held out a tall glass. 
That much was true. Sam read the small numbers on the pill, and recognized it. He drank the water. Almost instantly after he drained the glass, he dropped it and collapsed to his knees, clutching his abdomen. It shattered into a thousand sparkling shards onto the pristine marble.
The woman knelt next to him. “I-I’m sorry. It was in the water. I really hate this job, I’m so sorry.”
She opened the door right behind him and gently pushed him all the way to the floor, then rolled him into the dark room. She winced as his screaming started, melting together with the others’ screams. She yanked the door shut and pressed her hand tightly to her lips.

↞⇼↠
	
November 26, 11:48 A.M.: Selena listened to the call again, for the third time. This doesn’t feel right.
	“Hey, Jimbo! C’mere!” Selena leaned back to peer around her cubicle and yelled at her girlfriend, Trinity, who worked in a different department just across the hall.
	“You know I hate that nickname,” Trinity mumbled into Selena’s ear as she stumbled in. Selena giggled and kissed her cheek as Trinity wrapped her arms around Selena’s neck. “What do you want?”
	“Can you listen to this recording I have with my agents? Something is off about it, but I just don’t know what yet,” Selena explained and handed Trinity an earbud. Selena waited patiently while Trinity listened. 
	“You’re right,” Trinity said a couple minutes later, taking the earbud out and replacing it on Selena’s desk. “They’re for sure hiding something for you in there. Wanna go into the conference room and figure it out?”
	“You don’t have anything to do right now?” Selena wanted help, but she also didn’t need Trinity getting fired. 
	“I do, but I’m procrastinating! Let’s go!”
	They went into the conference room with pens, sticky notes, and two cups of coffee, one basically creamer and the other black. 
Selena listened to the call as a whole, trying to understand the whole call. Trinity picked apart each sentence, each word, seeking the individual meanings in each line. Selena noticed the sixth sentence saying every other thing would be important. Selena and Trinity fought for a while, not sure whether that meant every other word was important or every other sentence or even every other message the agency received from them. Eventually they decided it meant sentence as Trinity noticed sentence eight saying the first letters were important. Tracing back to the fourth sentence, they solved the word puzzle.
“All that work just to get THIS IS CODE? That’s stupid and a given; that’s why we were solving it!” Trinity complained.
“No, no! It’s not dumb or a waste of time! Think about it.This is gonna be the same key they use for the next call. And the next call, and the next call. And we’re probably the only ones who have it, because how would you get it unless you relistened to the call multiple times?”
“Something must have gone wrong then. Why else would they need to use a code?” 
	“I don’t know. I think we should send in another team to help them,” Selena opened and closed her hands, nervously twitching her fingers.
	“No, that wouldn’t work,” Trinity countered. “What good would it do the agency if we got two teams stuck up there? If Adonis and Sam, two of our best agents, got captured, surely any other team would get caught too. Do you know if they’re going to call you again?”
	Selena jumped from her chair excitedly. “Yes! They said they were going to call about three times a week; that should give them plenty of time to tell me what’s really going on, and what I should do.”
	“What we should do. I’m invested in this now; I want to help you,” Trinity reached out and flicked the tip of Selena’s nose. Turning back to the table, Trinity reminded Selena, “Before you forget, write down the code. Losing that would kinda suck.”
	Selena scribbled on her notepad, then immediately ran back to her desk and slapped it on the top of her computer monitor so she wouldn’t lose it. 
	
Three times a week. 
Every other sentence. 
First letters.
