# Thanks-Taking

“Happy Thanksgiving!” Aspen called to a manservant as she swished by in her mermaid-cut pearly dress. Her hair was twisted around her head in a braid crown, pinned up with simple bronze pins.
	“Good afternoon, Miss,” the manservant replied, his response lacking all the excitement her greeting had contained. His eyes were tired, dark shadows sitting below them. He was young, but his back was bowed slightly, as if he carried a heavy weight.
Aspen realized her mistake and wished she could bite back her greeting; of course it wasn’t ‘happy thanksgiving.’ Nothing was happy about being forced to work in a big, lonely house without seeing your family. After all, Thanksgiving really is just an excuse to meet with your friends and family. Guilt burned the tips of her ears as she passed the man, and she stared at the floor so she wouldn’t accidentally meet his eyes again. Even though this Thanksgiving would not particularly be a good one for her either, it was certainly better than his.
She wrung the dress tightly with her hands. She was headed towards the dining room where Jeff told her he’d be waiting. She looked up from the ground and tilted her head in confused interest as she heard a scuffling sound in front of her. The source of the sound was hidden from view by the wall of the hallway.
“Here-grab him under there. No, there!”
“Here? Ugh-he can’t walk by himself?”
“No you idiot! He-” the guard talking cut himself off as he saw Aspen approach. He composed himself and said as politely as possible, “Hello, Miss Aspen.”
Aspen froze for a second, trying and failing to look indifferent to the situation she was seeing. Two guards struggled to hold up a limp body. The body was tall, the skin that was visible was covered in bruises. Blood dripped from its nose and mouth, falling to join the already large pool of blood on the marble. Streaks covered its face, presumably from tears. Small scratches covered its cheeks, arms, legs, forehead. Hair hung in weak, greasy strands. 
The body lifted its head. It held its head aloft just long enough for Aspen to peer deep into its eyes.
Sam’s hollow eyes bored back into hers. 
His tired brown circles broke off from hers as they glazed over and rolled up. His head fell backwards, his body following. The guards cursed as he slipped from their arms and landed back in his own trails of blood. Tremors racked his body. When he thrashed about, his limbs caught the blood and dragged it around, trailing crimson streaks all over the pristine marble. 
Aspen jerkily nodded to the guards and kept walking. She couldn’t help Sam. She couldn’t help Sam and it ripped her heart apart. 
Coward. You are a coward. 
Helping Sam would give me away! It’s better to just do nothing.
Coward. 
The path of blood went all the way down the hall she was walking, finally branching away from her as it went into the stairwell. There were two more irregular patches of rusty streaks; he’s had more than one seizure. 
Her stomach flipped and knotted. She felt like giving up and screaming, but she knew that there was bound to be a camera watching her right now. In a dazed state, she meandered the rest of the route to the dining room. 
“Aspen, are you alright? You look a tad pale,” Jeff asked, using his thumb and pointer finger to grab Aspen’s chin and lift it slightly. She flinched, surprised at how she got to the dining room so quickly and startled by Odin reaching towards her. 
She carefully wiggled out of his hand and said, “No, I’m fine. Just tired, that’s all.” She smiled at him, performing for him, becoming an actress, willing him to believe. She was certain that nothing in her face betrayed the horror she had just seen. The horror that this man in front of me is responsible for. She looked up and down Odin, observing every wrinkle in his suit, every twitch of his fingers, the line of shadows under his cheekbones, the small reflection of herself in his glasses. What did he do to Sam? She realized that though she had known this man since high school, even though she had fallen in love with him, even though she had married him, she had no idea who the stranger that stood in front of her was. 
She took his hand in hers and they strided across the threshold into the room, taking seats next to each other at the massive table. No one else sat. 
Kitchen staff and servers brought out course after course, and between each bite, Aspen talked, joked, charmed. Hours crawled by, and she worked to entertain and distract Odin for every second of them. 
Anything to take his attention away from the stain she hadn’t noticed until she sat. A bright scarlet splotch bloomed along the entire bottom hem of her dress. She must have walked through a pool of Sam’s blood without noticing. She prayed Odin had not seen it. He either would blame her for conniving with Sam or blame the guards for allowing her to see him; Odin typically shielded her from his business. Just like he had hidden the children from me. He knew I would never approve of leading children away from their parents.  
The constant acting also helped numb her own mind. Nervousness thrummed in her throat as she worried about Sam, how she should have helped him instead of being a deserter, when could she sneak away to see him again?

A small part of her wondered whether the next time he saw him it would be at his grave. 

↞⇼↠
	
	First a missing knife. A random sock frozen on a security camera. And now blood on your dress that I bought for you. Not to mention the clothes the prisoners somehow got.
	Odin stared at Aspen sideways, tenting his fingers around his temple to hold his head up. He  watched her mouth move, her eyes light up, the slight bouncing in her hair as she exuberantly told another story. He smiled, satisfied she was his bride. 
I love her. 
She loves me. 
That’s all I need to know.
Yet he noticed again as she wrung her dress in between her slender fingers. The slightly too long pause she took between each sentence in her story. The way she was carefully covering up every bit of the silence. 
Those idiot guards must have paraded Sam throughout the halls. How else could she have managed to get blood on that dress? I’ll have to have a meeting with them.
I do hope you didn’t see Mr. Sam. Although, I suppose you don’t even know who he is. 
If you did see him, I hope for your own sake you see it as a lesson, my dear. Odin mused. He moved his fingers to scratch his chin.  I see all. I know everything that goes on in this house. I control what goes on here. I get to decide who to punish as I see fit. 
I decide people’s fate because I have the power. I’m finally at the top. I’ve finally accomplished something. Something worth recognition. 
Finally, I’ve outdone everyone else.

↞⇼↠
	
Adonis experienced a profound sense of deja vu as he stood in the exact same spot as he had a few days ago, pressing his ear to the thick wood door, to listen to the guard’s movements outside. The only difference was this time, he was wishing the guards would come faster and he was in Sam’s room. 
He had been listening to the guards for the past twenty-four hours, itching to hear anything about Sam. According to the conversation he overheard at about ten this morning, Sam was being moved back up to his room to ‘make room for more.’ Adonis hoped he had misheard the second part. Surely Odin wasn’t drugging so many people that his titanic basement was literally overflowing with the screaming dead, right? 
So Adonis had snuck into Sam’s room during the rotation, right after the lunch delivery time so he would not have to deal with the maid. He questioned if they would actually get dinner; the majority of the staff’s energy and resources was likely going to Odin and a very preppy dinner he was sure to have for Thanksgiving.
The hallway echoed with loud clunking, quietly at first, then very loudly as the two guards bumbled around with Sam. Adonis stayed at the door until the last second he could, only dodging behind Sam’s bed when the keys were fit into the lock. The guards opened the doors, but instead of just staying at the door frame like Adonis thought they would, they actually came into the room. Internally groaning, Adonis crawled on his belly, squishing himself under the bed. The guards released Sam the second he was somewhat close to his bed, and with a great whuff his beaten, bloody, torso fell onto his pillowy comforter. His legs still hung off the edge. From his muffled hiding place, Adonis heard one guard laugh. Judging from the thin shadows he could see, the same guard also kicked the bottom of Sam’s foot. The other guard was silent. Adonis couldn’t see the second guard’s face, but guilt and pity played across it. They both turned and left. 
Adonis carefully flipped to his back and arched his neck to see above his head. He grasped a metal bar at the edge of the bed frame, then pulled himself out using only his arms. Standing very carefully, he crept around the room, closing the windows’ curtains, and moved the heavy dresser right in front of the door. He also grabbed the remote and turned the television to some random show, raising the volume to an unnecessary pitch. Anything to hide some of the louder noises we might make.
Adonis finally turned his attention to Sam. He gently shook Sam’s shoulder, but Sam didn’t stir at all. Adonis scooped his arms under Sam’s armpits, lifted him off the bed, and dragged him into the bathroom. Moving him also let Adonis see Sam’s once-pristine comforter; the guard’s careless throwing of him had stained it with gore. Lowering Sam to the floor, Adonis tried to think of a way he could wash at least some of the blood off him without putting him at risk of drowning. Sam started mumbling something quietly. Adonis instantly kneeled next to him.
“Can you say it again, Sam? I couldn’t hear what you said.”
“The reason we got such nice rooms is-” Sam’s throat gave out. He cleared it and tried again. “-is to hide that damned basement.” His words slurred together. Adonis pulled away slightly and nodded.
“Is it ok if I try to wash some blood off you?” Adonis asked, wanting to get Sam’s direct permission now that he was awake. Sam imperceptibly nodded, still not opening his eyes. He wet a washcloth and wiped Sam’s face, erasing most of the grime, but some had worked into his pores and stubbornly refused to wipe off. After dabbing Sam’s face, Adonis decided to move onto his main body. “Sam, can you lift your arms? And now your legs? One at a time is ok.” Sam listened to the instructions, but did not react beyond that. Adonis lifted off Sam’s sweatshirt and sweatpants, stripping him to his boxers. 
Adonis winced as he saw Sam’s body. Now that he had actually seen the damage in its entirety, he wished that he hadn’t. Cold seeped from the tiles into Sam’s direct skin, making him shiver violently. As Adonis leaned in to inspect all the injuries closer, checking to see if any were actively bleeding, Sam seized. Convulsions took over his body, wrenching his back and spine. Adonis bunched up the towel around Sam’s head but didn’t try to hold down Sam; he remembered from first-aid training that trying to do so could hurt him more. The best thing to do was just wait for the spasms to pass. The trickle of blood from Sam’s nose doubled to a steady stream. 
His convulsions finally stopped. I didn’t want to put him in the shower before because he would probably be cold after, but I don’t really think that matters anymore, Adonis grimly thought to himself. “Sam, this is probably going to hurt, but just try to relax. If it hurts too much, tap my arm.”
As carefully as possible, Adonis hooked his arms around Sam’s armpits again and slowly pulled him into the tiny shower. He propped Sam against the wall opposite of the shower head and turned the water to a temperature he hoped was right. He watched with morbid fascination as filthy, brown-red water swirled off of Sam and down the drain. 
The shower was so small Adonis was balancing on his knees outside of the shower, leaning on his hand planted on the rim of the shower pan to reach inside and dab more dirt off Sam with the washcloth. The pure whiteness of the towel was soon soiled, blackened so much it was hard to believe it was ever white. Adonis attempted to shampoo Sam’s hair, but struggled so much he had to ask Sam to scrub it in and rinse it off. Showering was a long process, taking nearly forty minutes to get Sam slightly clean. Throughout the whole process, he grimaced, throwing his head back in pain when Adonis brushed against the more sensitive scrapes, but Sam was too stubborn to concede and tap Adonis’ arm. He still had blood crusted on him in places, but his need for sleep trumped his need for sterilization. 
A few drops of blood occasionally dripped out of Sam’s nostrils, but other than that, he was overall okay. Adonis rolled up two small strips of toilet paper and pushed one up each of Sam’s nostrils, then pulled him out of the shower to wrap him in the full-size towel. Heavily leaning on Adonis for support, they stumbled out of the bathroom together and made their way over to the bed. Adonis’ shoulders and arms almost caved from holding Sam up, so instead of actually helping him get onto the bed properly, Sam just flopped on it again. Adonis lifted his feet up and snatched the nasty comforter from beneath Sam. 
He bunched up the comforter and prepared to throw it across the room, but stayed his hand at the last second. He faced Sam again. In a low voice he asked, “Sam, do you think you have the energy to yell something right now? Something really short.”
Sam slitted his eyes open and looked sideways at Adonis. “Do I look ready to yell something right now?” he answered with a question, his sarcastic air returning. 
“I think you’ll manage. All you gotta do is ask for Francis.”
Sam kind of shrugged, the sheets getting in his way. “Alright then.” Adonis dropped the comforter, turned the television’s volume low and ducked under the bedframe. With all the strength he could muster, Sam called, “Guard! Can I ask a-” he coughed. “-a favor!”
The guard unlocked the door and poked their head in. They looked annoyed. “What do you want?”
“Can you please send in Francis?” Sam asked hoarsely. “He’s a nurse, and-”
	“Yeah, yeah. I know who Francis is. I’ll send a call for him.”
	“Thank you.”
	The guard paused halfway through closing the door. “...you’re welcome.”
	
A few minutes had passed since the guard locked the door and radioed for Francis. “Adonis?” Sam asked.
“Yeah?”
“Are you going to crawl out from under my bed?” His throat ached when he talked, but he pushed away his discomfort to talk to Adonis.
“Nah. I like it down here. Plus I can see the TV.” Adonis’ words were very muffled to Sam as they passed through his mattress. 
“You’re weird.”
“It’s comfortable! Don’t hate on me just because you can’t move by yourself.”
“If I could move by myself, I would move my hand to your face very quickly so I would hurt you tremendously.” Adonis just snickered in response. 
They watched the house show that was playing on the television, not understanding the point of it. Adonis thought it was stupid that this family of seven wanted to live in a house no bigger than seventy square feet and Sam couldn’t have agreed more. They had a pointless argument over the finer points of the parents’ obliviousness, pointless as they both agreed on how incredibly ignorant the parents must be. 
	Adonis quickly shut his mouth as the room was opened to the hall again. The bars of light coming from the hall shifted on the floor as Francis stepped in. 
	“Hello Sam! What can I do for ya?”
	Adonis popped his head out after Francis closed the door. “Hi!”
	Francis startled, dropping the oversized bag he had with him. He laughed and said, “Hello Adonis! Didn’t expect you here too!”
	Adonis smiled and wriggled the rest of the way out. He walked up to Francis and stooped to retrieve the bag for him. After he handed it back to Francis, he jumped on the other side of the bed and sat cross-legged on the sheets.
	“Now, why was I summoned by you rascals?” Francis asked, planting his hands firmly on his hips.
	“I didn’t know what to do,” Adonis answered. “There’s a bloody comforter, the rug is bloody, there’s blood on the floor, there’s blood on Sam. And his nose won’t stop bleeding.”
	“Are you sure you have any blood left in you, Sam?” Francis tapped his forehead. Sam smiled weakly. “How are you feeling?”
	“I thought I had died a couple of weeks ago when I was shocked;” Sam held up his finger to show the small scar. “But I’ve revised my view of death, and have decided that now I am dead. My stomach hurts, I’m nauseous, my head is floating around somewhere in the sky and my skin and all of these cuts throb in unison.”
	“When was the last time you ate or drank anything?”
	Sam struggled to remember. “I...I think the last time I ate was the morning of the twenty-sixth. Probably the last time I had water too.”
	“First off, you’re dehydrated,” Francis walked away and opened the door. He leaned out and said, “Hey boneheads! Do you even feed your prisoners? Yes? Are you sure? Go get food now!” After a pause he continued his tirade: “I don’t care if it’s Thanksgiving! Just grab something from the kitchen that looks edible!” 
	He turned around and slammed the door. “Sorry, I hate dealing with idiots.”
	Sam and Adonis hooted with laughter. Sam laughed so hard he started coughing and Adonis had to double over to stop wheezing. 
“I do think your dinner will be here promptly, Sam,” Francis continued as if nothing had happened at all. Only a small quirk in his lips gave away the hilarity bubbling inside him. “For now, drink this and take this pill.”
Sam’s hand shook as he accepted the cup. He trusted Francis, but he just couldn’t shake his last encounter with ‘water.’ Adonis noticed his fear and asked how the drug was given to him. Sam told him. 
“Sam, I’m so sorry that happened to you. But you can’t hold fear of drinking; you need to survive. It’s ok, there’s nothing in this water. Francis and I are right here,” Adonis said slowly, staring at Sam’s eyes. Sam nodded and took the pill.

↞⇼↠
	
Francis had bustled about the room for the better part of two hours, chatting with Sam and Adonis, caring for Sam’s scratches and endlessly bleeding nose (which he finally staunched with a localized blood-thickening solution), and making sure Sam drank more water and ate the sub-par food the guard managed to collect. The sun sank lower and lower in the sky, turning into a bloated disk on the horizon with scratches of clouds hovering in front of it. After it hid behind the mountains and stained the sky with crimson and violet, Francis excused himself to go eat his own dinner. He took the rug and comforter with him. He had also scrubbed away the few drops of blood on the floor.
Sam and Adonis sat in content silence, too weary to talk. Sam was circling in his thoughts, spiraling, and decided he needed to break the quiet. 
“I miss my family.” Sam had a large family, all who he left behind in Guatemala to pursue his career in America. He still visited them often, but a lot of the time, his meetings were cut short due to work. He missed his childhood home, a little village called Chichicastenango high in the mountains. It hurt him more when he remembered today was a Thursday; every Thursday and Sunday, there were big markets where you could stroll down the main road and buy all kinds of handicrafts, food and flowers. He was the oldest in his family, with five younger siblings, though technically he was the second oldest. He had an older sister until he was four, but she passed away due to a fever. Part of the reason for his hot-headedness was his burning desire to be an overprotective older brother. A gaping pit with spikes at the bottom threatened to swallow him if he kept going down the path of nostalgia; allowing oneself to stay in the past for too long can prevent future growth and destroy what is already in place in the present. 
“Why are you thinking of them?” Adonis asked while observing the cloth canopy draped between the bedposts, picking out every curve and flaw. When Sam didn’t answer, he followed up, “Is it Francis?” Adonis saw Sam nod at the edge of his vision. “Yeah, he reminds me of my dad too.”
They didn’t say anything else. Stars flashed over the manor, the same stars that half the world could see at the moment. All over the world, families, friends, strangers gathered together for meals, Americans for Thanksgiving, everywhere else just for a casual lunch or dinner or breakfast. All the people in the world had two things in common: sharing food and sharing stars. Odin was an exception. He didn’t share, he just took and took and took. Sam and Adonis were also exceptions; while they did share the stars, they replaced sharing food with simply sharing each others’ presence. 

	Adonis finally crawled back into his room at around one in the morning. He wanted to stay with Sam until he fell asleep, and he figured the meal deliverer wouldn’t care enough to check if he was actually there. On his way out of Sam’s room, he snagged the pen and pad of paper they used to make the code last time and scribbled a quick note to Sam. It said: Continue acting like you are horribly sick tomorrow. Try to not come to the call. He folded the scrap into a small free-standing triangle and placed it on Sam’s night stand, next to Sam’s glass of water. Adonis then returned to his room and sitting on his bed, he flicked his bedside lamp on and started working on the next call’s code.