# Organized Chaos

December 5, 9:22 A.M.: Francis trudged the stairs up to Odin’s office. He had sweat running down his face, he had a fever of one-hundred and one degrees. He was feeling faint. He hadn’t eaten that morning, or the night before. He had been coughing like a madman. 
I should try out at that local theatre. 
	He lifted his fist to pound on Odin’s thick door. “Come in,” Odin commanded. 
	“Good morning, sir,” Francis whispered, making his voice crack and turn hoarse. 
	“Did you make a trip to the basement?”
“No, sir. I think I have a sickness called COVID-19, or corona maybe?”
“Hm.” Odin leaned back in his chair. “What makes you think this? How could you even catch it? We are completely secluded.”
“Well, I think it’s a sickness where-”
“I know what it is, gardener,” Odin cut in smoothly.
“Ah, okay, well I think I got it from the food delivery a few days back. I haven’t been feeling quite like myself since then,” Francis said, sniffling.
“What’s your temperature?”
“One-hundred and one, sir.” 
Odin stared at Francis. He hid his thoughts and feelings with a cool, neutral face. He actually didn’t know much about the sickness, but he had heard how contagious it was, and that it was key to self-isolate for two weeks if you think you had it. If all of my staff get sick… 
“Two weeks. I expect you to be back at the manor in two weeks, even if you have a fever of one-hundred and twenty degrees. Do I make myself clear?”
“Yes, sir. Thank you.”
“Get out of my office.”
Francis bowed his head and retreated. His eye caught on a dark stain ingrained on the already dark wood floor. He winced inwardly as he remembered watching that stain being made from one of Aspen’s pools of blood. 
As he closed Odin’s office, he shook off the dreadful memory as well as his fake sickness. He was already feeling much better. He felt astronomically better after he got to deliver a duffel bag ‘full of necessary pills’ for Sam to take care of himself while Francis was quarantining, and a backpack with ‘allergy medication and an inhaler’ inside to Adonis in case he got an asthma attack during the two weeks.

↞⇼↠
	
December 6, 11:10 A.M.: Sam’s room echoed dully with throbbing reverberations as his door was pounded. He was jolted out of sleep and he leapt from his bed, punching the air as he landed on his feet. His heart pounded and realized there was no immediate danger as he blinked away the haze on his eyes. 
“Get up, you lazy pig!” Odin yelled from outside. The pounding on his door finally stopped when the guard opened the door. “Where are your handcuffs?”
Sam grunted. “I don’t know. Where’s your courage? You need to cuff a man who’s still sick?”
Odin marched over and grabbed Sam. Despite the height advantage Sam had on him, his body was still weak from the infernal basement ordeal and he nearly fell as Odin yanked him forward. “Guards, cuff him. Make sure they’re tight.” He looked up to Sam’s pale face and glared at him. Sam’s own ire rose as he saw how glowing, healthy, alive Odin’s face looked; he looked like he slept ten hours a night and ate fantastic meals and exercised regularly. Odin was completely unfazed by the torture he dished out. “Very tight.”
Adonis came out of his room moments later after Odin personally woke him as well. He was prepared and already was wearing the cuffs that Odin didn’t know were fake. Sam winced as the guard dug the metal into the soft skin of his wrist and drew blood. 
Sam and Adonis’ faces were both ringed with exhaustion. They had made a copy of the code for this call as it was an extra long one, and they had both stayed up the whole night, as well as the last few nights, memorizing the words. Their scripts now burned in the forefront of their minds. 
Adonis noticed Odin eyeing the black band that was still around his wrist. He asked the guard if he could be uncuffed for one moment so he could put his hair up; it was so long he could barely see where he was walking. Odin dipped his head when the guard looked at him for instruction, and Adonis was uncuffed briefly to gather up his rich chestnut-brown locks and tie them in a small ponytail at the crown of his head. 
“You look stupid,” Odin said as they entered the library.
“You look cute,” Sam countered. Adonis grinned.
Odin looked severely at both of them as they got comfortable in the padded chairs. The pair were both getting excited as their departure date was quickly approaching and Odin had no clue about it. Adonis even bounced in his seat a little. 
“You both know how to do this. You both know the consequences.” Odin placed his elbows on the table and leaned across towards them. “I know you guys are doing something with these calls. Do not make me send you to the basement.”
Sam and Adonis let the threat sink in for a moment. They let Odin think he had the upper hand. Then Sam said, in an almost tauntingly child-like voice, “Hey Jeff, I’m bleeding all over your chair from my cuffs.” Adonis snorted loudly. “The guard clipped my wrist.”
Odin pushed off the table. “Like I care. The fabric’s red for a reason.” He dialed Selena’s number yet again and thrust the phone into the middle. He was going to allow them their little game, for now. He was determined to figure out their code tonight, so he needed the call to go how they wanted so he could get their raw wording without any quick changes or pivots. Besides, the cameras are going to be installed tomorrow. New cameras in front of their doors, and maybe a few more in the halls wouldn’t hurt. They aren’t going to be able to sneak around me ever again. 
“Hello?”
“¡Hola Selena!” Sam started. 
“Hey Sam! Feeling better?”
“Yes, much better, thank you. The investigation looks exactly as veritably interesting as it’s not good. There are lots of complications up here.”
“Definitely, but the encore continues!” Adonis chimed in. “I feel as though we’re in a very interesting television show’s seasons at this point, with all the trouble we’ve received from the weather. As the agency always says, the weeks end on the eighth day!”
“Yes, we are still making lots of progress. Nevertheless, ogling at one’s continued onslaught never thanks a caring thought. We have to focus on the positives to stay motivated! Besides, always counting kindness cheers me up!”
“It is rather boring up here, actually, with us always continuing to be doing the same pastimes. Decidedly more exciting citizens here, though. They always have stories to tell. Even on the eleventh street, where practically no one lives, there’s stories. Overally, no new news. Just the same, slowly moving forward with the investigation of interesting townspeople. Keeping the entire investigation on the down-low as possible.”
“Yes, that is everything! Sadly, we have to go again. Bye, Selena!” Sam finished, glossing over the call. 
“Thank you boys! Talk to you soon!” 
The call went faster than Adonis and Sam expected. They had anticipated that Odin would start to catch onto their code by now, especially after Adonis saw him record the last call. So, the code was made much harder this time. They still followed the basic pattern, every other sentence was important and the first letters of words were important, but they had also thrown in many unnecessary sentences that sounded like code but were gibberish. Plus, the sentences with code also had more unnecessary words, but it couldn’t be avoided unless their goal was to make an obvious word-salad. Even with the key they gave Selena, it was going to be a difficult one to solve due to the multiple false leads. 

↞⇼↠
	
December 6, 12:56 P.M.: Sam sat on his floor with the serrated knife propped straight up with his feet. He clenched the knife as hard as he could to stop it from wiggling, but it still was difficult to work with. He had spent that last twenty minutes sawing at the chain connecting his hands. Even sitting in this position had been tricky. He had to bring his hands as low to the ground as he could and step his legs through the hole his arms made. 
Eventually, the thin chain gave out and his hands were free. Since these were the real cuffs, he had no way to get the annoying metal bands off, but he could at least move things around now. 
He wrapped the sharp edge of the knife in many layers of toilet tissue and put it in his duffel bag. 

↞⇼↠
	
December 7, 4:38 A.M.: Odin screamed. He threw the steak knife he had used to eat dinner earlier at the wall, sticking it perfectly into the dark far walls of his office. A growl exploded out of his throat, viciously animalistic. His guards in the hall edged away from his doors carefully. 
He swilled the last of the red wine left in the large green-glass bottle. The dye in the alcohol matched the pigment of his bloodshot jade eyes. He briskly ran his hands through his light-blonde hair many times. Despite the high content of alcohol in his blood, his head was completely clear. 
He practically had Adonis’ and Sam’s words perfectly memorized; their voices droned in his head multiple times over, overlapping and crashing into each other. He stood up and paced around his office, his determination refusing to fade. It’s every three sentences that are important. He compared this call to the last and had noticed that pattern. Or is it every other sentence? And is it every other word? With every other word, he had gotten ‘there lots complications here’ from the first sentence. He tried letters and got ‘tileaviaing’ from the first sentence. Tile? He eliminated a few letters and got ‘leaving,’ but he couldn’t find what word came after that, and he couldn’t tell if it was actually part of the intended code. 

Trinity and Selena had strained over the call hours ago and solved it with much more success with Odin. They did struggle with the unnecessary words and sentences, but with the call they got:
tileaviaing 
dbtec 
noaocontact 
backcmup 
dmecht 
leaving 
dec. 
no contact
back up 
dec. 
	They missed a few dates in the middle, which Trinity pointed out. She asked Selena what kind of saying was ‘the week ends on the eighth;’ it made no sense. From there, they looked at the in between sentences again and finally got: leaving Dec. 8. No contact. Back-up Dec. 11, down-low. 
“I wonder what their big plan is here,” Selena mused. 
“I don’t know, but somehow we’re going to need to get back up, and a lot of it, discreetly into the mountains in four days. The valley has only one entrance, right?”
“Unfortunately, yes,” Selena responded to Trinity. “But if they can make an entire secret code, I think we can send them some back up.”

↞⇼↠
	
December 7, 1:32 P.M.: Sam pressed his ear to the thick wood, trying to make sense of what the guard and someone else was whispering on the other side of his door. Their voices were so low he eventually had to give up listening through the door to lay on the floor and try to listen through the crack. Although it was still quiet, Sam started to pick out a couple words.
“....above their rooms. Odin’s orders.”
“Why? There’s always someone on guard.”
“He’s paranoid, that’s why. He thinks the agents are somehow conspiring behind his back, even with all you on guard.”
	“He’s crazy.”
“I know. Also, the prisoners aren’t supposed to know about these, so make sure they don’t see them.”
	“What if they do see them? What should I say if they ask?”
“Just say…” the person’s voice dipped and Sam couldn’t understand what they were saying for a second. “...but don’t say that they’re any kind of monitoring device.”
“Obviously. We want to catch them on tape if they really are sneaking around.”
Sam smirked. Idiots. These doors are thick, but apparently not as thick as your skulls are. Even if the cameras have night vision and see us leaving, it’s not gonna matter. We’re leaving tomorrow night; after that we should be out of Odin’s grasp. Sam stood up and backed away as the sound of drilling whined in his ears through the crack. For wanting the camera’s installation to be a secret, Odin did not train his servants enough on how to be silent. 
Sam sauntered to his window and wiped the condensation from it with his sweatshirt sleeve. The heavy thunder clouds from a few days ago were still clinging to the air above the lake. They looked all too threatening to Sam, but they still hadn’t released their rain or snow or whatever they held in their columnal penetralia. 
Basically, the rain gutter was no longer sound proofed by snow. It had patches of slick, clear ice, but they were so sporadic they shouldn’t affect sound transmission. 
Sam broke the ice shell rimming his window panes and swung it outwards. He leaned out and down to the gutter and started tapping on it ‘A’ until he got a response from Adonis.
WHAT? Adonis asked.
SECRET CAMERAS
OH
I DON'T THINK WE SHOULD WORRY Sam tapped even faster, trying to convey all his thoughts concisely. IF THE CAMERAS SEE US IT WON’T MATTER
TRUE
They tapped goodbye but didn’t communicate anything else. Their fingertips had turned uncomfortably cold and tinged with blue. 
 
↞⇼↠
	
December 8, 12:15 P.M.: Odin glared darkly at his desk. He was spread out over his large office chair. Technically my grandfather’s chair, he reminded himself. His legs melted off the chair into the floor. His left arm was neatly resting upon its armrest and his right arm was draped halfway off, the sculpted neck of another wine bottle precariously dangling from his thumb and middle finger. His eyes were a firestorm, swirling with unbridled power, billowing dangerously with black soot clouds and fiery sparks emanating from their core. His head throbbed slightly from the constant drinking he had been partaking in for the past two days. He lifted the bottle to swig from it again.  
The heavy oak table thudded as he slammed the near-empty glass bottle on it. He straightened his oatmeal sweater and long grey trench coat and stood, leaning heavily on his desk as nausea rose in his throat. He shoved it away; he had a good history of holding his alcohol, and he wasn’t going to allow himself to ruin it now. 
Where’s Aspen. Where is that- he remembered how Adonis had reacted when he asked where Aspen was just days ago. -that cheater. I need to find her. My little butterfly seems to have flitted away from me again. 
“Guards! Find Aspen! Now!” Odin yelled from inside his room. He stumbled to the doors and barged out. A slash of sun, beaming cheerily through one of the many windows of the foyer atrium, burned into his eyes and lanced through his brain. The guards nodded to him, one guard halfway-offering a steadying hand to Odin. “I don’t need either of you. Where is Aspen?”
“She is in her garden, sir.”
Odin trudged down the hall, stopping when he wobbled once. He breathed deep into his lungs and fell against the wall near him. He breathed out through his nostrils, clenching his eyes, steeling himself. When he bounced off the wall and reopened his eyes, he no longer felt any effects from the alcohol. 
He found Aspen watering her azaleas towards the left-back of the foyer. He was in no mood to admire the sunlight playing with her hair, the flashes of white dancing on her from the quietly trickling koi pool. 
“Put down the watering can,” Odin commanded. Aspen’s back went rigid, and her mind dared her to keep tending her plants, but she listened to him. “Let’s walk.”
She laid her left arm atop his proffered right arm. As they strolled through the house’s halls, Aspen asked, “To what do I owe this pleasure?”
	Jeff didn’t answer. She resolved to not speak until he did.
	“We haven’t talked in a long time. What have you been up to today, this week in general? Even the past few weeks?” Odin finally asked.
	“Lots of my flowers are blooming. My winter flowers, that is. My summer ones are looking dreary. Oh, and I built a new house in that mining game; you should look at it. I did it on your PC.”
	Jeff smiled a little as she talked about her in-game house. She told him about how it was a big castle built with cut stone bricks and her favorite dark wood in the game. She told him how she grew berries and trees, and farmed flowers and bees. 
	“Your castle sounds lovely. I’ll have to look at it later,” Jeff looked down at her. But even half-sloshed, Odin’s mind was impressively unfettered. “Have any of your adventures needed a kitchen knife? The kitchen staff claims they are still missing one.”
	Aspen thought for a moment. “Hmmm…. I don’t think so. There was a time I borrowed a butter knife to have a cheese plate, but I’m pretty certain I returned it.”
	Odin nodded. “You haven’t visited the agents, right?”
	“No. Why would I?”
	“I’m only asking because I think you would think of them as exotic curiosities. They’ve been here for a few weeks; that’s long enough for anyone to meet strangers living in their home, no?” 
	“I-I suppose it would be,” Aspen responded noncommittally. 
	“But you haven’t seen them, of course. Or learned their names.”
	“Nope!” She busied herself by stopping Odin to mention that this flower pot needed more water. The soil was too dry, and the fern would die without more water. 
	“Any plant dies when it is not given the proper attention and nutrition,” Odin said ominously and swept them onwards. “You know, it’s just been a crazy past few weeks for me.”
	“How so?” Aspen asked, her voice full of concern. 
	Damn me. She’s pretty, Jeff thought. Her face was tilted at a perfect angle, half in shadow, half glowing a cheery orangey-pink as the natural light playfully shifted. Freckles dusted her cheeks, right under her deep eyes, and also graced her nose-tip. A nose-tip: a simple feature, something that probably shouldn’t hold too much attention on a face, but Jeff had been fascinated with the way hers stuck out just slightly from her nose bridge, a little button nose, for the longest time. And admittedly, he was obsessed with how her thick hair hung heavily, reaching to the floor, matching the graceful swoops of her heavy sea-foam dress that pulled her body down. Even her forehead had the smallest, cutest crease as her brows pulled together ever-so-slightly. He cleared his throat and looked askance, also dropping his arm. Aspen slowly lowered her hand to her side. 
	“Well, my guards have found a strange sock. The sock was all frozen from being outside, as it was stretched over the security camera in the laundry room. Before that, the prisoners somehow got clothes that I didn’t give to them. It gets even stranger. One of the prisoners was missing his cuffs this morning and the other had a plain black hair tie around his wrist that he used to put his hair in a ridiculously small ponytail.”
	“Really? Which prisoner?” Aspen asked.
	“Why does it matter?” Odin stopped and faced her again. “I thought you had never even seen them before.”
	Aspen gulped. Odin resumed their walking. He jammed his fists into his pockets to resist touching Aspen. They now were reaching the spiraling stairs, and they climbed to the second floor, doubling back on their path except for they were a floor above now. 
	“And you know what the strangest thing is, my butterfly?”
	“What, my prince?”
	“I seem to remember you waltzing around in a bloody dress on Thanksgiving. A dress that I seem to remember giving you.”
	“Psh, you’re crazy. That dress had a natural red hem; it matched the rest of it, did you not see it?” 
	“No. I suppose it didn’t catch my eye.” Odin pulled his hands out of his pockets and suddenly pushed Aspen against the wall, widely splaying his fingers on the wall, pinning her in place with his eyes. His eyes that he so wanted to clearly burn with rage and intimidation, but his eyes betrayed him; beneath the wine haze that was slowly overtaking them, lust swirled and sparked in his pupils. He precautionarily barred her shoulders with his elbows. “I don’t remember marrying a liar, Miss Aspen-Fauna.”
	Aspen screwed up her face to glare at him, wrinkling her nose as his alcoholic breath washed over her bitterly. “I guess you don’t know enough about me, then.” She cut off whatever he was going to reply with by pushing her lips onto his. She knew his weakness: her. She carefully guided Odin’s arms by his biceps, moving his hands onto her hips. She lifted her right leg and wrapped it around Odin, using it as leverage to swivel around him. She ended up in front of him with the open hallway behind her. Odin’s back slammed into the wall. She ran her hands through his hair, ruffling it, stroking her fingertips across his forehead and temples. She parted her lips, but then gently pulled away from his mouth to whisper into his ear. “And I don’t remember dating a psychopath in tenth grade. I remember a sweet, shy, misunderstood boy. I don’t remember a power-hungry man. But now all you are is a dictator, so know this: I did everything. I know Adonis and Sam by name, I gave Sam the knife, the hair tie is mine, I know about the children, I know what you’ve done to my flowers in the valley that you helped me plant last summer. Know this: you will never be enough; you are always going to be second best, a phony, mediocre at everything you ever will attempt to do. You are weak and cowardly. I do not adore who you’ve become and I loath the woman you tried to turn me into. I’m not a liar, I just have a fiery tongue when it’s necessary. I hope you know that now that I know everything,” she paused to push closer to his ear, “I know everything, I am going to destroy you.”
	She released him and thrust her heels she had slipped off while talking to him into his dumbfounded hands, hands that were still expectantly waiting for her to do more. Then she took off. She sprinted away from the man who was her past and present, and towards the possibility of a future without him. 
	Odin roared. Her heels clattered to the floor. “ASPEN! GET BACK HERE NOW! NOW!” Odin started running after her, but she had a major head start. He had the advantage of longer legs, but the alcohol was finally catching up with him and he fell to his knees and retched. Only bile came up, burning his throat, as he had eaten practically nothing in two days. He immediately got back up and resumed chasing Aspen. The halls were completely empty; servants were practiced at making themselves disappear when Odin was drunk and angry. “ASPEN, MY LOVE! WHERE HAVE YOU ESCAPED THIS TIME!”
	Aspen was sprinting as fast as she could up the opposite set of spiraling stairs, getting as far away from Odin as possible. The frigid tiles drained the warmth from her feet. Her giddiness at rebellion faded as reality smacked her and she realized just how much danger she would get in if Odin caught up with her. A few tears trickled from her eyes, scattering across her cheeks, propelled by her speed. Her flight was desperate; she hadn’t planned where she was going to go after. In fact, I hadn’t planned this at all! 
	She rounded the stairs to the third floor. Her breaths were short and gaspy. She didn’t know where Odin was, but she knew he was very close behind her. She didn’t know anything except she just needed to run. 
	A door swung open. A flash of movement.
	Her lungs crumpled as a hand stuck in front of her and caught her ribs. She was yanked out of the hallway. 

↞⇼↠
	
	Adonis was peacefully napping, catching up on sleep he had missed for the past few days. The sheets on his bed were cool around him, the blankets weighed on him perfectly, giving off the slightest pressure that felt like someone was gently hugging him. He stretched and curled his legs, enjoying the perfect balance. 
	A scream shattered the tranquillity. 
	“Aspen! Get back here now! Now!” The voice was muffled, but it was clearly Odin’s voice. He was screaming so loud that Adonis could hear him through his doors and the pillow Adonis had thrown over his face. Adonis debated remaining in bed to ignore this debacle, staying suspended between sleeping and wakefulness, but instead jolted out of bed when he heard Odin scream again. 
	“Aspen, my love! Where have you escaped this time?” 
	Adonis grabbed his lockpick and jumped to his door handle, fumbling the piece of metal into the keyhole. He decided didn’t care whether the guard heard him, but at that same moment, he heard the guard mumble a curse then hurry off, deciding it wasn’t worth the fuss to stick around. 
	Come on! Adonis thought desperately.
	The recent moisture had made the wooden doors swell slightly, messing with all the door locks in the house. 
	The lockpick struggled to find purchase on the latch of the lock. 
	Footsteps echoed in the stairwell; Adonis could barely hear each footfall through the wood.
	The pick scraped across something.
	The pattering of footsteps got closer. Heavier, louder, footsteps crashed in the stairwell again. 
	The pick clicked. The door swung.
	Adonis thrust his arm out as a blur of Aspen whisked by. She thumped into him as he clenched his elbow, whipping his hand back to himself as quickly as he had thrown it out. He wrapped his arm around her torso firmly and backstepped with her into the room. Her dress, billowing wide behind her moments ago, crushed around her legs and lost all momentum. Adonis saw a pissed, and probably wasted, Odin emerge shakily from the staircase at the edge of his vision. He snapped the doors shut and twisted the lock with the pick, still holding Aspen around her ribs with the arm farther away from the entryway. The small shaft of metal slipped from his fingers and fell to the flooring as Aspen’s rattling breaths turned into full gasps and the few tears clinging on her ethereal face turned into many. 
	Odin efficiently, and noisily, ran through the hallway, pounding on each door. “ASPEN! ASPEN, MY LOVE! WHERE DID YOU GO! WHERE ARE YOU HIDING!” His voice took on a maniacal edge. He smashed a flower pot to emphasize himself. The smash echoed in the stone hallway, clanging viciously against Adonis’ eardrums. Adonis was angry and a little shocked at how much Odin was a sad, slimy, weak excuse for a human, so evil that he would attack his own house and wife. 
	Odin continued to screech in the hall. 
	“What did you do, Aspen?” Adonis asked her in a low voice, clutching her protectively to his chest. 
	“I told him what he deserved to hear,” Aspen answered in a surprisingly hard voice, but Adonis felt her start to shake, and her panicky gasps were progressively getting louder. Adonis slowly backed them away from the entrance, the hand resting on her hip guiding her backwards with him, the other hand gently covering her mouth with his sleeve to gently muffle her breaths. 
	“Shh, Aspen. It’s ok. You’re safe with me. Odin can’t get us,” Adonis murmured. He sat them down on the rug. 
	He’s still getting closer. Adonis clasped Aspen in his lap and he swayed back and forth slightly, trying to calm her. 
	Odin stopped outside and pounded on the doors. “Hey short freak! Are you holding my little butterfly in there? She seems to have flown away!” he cackled, beating the doors so hard small puffs of dust escaped from the cracks. Aspen needed more attention than he did right now, but Adonis could feel his own anxiety rising. She shivered so much Adonis thought his own body was trembling. 
	“Aspen, what’s your favorite place in the whole world?” Adonis asked her softly. 
	“Anywhere tropical,” she whispered back.
	“I need you to imagine yourself in that tropical paradise,” Adonis said, leaning closer to her ear. “Hear the birds? Feel the sun. Smell that beautiful flower for me. I’m right here with you, and I’m not going to let you go until you’re ready, okay?”
	She nodded and reached her right hand towards Adonis’. He moved his palm from her hip to lace her fingers with his. He did not mind helping Aspen, and he wished he could dedicate all his energy to her, but he needed to prevent his own anxiety attack. He squeezed his eyes shut, trying to block out Odin’s ruckus and every other outside distraction. He imagined himself into his own safe place; a rocky cliff overlooking a great, churning sea. Sea spray washed over his face, cleansing him. 
	Aspen saw her palm trees sway gently. Her ocean was a much calmer version than Adonis' vision, gentle crystal-blue waves lapping over her feet and swirling away again. She had been to her tropical paradise many times before in her mind, run the golden sand through her fingers, seen the vibrant hibiscus flowers of every color grow in even the tiniest corners of light; she wondered how she had never noticed the feeling of loneliness in this place before. She wished she had someone to wander around her paradise with. 
	Odin was now harassing Sam’s room. He must be almost done. Then I’m sure Sam will sneak over and help us. Adonis slowly rubbed circles on Aspen’s stomach, and moved the hand from her mouth to her ribcage to pull her even closer. He hugged her snugly and buried his face into the crook of her neck and left shoulder. Her crying reduced to pitiful hiccups. 
	The pair didn’t move for a whole ten minutes. Adonis didn’t let a single muscle twitch, almost in the hopes that Aspen could forget he was even there and allow herself ample recovery time. Odin’s sounds of raging had gotten quieter; Adonis surmised he had moved onto different floors of the house or maybe had given up. He moved only when he heard his doorknob’s lock jiggle again. He lifted his head slightly to stare at the threshold. Aspen didn’t react to the sound or to the slight lift of Adonis’ head.
	Sam tiptoed in, duffel bag slung over his shoulder, and relocked the door. Adonis silently stared into Sam’s eyes, then nuzzled his head back into Aspen’s shoulder. Sam took in Adonis, sadness emanating from his body, then Aspen, a huddled figure who looked so small against Adonis’ chest. He looked to the floor and shook his head, then padded to the bathroom, filled a cup with water from the tap, then squatted next to Adonis and Aspen. 
	“Hey. Can you drink some water? It’ll make you feel better,” Sam asked, holding the cup aloft. Aspen opened her eyes languidly and accepted the drink, pulling her hands free from Adonis’ arms. He still stubbornly had his head at her shoulder, savoring the warmth there, and had his arms placed where they wouldn’t interfere with her own arm movements.  
	Aspen gently tapped the back of Adonis’ hand, and he released his arms from her, but she made no move to leave his lap. He didn’t mind; whatever made her most comfortable was fine with him. She wordlessly passed the cup back to Sam, and the boys waited for her to speak. 
	“Thank you,” she said quietly. 
	“Of course, Aspen,” Sam replied. He reached his hand to graze her cheek. She caught it with her fingertips and pressed his warm palm to her cold cheek. 
	“Sam, Adonis, were you guys trained for this?” Aspen asked, gesturing wide with her hands at nothing in particular. “Was it part of your training?”
	“No. I know a bit of this because Adonis has anxiety. He knows how to handle it pretty well, but I’ve helped him through a couple anxiety attacks,” Sam explained, his hand still held to Aspen’s face. 
	“But neither of us were prepared to deal with a wild Odin,” Adonis spoke tenderly. “I’m so sorry for all the pain that man has dragged you through.”
	“You mean that monster has dragged me through. I’m ashamed that I ever married him,” Aspen said. Hate edged her words, and each syllable lanced through Adonis and made Sam cringe. 
	“Aspen, you know none of this is your fault, right? You can’t hold guilt for something you have no control over,” Adonis asked.
	“But I did have control! I was in the adoption system my whole childhood, and when I turned eighteen, Jeff asked me to move into his grandfather’s manor with him, so that I wouldn’t be turned to the streets as I aged out. I was young, not stupid, but young and desperate and in love. I noticed how suspicious Odin started becoming when he didn’t come to dinners with me anymore, and he started yelling at me out of nowhere, but how could I complain! He had given me a house and love and a future when I thought I didn’t have one!” She lowered her voice for the last few lines and dropped Sam’s hand. So much self-loathing penetrated her words they stung Sam and Adonis. “If only I had not been a wimp, back when I first noticed his behavior becoming problematic, I could have prevented so much pain for so many people. So yes, I do hold guilt for this situation because it is my fault.” 
	Adonis and Sam overlapped each other as they spoke, both saying no many times. Sam got control: “Aspen, that is crap and you know it. You deserve no guilt from this. I don’t care how you argue the blame towards yourself; none of this is your fault. Absolutely none of it.” Sam leaned forward to crush her in a hug. 
	“Don’t dwell on the possibilities either. Even if you had talked to Odin, even if you had stopped him temporarily, even if you hadn’t moved in with him, there’s no guarantee that it wouldn’t have turned out exactly like it already did,” Adonis re-laced his arms around her midsection while whispering in her ear. Aspen nodded, a blush feathering her cheeks. 
“Aspen, do you think you can stand? I have some clothes you can change into if you want,” Sam asked, kneeling to his bag and pulling out a pair of his sweatpants. “Also, thanks for the knife. It’s been really helpful.”
“You’re welcome,” Aspen said. She let the back of her head drop to Adonis' shoulder to look into his eyes. “But, can I borrow your clothes, Adonis? I feel like they might fit me better.”
Adonis grinned. “Yeah. Do you want your hair tie back?” Adonis stood and pulled Aspen up with him. 
“No, you can keep it.” She thought for a second and added, “Only if you put your hair up in a ponytail though.” She stumbled to the bathroom to change after Adonis passed her his sweatshirt and sweatpants, the last clean set he had. He worried about having to share his clothes with Aspen while at Francis’, but they would figure it out. 
Aspen closed the door. Sam crossed his arms and stared at the floor, and Adonis leaned on his bed post.
“Sam,” Adonis said in an undertone.
“Yeah?”
“I don’t care what we have to do, but Aspen needs to come with us tonight.”
