# Carrot Soup Conference

Adonis accepted the warm bowl of carrot soup from Francis, cupping it with his hands. “Thank you, Francis,” he said.
	“You’re welcome,” Francis smiled. He sat across from Adonis. Aspen sat next to Adonis on the couch they shared, and Sam and Francis were both relaxing in overstuffed dusky-orange chairs. They all were crowded around a white coffee table strewn with papers and a few pens. The whole afternoon, and now night, they had been trying to figure out what to do next. Yes they had backup coming; but they were supposed to be arriving tomorrow, and what were they going to do with it? 
Up until about twenty minutes ago, Francis’ wife, Ariadne, had also been helping, but she went to bed. It had been two days since they had arrived at Francis’, and on top of struggling to find a plan, they were also running out of food. Francis couldn’t go into town as he still was ‘sick,’ and Ariadne had not had time to pick up some. Plus, she technically was not supposed to go to town either under the sick ruse. Francis and Ariadne had lovingly opened their colorful home to the agents and Aspen, but it just wasn’t enough. 
Adonis was only getting this bowl of carrot soup now because he had not eaten it when the rest ate dinner; he experienced a small anxiety attack and had lost his appetite. Francis had kept the soup warm for him in case he ever got hungry, which he did. 
“Francis, what time does that little convenience store close in town? It sells food, right?” Sam asked. Aspen leaned over to Adonis and slipped the hair band, which he was still wearing, off of his wrist. He put his soup on the table as she motioned for him to twist to her. 
“Yes, but I don’t think we should go, obviously,” Francis retorted. 
Sam ignored the second part of his answer. “Aspen, you draw right? Can you do any makeup art?”
“A bit, yeah. Want me to paint a disguise on you?” She caught on quickly. While answering, she also had Adonis tilt his head down to weave a thick braid starting from his forehead, tapering at the back of his head, and tied it off with the band. 
“Yes.”
“This is a bad idea, and since it's already nine-thirty, you only have an hour and a half till the store closes,” Francis warned. Sam shrugged; they needed to get food somehow. Seeing Sam was determined, Francis relented: “Alright, I’ll go get some of Ariadne’s makeup. What do you need?”
Aspen listed the products she wanted, as well as some more obscure ones Ariadne might not own but would be helpful. Francis returned with his arms full of bottles and palettes almost ten minutes later. 
“Alright, Sam. Let’s get to work!” Aspen painted over his face as quickly as she could, carefully laying colors on top of each other. Francis gave Sam a hugely oversized plaid overshirt, big boots, and baggy jeans with a frayed waistband. Aspen finished painting his face and held out a mirror for Sam to look at. 
“Nice, Aspen! It looks really realistic!” The mirror showed Sam a view of a huge scar, twisting from his right temple all the way down his neck. She had also added an excessive amount of blush, drawn on freckles and smoky eyeliner, as well as changing the shape of his face slightly by using bronzer and highlighter. He wore a puffy winter jacket underneath the plaid and he tugged the thick hood all the way over his ears. “Alright, I’ll be back in an hour with as much food as I can afford or I can carry.”
Meanwhile, Adonis, Aspen and Francis went back to work, Aspen occasionally punctuating the work with her giggles whenever she saw Adonis’ little braid. 
“Okay, we all agree that we need to rush the manor, and that when we do, the children can’t be there, but how do we do all of that?” Adonis asked rhetorically. “Is there anywhere we could hide them?”
Francis thought for a moment. “Maybe by the lake? It’s hidden and far away. However, it is cold and snowy at this time of year.”
“I think they’ll be ok. If all goes well, they’ll only be up there for a couple days,” Adonis reasoned.
“Plus, they are already in the cold anyways,” Aspen whispered quietly. Adonis twisted his head to her, studying her downcast face. She diverted the attention from her by asking, “Francis, what’s the lake like? I’ve only been there twice, and I don’t remember much about it.”
Francis listed everything that he could remember from it. The western side had a scrabbly, uncomfortable shore, but more square feet than the rest of the lake. The eastern side was always windy, as a small valley dipped there and there were no mountains to disperse gusts. To the north, fingers of trees and shrubs expanded over the hillside behind it and wrapped around the circumference of the water. There were two ways to get to it, but one of them was much more discreet and not many people knew about it. 
“Does it take any longer to get to the second entrance?” Adonis asked.
“It takes about fifteen minutes longer and you have to walk the last part because the car can’t drive up the last part of the road,” Francis described. 
“Let’s use that way to get there, then,” Adonis decided.
“I have an idea,” Aspen said. “I think…” Her brain skipped around haplessly; it was difficult to explain, but her plan was perfectly genius, fueled from years of stockpiled passionate rage. She combined the idea of rescuing the children and the rush on the manor. Every aspect was looked after, from the agency’s backup, to entering the manor, to dealing with Odin.
She finished speaking and laid back into the couch, letting her ideas settle. Francis leaned forwards and put his elbows on his knees. Lacing his hands together, he created a cradle and rested his chin, slightly frowning at a separate pen. Adonis propped his feet on the table and fiddled with the tip of his braid. 
There was only one part of her idea that Adonis didn’t like. He was nervous to broach the subject, but he eventually asked: “Are you sure you want to deal with Odin yourself? By the time you meet with him, Sam and I can probably catch up.”
She looked up from where she was pouring out her idea on a sheet of paper, a deliciously devilish grin curling her mouth. “Feel free to catch up. But let me deal with him entirely by myself. I know exactly what I want to do with him.”

↞⇼↠
	
	“Sammy! So good you’re home!” Aspen yelled at eleven-twenty when Sam stumbled through the front door, laden with food. She ran up to him and hugged him, almost making him drop all the food.
	“Aspen, shhh! Francis and Ariadne are asleep,” Adonis ran up and pulled her off Sam. 
	“Did you tell her to call me Sammy? Really?” Sam asked. “Not funny, Adonis.” Adonis held back his laughter and helped carry the food to the kitchen. 
	“Sorry I was loud, I just woke up,” Aspen explained, yawning. She plopped down on the couch, folding her legs up. “I’m so tired.”
	“It’s fine. What happened while I was gone?” Sam asked, thinking that her outburst was actually quite funny. Aspen drifted while Adonis explained her ideas to Sam. 
	“What are you going to do once you have Odin, Aspen?” Sam asked her, jerking her into wakefulness. “Do you think you’re going to kill him, to repay for all his crimes?”
	Aspen felt like ice froze her heart. “He-I-” she stuttered. “We can’t become him! If I killed him, if we killed him, we’d be just as bad as him! You don’t understand the full picture.”
	“Then make me understand, Aspen,” Sam asked. “I don’t mean to upset you, I just want to know what your purpose for cornering him is.”
	She hesitated, then started. “He has reasoning behind everything he’s doing. It’s illogical, nonsensical, but it used to be for noble reasons. Is it alright if I go all the way back? I feel like it’s more understandable, then,” she fidgeted with her fingernails. Adonis and Sam nodded. “He is the youngest child in his family, with two older brothers. His brothers are five and seven years older than him, and both were very athletic. One even became a professional swimmer. His other brother became a lawyer. Jeff, when he was younger, he just wanted to mess around with computers, which his parents saw as pointless and they didn’t really respect that, or him in general. On top of all of that, his parents often overlooked him because he was, as they called him,” Aspen cleared her throat, “an unexpected surprise. So he always tried to get his parents’ attention by excelling in all of his classes, but it was never enough. In eighth grade, they sent him to live here, in the states with some random cousin. When he turned eighteen, he inherited his grandfather’s manor, this one.” 
She took a deep breath. “Basically, what I’m trying to say is all he ever wanted his whole life was control. Control to feel special, the best, being able to control when he got attention. He never got it, so he turned to controlling people. When I first met him, he told me how he wanted to have many children and treat all of them fairly, and I admired him. I thought his dream of a world where everyones’ talents were accepted and appreciated was incredible, and I followed him for years. It wasn’t until it was too late to turn back that I realized how horribly wrong his desire for control had gotten.”
Neither of the agents said anything for a few minutes, allowing her words to sink in. They were just beginning to grasp the depths of pain that had led Odin to here. They wondered how different life could have turned for him if only his parents had approved of his hobby. 
“Even if you hated him with every fiber of your being, you couldn’t kill him, could you? A part of you still wants to see the boy you fell in love with,” mused Adonis. 
“Yes. As much as I hate myself for it, I still can see his humanity.”
“Then don’t worry, we aren’t going to kill him,” Sam said. He added cheerily, “He’s just going on a short trip to federal prison for the rest of his life.”
Aspen smiled, warmed by Sam’s gently simmering hatred.
