# A Rainstorm's Cleansing

Aspen, Adonis, and Sam were all given their own bedrooms in Francis’ house. They all went to bed after Sam declared Odin was going straight to jail and woke the next morning at five-thirty. It was an insultingly short period to sleep, but Aspen’s plan started today, when the agency’s extras were supposed to arrive. That is, if they have been solving our codes, Adonis groggily thought while eating a soggy bowl of cereal for breakfast. There was a small chance that it completely went over their heads, and Francis and Sam would not be able to guide non-existent agents to the valley floor.
Today, if Ariadne agreed to it, she was going to take one of their cars and drive to the lake to survey the area, bringing tents and some camp food with her. After the backup was brought to Francis’ house and had the situation explained to them, a few would be selected to join Ariadne. After they arrived at the lake, Ariadne and the backup were going to create a realistic-looking explosion of rocks to block the main entrance so no one could easily follow the road there. 
Sam and Francis were going to use the other car to surreptitiously travel to the mouth of the valley and hopefully catch the backup. On top of not even being entirely sure if the backup would show at all, the lack of communication made Sam and Francis unsure when they were going to arrive, so they were going to get there early and plan on staying the whole day. Francis was needed for that because he knew the best roads in the valley to sneak around, and Sam was selected to drive because he had the best vision out of everyone, so he could drive in the dark without headlights if necessary. 
Adonis and Aspen were going to pair up to sweep the surrounding area, clearing houses for the extras to stay in. 

Sam and Francis left first, right after a quick breakfast, so they could drive up while it was still dark. Francis directed their car through the most circuitous route possible to make following them difficult if any trackers were set after them. Ariadne left second after packing the trunk of her car full with supplies, raiding almost all of the food that Sam had bought just eight hours ago. She wished Aspen and Adonis good luck with their tasks for the day, and since they would probably be the first ones done, that they were allowed to do anything they wanted at the house when they got back. 
Adonis and Aspen were the last to leave, and since it wouldn’t matter too much whether it was day or night for them, they got ready leisurely. They finally went outside at eight AM, encased in layers of winter coats, scarves, hats, pants, mittens and socks in the darkest colors they could find. They pulled the scarves high above their noses and the hats low on their forehead so only their eyes could be seen. 
When they stepped out, the clouds that had been looming for days finally released their tempest. Rain mixed with hail lashed at the buildings and lightning lanced the sky, its after-product of thunder cracking and booming violently. Francis’ house and those around it were built from red bricks with jade ivy creeping up them; the lances of water and ice were so strong the leaves were shredded. The gutters next to the black pavement swirled with grey water and the strips of yellow painted on the road glimmered in the wetness and half-light. The wind whipped through the streets irregularly with quick ferocity, jangling the neighbor’s wind chimes and ripping through the bare branches of gangly maple trees. Any trace of dust was pelted away by the icy water, cleansed and refreshed. The whole street, surely once full of warm fireplaces and family gatherings at this time of year, was hollow, desolate and creepy. To Adonis, it felt like he was disrespectfully trampling around a dystopian mausoleum.
Adonis and Aspen trudged through the rain, hunching under eaves and dashing from cover to cover. At one point, Aspen fell behind and Adonis ran back to her.
“Aspen! What’s wrong?” he yelled over the storm. 
“Nothing! I just love thunderstorms!” she yelled back jubilantly. She had fallen behind because she was watching the clouds for more flashes. Adonis agreed that thunderstorms were amazing, but lightly pulled her away with her wrist; as much as he yearned to watch for lightning with her, finding hiding places for a team of people was more essential. 
They slinked around the streets until 4:00 PM, declaring almost twenty houses as safe after checking if they were abandoned and removing all the security bugs they could find. They were almost caught a few times by Odin’s security; ever since they had gotten away, pairs of security members walked Briarcliff’s streets, looking out for any sign of Sam, Adonis or Aspen. Sometimes while Adonis and Aspen were in a house, the guards would break the door and barge in, making them have to quickly jump into closets or cupboards. The huffs of their breaths were strained when these moments happened, and Adonis’ and Aspen’s hearts skipped every time the soldiers stepped on nearby floorboards or yelled to each other. The pair waited long minutes after the soldiers left as noisily as they came, fearful they would come back. Inching back out, Aspen and Adonis would stare at each other’s eyes through cracks, and then tenderly ease out and creep around the rest of the house. When they decided a house was completely clean, they marked it by jamming a small pebble into the cracks of the front doors. 
Finally, after sloshing through the streets and slumping back to Francis’ house late that afternoon, they stepped through his threshold sopping wet, cold, tired and hungry. Francis and Sam had still not returned from their mission. 
“Aspen, do you want soup or something?” Adonis called from the kitchen. Aspen had immediately ran to the living room, moved the coffee table to the side, pulled out the hidden bed from the couch that she and Adonis had shared last night, and crashed on it. Adonis had run to the kitchen and sifted through the cabinets for something to eat. Their winter clothes lay in a jumbled heap next to the front door. 
Aspen clicked through the stations on the television, pausing her searching once she found her favorite fashion show playing. “Yeah, can you also bring some chips?”
“Mhm.” Adonis microwaved two bowls of canned tomato soup, cracked fresh pepper on top of the warmed bowls, and grabbed a bag of barbeque-flavored potato chips. He joined Aspen on the couch, handing her a bowl as she draped a thick blanket over them. He saw her choice and said, “Oh, I love this show!”

His head dropped to her shoulder to share her warmth as they watched the episode. Adonis glanced at the clock on the wall when the episode ended, reading 5:26 PM. “I wonder why they aren’t back yet,” he mumbled. He turned his head to look at Aspen’s face. Thick lashes framed her eyes, casting a light shadow onto her lower eyelids, adding layers to their ocean depths. Her eyelashes were a shade lighter than he normally saw them because she had no mascara on. “It’s alright with you if I lay my head on you, right? I show affection through touch, but if it makes you uncomfortable, please tell me.”
“No, it’s fine. I’m touchy too,” she said while scratching his scalp with her nail tips. She stretched away momentarily to place their bowls and the bag of chips on the coffee table, then shifted Adonis so his back rested against her chest and she had free reign over his hair. She combed through his thick locks with her fingers and rebraided it, making it much more complicated than the previous. She worked in three small braids that started thin and got thicker towards the back of his head, then wove them together and tied them off with a small, fluffy pony tail sticking out at the base of his head. 
Neither of them noticed as they slowly drifted to sleep, and neither of them woke when Sam and Francis returned, their mission having gone successfully. The backup the agency managed to gather was forty strong, and five were going to leave for the lake in the morning to meet Ariadne, and the others were going to stay safely hidden in the houses and wait for more instructions. 
“Do you think we should wake them to move them to their bedrooms?” Francis asked, bending to pick up Adonis’ and Aspen’s head of soiled clothes. “It’s almost ten.”
“No. They look comfortable,” Sam said, stretching and preparing to go to his own bed. “Besides, they look really cute.”
And so Adonis and Aspen were left alone, together, on the lumpy pullout mattress. 

Adonis jumped awake, panicking momentarily as he thought he was trapped. In reality, it was just Aspen’s arms lightly resting on him, but in his half-asleep state, they felt like weighty chains anchoring him to this world. He fought off her arms and sat up, slouching over his folded legs and clutching his forehead. 
Aspen slowly woke and watched him. His back quivered, and she could see him hunched over, even in the dark. She waited for a couple minutes before asking, “What’s wrong?”
He took so long to answer she thought he might not answer at all. 
“I had a dream about my dad.” His voice was throaty, as if he had been crying. “Francis reminds me so much of him.”
“What was your father like?”
Adonis sat back into her arms, feeling the fingers of the dead swipe at him, wiping away ghost tears from his face. 
“He was...an enigma. A good man. A good dad.” Adonis struggled to think of the right words. “When I was younger, I loved to wear skirts and blazers and dresses and board shorts. I still do- clothes are a form of expression. He always told me how good I looked in everything, and when kids made fun of me for ‘dressing like a girl,’ he always told me fabric doesn’t have a gender, and why should I care what others think if I like it? 
“He taught me to respect. Respect elders, parents, superiors, boys, girls. He taught me chivalry and manners. He taught me how to be a decent human being.”
Aspen stared at him, analyzing his face in the small moonlight that her eyes had adjusted to. She saw his wet eyes, blushing cheeks, crinkles fanning from his nose bridge. She heard the admiration, the praise, the happiness in his voice. And she also heard pain and regret and deep sadness. Adonis’ eyes were locked to the wall. He swiped at his nose and eyes, sniffling quietly.
“And then he was gone. I had him for thirteen years, and then the doctors gave him too many painkillers and he was gone.”
Aspen stared at the wall too. “I’m so sorry, Adonis.”
He answered softly, “Don’t be. He was sick for a long time. And loads of people have dead people. I’m not the only person to ever be sad, so I can’t really be sad about this.” 
“Other people’s pain doesn’t invalidate yours.”
Aspen held him like he had held her, refusing to let him go until he wanted to. He cried silently, not even his breathing making noise. Eventually, they were both pulled back into sleep. 

↞⇼↠
	
Adonis and Aspen were not the only restless sleepers that night. A large, mid-thirties guard was tromping around Odin manor, crushing rocks and ice beneath his heavy winter boots. Since Odin had been incapacitated when the agents managed to sneak away, he hadn’t seen which guard had been on patrolling duty, so this guard had also managed to escape his punishments. Even so, the guard still felt jumpy and uncomfortable, as though he was white-hot iron on an anvil waiting for the hammer to strike. 
He stopped at the shed where he had lost the agents, inspecting the area for any sort of clue as to where they had gone. They just vanished. One second I saw them, and then they were gone! he thought anxiously, knowing it was a weak excuse to cover himself if Odin were to push him. 
He put his flashlight in his mouth and broke through the thin door on the shed, more concerned about himself than the state of the shed’s door. He frantically dug through piles of dusty tools, seed packets and bags of soil, shattering pots and disorganizing everything in his desperation. His stomach dropped as he found nothing incriminating in the shed, not a secret door, not a footprint, not even a scrap from one of their clothing items.
He backpedaled out of the shed, feeling his heart beginning to race. His hands shook, and the rain was still pelting ferociously outside as it had the whole day, soaking through his guard’s vest as he tried to prop up the sagging door he had just broken minutes ago. 
He dashed around the shed, once, twice, and on the third time, he tripped and fell onto the rough pavement, painfully pushing all the air out of his lungs as he crashed. He muttered a curse darkly and slowly rose to his hands and knees on all fours. His flashlight had rollen away some feet, and he leaned to grab it, looking around for what had tripped him. He was close to the border of the forest, so he thought maybe a root or a rock had made him fall. 
Instead, he found a poorly concealed rusty grate. 
The area around it made it look like it hadn’t been used in at least ten years, with creepers and detritus nearly covering the entire thing. The hail had pelted away at the covering, exposing the old metal to the rain. There weren’t any footprints near it, but there wouldn’t be anyways after the rain had poured and gurgled down the drain, whisking away anything that might have been left behind from the agents. 
The guard carefully lifted the grate and climbed down the shaky ladder, dropping the last few feet into the cavern below and listening warily as his feet made ominous, echoey ripples in the stagnant water. Dark tunnels were in front and behind him. His flashlight barely made a difference, and the whole concrete structure had a ghastly, haunting look to it from the wan light shining through the grate. His satisfaction rose tremendously as his flashlight caught on a scrap of waterproof fabric, the same fabric Sam’s duffel bag had been made of. He probably shredded the bottom when he slid away from me.
He fingered the fabric, thinking. If he found the agents, he would also have to turn over Aspen-Fauna, a lovely woman who had always been solicitous. She had comforted him one night when he was first brought to the manor and he learned that his twin brother, who lived in the ‘big city,’ was badly injured in a car accident. That was months ago, when he got the quick call from some Helena hospital’s nurse to deliver that horrible message. With Odin’s massive restrictions on cellular communication, he got no further updates and presently was still uncertain whether his twin was alive or not. Sure, before the restrictions, the guard hadn’t been the closest with his brother, but it still hurt a lot to hear that your only sibling was in critical condition with his body ripped crosswise. The guard just decided to assume his twin had passed in order to save himself from prolonging grieving by uncertainly waiting forever. I should have talked to him more. He’s gone now. I can’t believe how wide the rift between us grew without us noticing. I barely talked to him, then he was rent head-to-hip and died. The guard sniffed, crinkling his nose, and shook his head to clear his twin from his mind.  
Even though he was older than Miss Fauna, she seemed much more aware and developed beyond her years, and had patiently comforted him with a practiced method again when he realized he would probably never see his parents again. She had secretly comforted innumerable guards, recruits, and children, risking her safety from Odin to offer a hug or kind word to a housestaff. 
The guard almost blushed a little when he remembered how tenderly she had hugged him. The tiniest smile lit his face. She was so small, light, warm, and perfect. Ah, I wish that I could find a girl like that. Odin is one lucky dude. 
He tucked the scrap of fabric into a pocket in his pants. He mindlessly climbed the ladder to the grate he had left propped open using a stout stick. He punched the stick out after reaching his arms out and dragging more leaves over to cover the grate. The stick clattered drily against the rocky street. 
He grinned and dropped from the ladder. His loudly echoing splashes sounded much more tamed and distant now. His flashlight also seemed to be brighter, penetrating the darkness efficiently. He even swore that he could feel the sensation of Aspen’s arms wrapping around his midsection again, feel the warmth of her face the same as when she had pressed it into his abdomen as he crumpled around her, the slow stroking of her fingertips on his back to comfort him as he sobbed. 
Imagine the glory I could win if I find them.
