# The Dispersion of The Agents

Adonis startled awake again, just hours later, when he heard loud knocking. He jumped, reflexively hovering protectively over Aspen. 
	Aspen opened her eyes and blinked in surprise as she saw Adonis’ neck and jawline above her. She fought off a blush that was trying to warm her cheeks.
	Francis walked out of the kitchen where he had been eating his breakfast and almost choked on his food while trying to suppress a laugh. “Don’t worry Adonis, it’s not Odin at the door. I told your backup’s leader to come over this morning so we could talk.”
	Adonis fell to the side and yawned. “Oops. Never hurts to be prepared.”
	“That’s true. Good morning, ladies!” Francis said, opening the door. 
	“Hello! Thanks for letting us use your house.”
	Adonis jumped up again, scrambling over the couch’s armrest as he recognized the person’s voice. “Selena!” Another person walked in. “Trinity! You guys are leading? I’ll go get Sam!”
	Francis’ house was a flurry of excitement as four more agents walked in, Aspen and Francis meeting each of them, Adonis dragging Sam out of bed, and all of them moving to the kitchen for a meal. 
	“Do any of you want me to make you something to eat?” Francis asked to no one specifically, raising his voice to be heard over the chattery din. 
	“No, thank you. We already had some food that we brought with us,” Trinity answered, though she did make herself comfortable on one of Francis’ counters. 
	“So, these are the drivers you selected?” Aspen asked. She didn’t know how many agents there were, but five seemed like a good amount to join Ariadne at the lake. 
	“Yes. I’ll lead this, and Selena is here because she will help lead the other pack,” Trinity said. “I’m assuming you’re the mastermind behind all this?”
	Aspen responded, “Only the last half. Adonis and Sam were the first part.”
	“Well, we had to make small alterations to your plans, unfortunately. The five of us are all still going to go, but we can only bring one car up to the lake because we’re going to have to steal it.”

↞⇼↠
	
	I clambered into the front seat of the car to drive it. Unluckily, all the vans from the agency are bright white, which is not good for stealth missions. This car was Francis’ neighbors’ car, an old, black, mid-size 2013 model. Sam and Adonis knew how to hotwire, and Francis decided his nonexistent neighbors wouldn’t mind if their car was stolen in order to free their children. Another complication to the plan was that all the cars we were going to steal had to be older models; newer cars had steering features against hotwiring that forced the car to only drive in a straight line. A complication I’m glad I don’t have to deal with, I thought wittily. 
	“Trinity!” I unrolled the window as I heard Selena call to me. She leaned over to hug my neck. “Goodluck.”
	“Thanks. Bye everyone!” Sam, Francis, Aspen and Adonis all waited in a clump next to the front door, shivering in the cold. They retreated inside with Selena as I grabbed the passenger headrest and reversed out of the neighbor’s driveway. Addressing the four others in the small black car I said, “Let’s go.”
	As we wound our way to the lake, the massive rainstorm was finally beginning to look like it was lifting. Good timing, actually. It should make the dirt, or whatever material is next to the main road at the lake, softer and easier to move.
	Just like Francis had said, the drive to the lake was short. In only twenty minutes we made it to the tall slate cliff sides that made up the mountains surrounding the entire valley. Even though the anvil thunderheads were drifting away slowly, water still ran in rivulets all down the rocky faces, and the lake still had strips of fog weightlessly swirling on it. 
	I parked the car under a solitary giant pine and stopped the engine by unfastening the ignition and battery wires. My cohorts unloaded the trunk where we had shoved in more tents and food and started walking around the lake to reach the far western edge. I almost slammed the door shut, but decided to leave it open so I wouldn’t have to break into the car and set of it’s alarm. I was scared about the battery dying, but shouldn’t have to drive it again; if I did have to drive it again, it would only be because the plan went poorly. 
	Grabbing the last two bundles of supplies, I did kick the trunk closed and followed the uneven footsteps left behind in the fine gravel. The scenery was strange: the mist muffled almost all sounds, and sometimes it was so thick I couldn’t see in front of myself and I almost ran into grey rocks or the grey-tinted trees. That was another thing; everything was grey, misty, drab, with the only small pop of color coming from the viridian leaves on shrubs and evergreens. My breath curled in white wisps in front of me when I exhaled, and when I inhaled, my throat burned from the cold. The lake was at even higher elevation than the rest of the valley, and each breath was insignificant and left my body craving more oxygen. The edge of the lake had thin sheets of ice floating on its surface that melded into hoarfrost creeping up the shore, freezing small pebbles together. 
	“Trinity! Are you out there?” one of my companions called. I wasn’t incredibly far behind them, but remembering how Sam told me to stop the car took longer than I thought it would. 
	“Yep! I’m coming!” I yelled back. I walked another ten feet, and through the shifting fingers of fog, I saw a red-golden glow softly illuminating the air. A small area had been cleared beneath a craggy overhang and I saw a woman I hadn’t met before, hunched over and tending the coals. The other four people I brought with me worked in groups of two to set up tents, tarps and rainflies. I dropped my bundles onto the pile behind her and said, “Hey, you must be Ariadne? I’m Trinity, the unofficial leader of this little pack.”
	“Pleasure to meet you. Ready to help save the small world of Briarcliff?” she asked.
	I smiled. “I’ll do my best, ma’am.” 

	“Steady, okay, now just fit the rope into the pulley!” Will, another agent, called to Trinity over the roar of the wind. The group had traversed around the lake again, and now were at the east side of it, fighting to stay balanced on the steep cliff faces while they were buffeted with gusts. Trinity, Ariadne and two more agents stood on one high precipice, and Will stood on one opposite them, about twenty-five feet apart. The main road was in between them, and a rope was stretched from a pulley in Ariadne’s hand to Will’s hand. Will tied the end that he had to a large, but old, tree. The tree looked as though it would be impossible to pull out of the ground because of its age and probably countless roots, but it was actually dead and hollowed out; it looked like it had been struck with lightning years ago. Will finished fashioning his knot and yelled, “Pull!”
	The last agent they had brought with them was on the road, slightly farther up it to be precautionary. The group of four yanked hard on the rope, struggling to stay upright in the slick mud, and Will backpedaled away from the tree as it lurched. The hollow wood was gratingly dragged over the edge of the drop, and with a resounding boom, it crashed to the road below it. It was so long it got stuck in between the two cliffs, the rooted part of sticking into the air. The agent on the road ran up to inspect its placement and make sure it was secure. He gave a thumbs up and the team cheered.
	Now we just need to shove some rocks in the way as realistically as possible, Trinity thought. They were trying to block the main entrance to the lake so it would be harder to find them. If Odin even guessed that they were staying at this distant lake and tried to pursue them, he would have to first know of or discover the secret way in, and secondly sneak past the security they were going to put there. 
	So, for the next three hours, in a mist that was light yet heavy enough to slowly soak their clothing, the agents pushed rocks and branches into the road and smeared handfuls of mud all over the blockade, as well as drew streaks behind it to make realistic pathways as to where all these boulders and branches could have rolled in from. 

↞⇼↠
	
	The backup plus the agents plus Aspen plus Francis almost numbered the original count of back up before five had gone to the lake. Thirty-nine people crammed into the corner of a house, a house just across the street from Francis’. Aspen was addressing them all, trying to talk loud enough so everyone could hear her but not so loud anyone outside would be able to. She told everyone how she needed seven more volunteer drivers who were good at memorizing directions and everyone else was going to follow her into the storm drains. Six people volunteered easily, but when a seventh was indecisive, Francis took the spot.
Aspen quickly explained her plan through again, speaking so quickly that she hoped her audience had good memories. She knew that in order for her idea to work, they needed to act quickly on it now. The large group that wasn’t the drivers was broken into smaller groups; a tiny cluster of three who were going to leave the building first and restrain any nearby guards to make sure the pathway was clear to the entrance of the underground rain gutter; a group that was going to escort the children back to the cars; and a last group that was going to follow Sam and Adonis, after the children were handled, to takeover the perimeter of the house.
	When Aspen finished, she stepped back to lean against a wall, allowing a moment for her ideas to sink in. A few scattered drops of water splashed against the floor, dripping from a fist-sized hole in the roof. Sam stepped forward and began the mission by snapping his fingers then flicking his hand to the door twice; from now on, they were going to be as quiet as possible. The cluster of three were passed extra scarves, and they crept outside. Everyone else tensely waited inside, some tentatively rising to their feet. 
	Two of them came back, dragging Odin’s guards backwards by the scarves they shoved in their mouths. The third crouched under the eave outside, their squinted flinty eyes scanning the road for more of Odin’s puppets while retying their scarf to hide their nose, lips and chin. The group filed while the guards were restrained with tight bands of tape around their wrists, elbows, knees, calves and ankles. The scarves they were reined in with were also tightly knotted around the back of their head. 
	
Francis led the six drivers away with him to the cars. Their need for memorizing directions came in then; instead of all concentrating at one storm drain, they were going to scatter to seven different entrances. 
After hijacking the biggest, darkest cars the agents could find, they drove to their manholes and parked, praying there would be enough space for all the children. 
There could be a hundred or a thousand children there, Francis thought grimly. Aspen said she saw what she thought were hundreds of tents staked in the ice, but she was also stressed and shell-shocked; she might have accidentally inflated the number. Although Francis desperately wanted all the children, the pure, innocent children to be rescued, his selfish priority was to see Ambar and Coliban out first. 
He didn’t like physical touch very much, but he ached with desire to embrace them. He ached to bring his family all back together, to just watch Ambar and Coliban talk or play or even fight. He just wanted to hear their voices, together. 

Aspen and Adonis dashed ahead, leading. Their skin felt prickly and sensitive, high alert at all times. Their jogging from structure to structure and dodging behind them tired them and made them gasp, but instead of the ice-air stabbing their lungs, it refreshed them and cleared their minds. 
Sam trailed at the end of the group, defending their back. He was on high-alert as well, but he was even more stressed then the others. He jogged backwards loosely, his baggy sweatshirt and fluffy hair flouncing slightly with each little jump he did, trying to prevent tripping. His right hand subtly rested on a heavy, angular metal object in his pants’ pocket. Adonis and Sam, along with the other agents, were trained to use guns, but Adonis hated them because he thought they were cruel, unnecessary, messy, loud, hard to aim, and a million other horrible things. He also had the long smuggled knife tucked in a sheath he fashioned to a belt loop on his left side, bouncing along with each jerk of his hip. 
He didn’t want to use the gun, but he also wasn’t going to allow anything to mess up the plan, the last chance he would probably ever get to dethrone the twisted king that was Odin. 
	The group reached the storm drain and quickly dispersed into the alleys and shadows of the worn-brick building walls. Sam circled to the front with Aspen and Adonis and dug his fingers into the tiny crack around the manhole cover. 
	“Three, two, one,” Aspen counted. She had two fingers shoved into one of the small finger-holes, and Adonis crammed his middle finger into the other and clutched that hand with his other one to give more support. Even though it had been exceedingly easy to get out of the manhole cover when they snuck into Francis’ house, it was much harder to get in because they had to pull the cumbersome cover up instead of just pushing it out. 
The three strained for a few seconds, grunting and pulling, till the metal finally slid noisily out of place and allowed them to get in. Adonis jumped in immediately, Aspen hovered near the opening so she could push the lid back in place, and Sam herded the group over as they trickled out of their hiding spots. The agents efficiently made their way in, and Aspen closed them inside the concrete cavern after shoving the lid halfway over, slipping in, and fighting the last half of it back in place. It landed slightly crooked, but since the rest of the mission was only going to take a few hours, she didn’t care enough to fix it. She pulled a small keychain flashlight from her back pocket, balanced it in her teeth, and dropped from the ladder, falling almost ten feet to the murky water and sending a cascade of stagnant water straight into her pristine hair. 
	“Lovely. That’s going to be fun to rinse out later,” she said in a fake-disgusted voice. She spat the small flashlight into the palm of her hand and shook her head to fluff out her hair.
	“Nice splash,” Adonis said, sidling next to her. “But I’m afraid we have a complication.”
	Confused, Aspen looked up at his face, searching his features for something amiss, then turned to the group, all who were clustered in the center of the dingy passage. She gently tapped their shoulders and parted the wall of flesh.
	Sam was facing her, but was halfway bent over behind a cowering man who had his face angled to the water and his hands above his head. Sam pressed the cold metal gun in his hand to the man’s head. Ferocity cast a wild, beastly twist to Sam’s face.
	Sam looked at Aspen. “You know this guy?” he asked.
