# When Do “Byes” Become Permanent?

“He seems to think he knows you,” Sam said. He pushed the gun harder to the man’s temple and placed his other hand on the man’s back, shoving him closer to the ground until his nostrils were partially filled with the grey water. Bubbles trailed leisurely from his nose and wrapped around his crouched legs and back as they followed the creek’s weak current. The man struggled and writhed, fighting Sam until Sam stepped one leg over the man, still forcing the man into the concrete, and leaned close to his ear, whispering, “Be careful. You’re wasting your air when you flop around like that.” The man stilled as Sam’s hand proved to be unrelenting.
	The other agents, Adonis, and Aspen watched this exchange as if it was a theater performance. Aspen broke the silence by splashing her way up to them, grabbing a fistful of the man’s hair and wrenching his sodden face up. The barrel of the gun banged against his forehead and she hoped it would leave a bruise. 
“Sam, kindly allow this man into my hands,” she commanded. Sam took back his hand and started tucking the gun back into its pocket, but Adonis stalked up and grabbed it from him. Adonis still loosely angled the gun at the man's head, but now at an arm’s length away. 
Adonis’ hand trembled slightly as he whispered quietly to Sam, “You’re way too angry right now to handle this weapon. And, you know how I feel about guns, Sam,” he used his forearm to push Sam out of the situation. Adonis tore his eyes away from their prisoner to look up at Sam. Shame hooked in Sam's stomach, and he looked away from Adonis. Sam felt Adonis' eyes burning through him, surely the same as the cowed man would have felt the bullet burning through his brain. Adonis was right; Sam had let his problematic older-brother hot-head side take control again. 
“Sorry, Adonis.” Sam lowered himself to the concrete, not caring that he was laying in filth, and closed his eyes. Their coworkers marveled at their relationship, some impressed that Adonis dared challenge Sam’s infamous imperial temper, or that Sam, the hulking beast he was, could be tamed by Adonis, who was always cheery, unthreatening, and easygoing. Their attention was drawn back to the center again when Aspen started talking again.
“Light. Now, please.” Twenty beams of light instantly illuminated her and the man, washing out their features in a ghostly radiance. The light also played with the murky water, brilliantly sparkling against the small ripples. “What are you doing here?”
“What do you think I’m doing, princess?” the man jeered, smiling haughtily. Adonis gasped softly as he saw the man’s face, but Aspen ignored him.
“I don’t know, Carter, are you looking to capture me? Or maybe Sam and Adonis? Are you here on Odin’s orders or your own? How many of you are there in the sewers?”
The man was unbalanced by her, disturbed and surprised that he remembered her name. I haven't talked directly to her in almost two years. “Uh- I’m..I’m here by myself. I, um, was hoping that I- I could bring you back, err, well actually them, not you.” He tried to look away sheepishly, forgetting the fierce iron grip Aspen had on his hair, which was actually starting to flare a small headache. “You were kind of just a bonus.”
“A bonus? Hoping to bring in some favor for yourself? Fan your own flames? Your truth is admirable,” Aspen spat. The man, Carter, cringed. “I suppose you thought I would be an easy target as well. How disappointed you must be when you realized I’m not the weak, shallow lady-of-the-house. I’m sorry I ever gave you that false impression.”
Carter swallowed. “Ma’am, you remember my name? How?”
“I remember a bastard when I see one,” she retorted. She cocked her head and answered again, “And I also remember a person who is deeply hurt and thinks that a kind woman can ease his sorrows.” She let her voice go quieter. “I think of myself as a kind woman, but only until my patience runs thin. Right now you are running and treading all over my patience, Carter Joholock. You are preventing small, sick children who are hungering for warmth, for being saved. I hope your twin did die in that car crash.”
Right at that moment, another man stepped from the ring of shadows into the halo of light. His voice broke, pitfully quiet. “Carter?”
Sam opened his eyes, wide, rubbing them. Joholock. Of course. How could I forget? Prince and Carter Joholock. 
“Prince?” Carter said in disbelief. His eyes welled with tears. Standing ten feet in front of Carter was his mirror image, Prince, a perfect resemblance except a wire-thin scar that stretched from his right hip, around his chest, and up to the start of his hairline. His twin brother. “Prince, why did you take so long to step forward? You know me. I’ve missed you so much I thought you were dead how-”
A cold wall fell over Prince’s eyes. He stopped his slow march to Carter. His words sliced the air. “I suppose I didn’t recognize you through the thick layer of cowardice and treachery.”
Carter’s face fell. Aspen realized that Prince was the twin to Carter, the twin she had just wished death upon, and she regretted what she said seconds before, but she couldn’t let any weakness show. Instead she looked to Prince and said, “Sorry, I don’t truly wish you dead. I am so sorry that you were in a car accident; from what this loser said, it sounded pretty bad.”
Prince acknowledged her apology with a quick dip of his head. “It’s not all horrible. The many surgeries afterward to reconstruct my organs and bones left me with this scar,” he pulled off his shirt. While they could see the part of his scar on his face before, now everyone in the concrete room could see the mark coiling down his torso, permanently marking him. He pulled his shirt back on after eyeing everyone in the circle challenging them. The faces of the agents, his coworkers, showed nothing, but all of them were secretly equally empathetic and proud of him. “I’m glad I was almost killed, sawed in half, and reconstructed so that I was branded with this. At least I don’t look exactly like him anymore.”
Prince stepped forward again and crouched next to Aspen, who still held Carter’s head aloft. Carter started babbling: “Prince, how are you here? I thought it was just these three, why are you working with the enemy? How are you on their side? We are BROTHERS, damnit, you should stand with me at all costs! We are family! We have been bound by blood since the day we were conceived! We split off from one another! We are one and the same, my brother!”
“Shut up, Carter!” Prince yelled. “We are not the same! We could not be more different!” He let Carter sit for a moment to understand he was serious. He sneered, “I am not working with the enemy. You became the enemy the day you decided you were going to support a monster, nay, a demon who does this-” he gestured wildly, “-to people! Just as you are complaining we were torn apart, that ‘we’re family,’ can’t you see you’re helping a beast who’s doing just the same? You are a fool, Carter. I’m ashamed we have the same face.” Prince twisted away and began to stand.
“This wasn’t my choice, you ass! I was forced to work! I’m just doing my best, okay?” Carter sounded furious. Prince stopped moving, but didn’t turn back.
“It became your choice the moment you decided to hunt down the one woman who apparently comforted you when you thought I died, the one woman who is going to stop all of this. The woman squatting in front of you.” Prince stood and walked back to the darkness. Carter looked to Aspen, glaring, but then felt his glare soften. He looked at the ground shamefully.
“Kill me,” he asked her simply.
She looked sadly at him, compassionate to a fault. “No. I refuse to become a murderer for your sake. Your twin can decide your fate.”
From somewhere in the darkness, Prince called, “Wrap him up with the tape. If you can, completely encase his body, then tape him to the wall, right underneath the grate so the cold wind will hit him. Then pray for snow.” He leaned his head out from between two people’s shoulders. “Carter, when this is done, I am going to pick you up, take you down the mountain, and show you my beautiful wife and your two lovely nieces. I hope that we also have time to visit mom and dad.” 
Carter turned pale. Four people from the group who had rolls of tape encircled Carter and started binding him. Everyone else walked ahead, up the branch Carter had just walked out of fifteen minutes ago, traveling to the manor. The four would catch up, following the very obvious markers the group would leave behind for them. 
“Wait-!” Carter tried to yell after Prince one more time, to say goodbye, that he was sorry, that he couldn’t wait to meet Prince’s bride and kids, that he loved him. He was cut off by an agent tightly taping his mouth shut.
It was apocryphal that Carter and Princes' reuniting later would be anything remotely cheery.

“Again, I am so terribly sorry for saying I wish you had died. You seem like a very pleasant person,” Aspen said desperately, feeling awful over how that whole situation just went. She, Adonis, and Sam all walked at the front of everyone, but Prince had joined them as well.
Prince laughed. “It’s fine! I thought it was pretty funny, actually,” he reassured her. Aspen asked him about his daughters, and he happily chatted to her all about them as they followed the steep incline of the concrete to the manor. 
While they talked, Adonis gently nudged Sam’s arm. He pulled the gun out from his sweatshirt pocket and, after double checking the safety, twirled it around his finger. “Sorry. I didn’t mean to embarrass you in front of everyone. I was nervous about you using it on Carter when you were so close to Aspen.”
Sam smiled lightly. “It’s fine, Adonis. You were one-hundred percent right about taking it from me. I was so frustrated, and although I really didn’t want to shoot, I’m not sure if I had complete control of myself. Thank you.”
“Of course, Sammy. I just want you to know I’m sorry for embarrassing you if I did, and that I do trust you with a gun. Well, most of the time, anyway. We’re cool?”
“We’re cool, Adonis. As long as you don’t call me Sammy,” he joked. He didn’t actually mind that much. Adonis passed the gun back to him, but Sam just passed it to the agent behind him. He didn’t actually want the gun either. 
“Sorry, this is random, but are you guys dating?” Prince asked over Aspen. Sam and Adonis immediately cracked up, hollering so loudly Aspen was nervous the whole valley could hear them. 
Sam composed himself first. “N-no, we’re not dating. I’m actually aromantic, so I’m just not really interested in dating anyways.” 
“Although, and I have told Sammy this before, the first time I talked to him may have been because I thought he was cute,” Adonis slyly admitted. Aspen glanced away from Adonis’ eyes for a fraction of a second. Adonis noticed and joked, “Don’t worry, Aspen. I’m bisexual.”
Aspen stuck out her tongue as Prince hooted. They crested the steep hill and ended up in the chamber where the first grate, where this adventure had begun, hovered high above their heads, embedded in the concrete, laced with swirling vines creeping all over the rusty bars. The group paused for everyone to file into the room, and the room echoed quietly with labored breathing as the four who were left behind caught up after running the whole way. 
The concrete in this junction was much drier than the tunnels they had started in, and it was much drier than it had been a few days ago. Since it was near the top of the mountain, the only water left in it came from the only other tunnel connected to it, which kept going up the hill. All of the water from there drained through here, but only the tiniest creek wriggled through the middle of the concrete floor, wending through the center of a path carved from many other rainy seasons. Its track dipped slightly and was gently worn into the stone, permanently stained a light brown from years of stagnant water sitting during the dry seasons. The tiny creek was illuminated by the wavery late-afternoon sunbeams gilding the grate; the orange light threw itself against the walls and made every small drop of water that dripped from the delicate leaves of ivy poking through glow golden. The grey, dank concrete box lost its angular edges and hard construction, seeming magical and ethereal, full of life and possibility and wonder.
This is beautiful, Adonis thought. His chest ached with the simplistic gorgeousness of soft sunbeams. He yearned to run away, run away from his problems and life, to where he didn’t know and didn’t care, just yearning to feel free. He thought, It’s amazing how different this cavern looks in sordid nighttime lighting versus this gold heaven spilling in.
Aspen clapped her hands twice to bring attention to herself, and she climbed up the first two rungs of the ladder to raise herself above everyone. She wove herself around the bars, sitting on the second one, and resting her arms on the third. The sun just barely adorned her blonde hair, casting a goddess’ glow around her. Adonis leaned against one side of the ladder and Sam on the other. 
“This isn’t our final stopping place. We are going to continue through the other portal,” she pointed to the uphill branch, “and at the top of that, we are going to get out. I stopped us here because I think this will be the last place I can give out directions. Just as a few final reminders: I am going to the manor alone. You all are going to free the children; that is your first, primary, most important priority. Keep in mind that they are children; they are going to probably panic and be afraid, but try to reassure them as much as possible. Once you take the camp, Adonis and Sam are going to split off and follow me, as well as fifteen of you they have already selected to control the perimeter. The rest of you are going to come back with the kids; you didn’t have a leader before, but I think I’m going to give you one,” she paused and looked at each of their eyes, patient, loyal, intelligent eyes. 
“Prince, you’re not helping in the perimeter, right? Good. You will lead them.” Prince nodded. “You will split off again, and work your way to the seven different pickup sites. Make sure all the children fit in the cars. Pack them in, have them lay or sit on top of each other, whatever is necessary to fit all of them in. That is going to be the hardest part, but try to be as patient yet firm as you can. If you yourself cannot fit in the car, come back through the storm drains and try to help with the perimeter. Got it?”
The unanimous voice of the forty-odd agents rumbled, “Yes, Mrs. Aspen.” 
“One more thing. No killing. At all costs, we are not trying to get ourselves arrested; even if it is self defense, we don’t want to take chances. Please try to disable your opponents, and remember that the majority of them are only working because they are scared and they have to. Some of them are extremely young as well. I’m not sure how young, as Odin kept me in the dark as well, but I am suspecting the youngest came straight from the camps.”
Her words hung heavy over their heads. They resonated confusion and hurt. Even she, wife to this dictator, had no idea what was really going on. 
“Right, let’s keep going.” Aspen pulled her legs from between the rungs and swung from the ladder, catching herself with Adonis’ and Sam’s extended hands. They jogged to the front of the group and kept leading.

	Night was slowly blending with the day, stealing the meager warmth the sun provided. The sky burnished poppy-orange, melding with rosy hues at the western horizon, melting into indigo in the east, dotted with amethyst clouds. Sam, Adonis and Aspen stood at the edge of a cliff, partially concealed behind a towering pine, watching the sun fall away. The last of the agents hauled themselves out of the drain, leaving the gaping entrance open but hiding it with bits of branches. They assembled behind the trio, giving them an appropriate space. They assumed Adonis and Sam and Aspen were making final preparations and saying difficult goodbyes, and wanted to allow them proper respect and time for their plans.
	“That cloud looks like a butt,” Aspen said, pointing it out with her finger.
	Adonis and Sam giggled quietly. “That one looks really ugly,” Sam said. He blinked and shaded his eyes with one hand, then dramatically dropped his hand and shook his head. “Now that I look closer, I realise it just looks like Adonis. My bad.” 
Aspen cackled as Adonis punched Sam. Aspen paused, then asked, “I’ll see you guys on the other side?”
“You better believe it. And if I die, my soul will come back to haunt you,” Adonis said.
“Ha ha, very funny.” She turned around and pulled them into a hug. “See you later.”
“No goodbye?” Sam asked as she started walking down the hill. 
She paused and responded, “No. I never say goodbyes. They seem too permanent, too lasting.”
“See you later, Aspen,” Sam said. Adonis waved. They watched her climb a few feet down the hill. Then they turned the other way and saw the whole camp laid out before them: a teeming collection of kids thrown in a landscape of tents, snow and small fires. Sam cracked his neck. “Let’s go, Adonis.”
