# Shattered Pottery

Odin sprawled in his office chair, the too-harsh overhead lights switched off so he wouldn’t get a headache. The heavy drapes were drawn mostly closed, blocking out the world. His left elbow was propped on the armrest, his forefinger and thumb gently holding his chin as he stared blankly at the thick throw carpet spread beneath his heavily-hewed desk. His stomach clenched and growled, protesting his choice of fasting. He didn’t care enough to call a maid. His right arm held no weight of his body as it hung loosely over its own armrest, the sculpted flute of a mostly-empty wine bottle clenched tightly in his fist. He shifted his hazy eyes to stare through the greenish glass at the dark liquid inside, watching the bit of foam on its maroon surface quiver with every beat of his heart.  
Aspen’s abandonment had seismically shifted Odin’s planet. No, not just shifted; his world was undone. Ruined. He had lost his perfect little home-planet, been shot off into space, and now he drifted around in the nothingness alone. So, so, terribly alone. She was everything to me, and somehow I’m nothing to her. I have to be. I can’t mean anything to her at all, and I have to believe that because if I don’t I’ll be weak. Too attached. Clingy. Stupidly dreaming, stupidly attached, stupid, stupid, stupidly in love. He hissed at himself. How does she feel nothing about me when she is everything to me? I want her to suffer just as much as I do. I want her to know and feel the pain she puts me through. It’s not fair! Why am I like this! Why do I love her so much when she couldn’t give a damn about me! Why can’t she get out of my head! I need to move on! Now! Now, now, now, now now now now nownownownownow NOW! I AM NOTHING TO HER AND I NEVER WILL BE! SHE CANNOT BE ANYTHING TO ME!
Why did he have to hurt so bad. How could he be so stupid. He was used. By her, by Aspen-Fauna, the girl he’d loved so much he gave her his last name, his family name because she felt like she had never had one. But he was used and discarded, like he always is. Used until he was no longer useful, then thrown out because he was never good enough for anyone. Why did he love so much and have so many expectations and hopes when the sensical part of him knew no one would ever meet them. Why did he love so deeply? Why did he so stupidly set himself up to be hurt?
Yet he already knew the answer. And he hated that he would do it again. And again, and again, again, so stupidly setting himself up to be hurt by everyone. Because he so stupidly loved her. Because he is so, so, so, so stupidly in love with her. 
I hate her, everything about her. Get her out of your mind. She can no longer be your crutch. You have become far too weak. 
Weak, just like your father and mother and brothers knew you were. They’ll always outmatch you no matter how fast you run. They’ll always be better and more lovable and happier just like Adonis is.
Odin suddenly slammed the bottle on his desk. He released its neck and threw his head back. Groaning, he pushed up his glasses, rubbed his eyes, then slowly dragged his palms down his cheeks. He wouldn’t admit it to himself, but Odin knew that he was jealous of Adonis. When he stalked the agents before wiggling into their mission, scrolling through their social medias, reading resumes, digging deeper than what was truly necessary, Odin felt a seed settle in him. As small as a mustard seed, he barely knew it was there as he saw picture after picture of people crowding around Adonis to fit in the shot, picture after picture of his charming, alluring smile, picture after picture of Sam and he laughing at some unknown joke, of his neatly made baked goods, of his little sketches, of his outlandish yet somehow acceptable outfits. Adonis was just everything that Odin wanted to be: handsome, strong, pretty, funny, amicable, appealing, popular, perfect. That mustard seed had stayed dormant until Odin had captured Adonis, he had bested Mr. Perfect himself; Odin had won the war against Adonis, a fight Adonis surely had no idea was going on. 
But now Adonis was gone, and Aspen with him. Odin thought he had won, but he learned he had merely won a battle, not the war. And now, even though he refused to admit it, the mustard seed that burrowed in him so many months ago and stayed dormant, now exploded in Odin, growing to colossal proportions alarmingly fast. 
Adonis and Sam are still out there. I have to get them before they make a bigger mess. Everything was ruined the second they showed up here. 
He growled and stomped to his office doors, preempting his eyes from the pain he knew would blind him the moment he flung them open. I should’ve killed them a long time ago.
Odin whipped open the doors. He grimaced as white sunlight poured through the glass walls and ceiling of the atrium. Her atrium. The guards on either side of his door nodded to him, prepared to follow Odin wherever he was headed, but he waved them off. His head swam momentarily, and his first step was staggered, but he leaned against a pillar, caught his breath, and steeled his composure. He walked the rest of the way, down the spiral stairs to the first floor, across the hall and into the mudroom to grab a coat, without a stumble. He planned to walk the perimeter of the manor, then extend his solo search into the valley. He was determined to find Aspen, practically a miracle as not one of the guards in his force had seen her since the night she disappeared with them, but Odin knew how her mind worked best. He’d be able to find her easily.
	He walked into the atrium as he pulled on his puffy winter jacket. The air in the first floor of the atrium was heady, heavily perfumed by a mixture of flower’s aromas. He sneezed at the thick air and caught sight of his socks. Not his socks; her socks. Everything that’s mine is hers, right? Everything that’s hers is mine, because we’re married. He jerked his head up to flick the hair out of his eyes and crossed the cold tile to the shoe rack, willfully blocking out the towering ferns and flowers and palms that crowded behind him. Without Aspen’s careful regimen, some of the leaves had gone droopy and crisped on their edges. He managed to slip on his boots and get to the front door and reach out, but its frosty windows were intimidating and he hesitated. His hand hovered centimeters away from the pair of gilded handles. 
He couldn’t block out everything. Splish, gurgle, splash. He yanked his hood over his head and clapped his hands over his ears as the once-calming ambiance of rippling coming from Aspen’s fish pond turned into grating, assaulting noise. 
“Shut up! Go away!” he exploded, screaming at the unresponsive wall. Odin had felt numb for days, unmovable, a lump of nothing in a world too full of everything. Everything crumbled at once, his chest ripped open by hot coals. And all it had taken to rattle him was water gently dripping in a far-away corner. He was yelling at nothing, he knew he was crazy, but still he screamed in a broken voice, “LEAVE ME ALONE!”
The ground, unbearably cold seconds ago, seemed so welcoming. He dropped to it and screeched again, screaming a wordless howl, clawing at his head and ears. He shoved the hood off and grappled with himself, tearing at his body, gesticulating ferally. Nothing was satisfying, everything was frustrating. He glared at the cracks in the tiles, but found his eyes drawn to the knitted gloves on his hands. 
The gloves she made for me. I can't believe she left me. I love her. I love Aspen. 
I've loved her since the day I met her. 
He looked at the gloves for a long time, feeling terribly sick. They were gloves she wove for him years ago when he complained his fingers were cold.
He grasped the rim of a plant pot near him and threw it across the foyer. Finally, a noise he had made, something that he could create and break and control, that was satisfying to the beast clawing his gut. The pottery shattered spectacularly and the crash sent splinters of the glazed clay flying. The soft, moist soil spilled on the ground, and the plant was uprooted and crushed. The crash was so loud that it seemed to reverberate through the entire house, and he smiled when he heard it echo back from somewhere in the kitchen.
He stood again and tugged his gloves on tighter, flexing his hands to adjust them perfectly on his fingers. After looking at them for another moment, a thought dangerously came to him.
This is all Adonis’ fault. Her disappearance is his fault. His charming smile, his messy hair that conveniently needed a hair tie, a tie she must have given to him when he manipulated her behind my back. She must love me. She has to. 
He opened the doors and breathed in the stabbing cold air.
She was forced into this.
He walked down the widely curving front stairs and put his hands on his hips and glared upon the valley. 
I'm coming for you, Aspen. I'm coming for you.
He left the broken pot behind. Someone else can clean it up. He had to get Aspen. He ignored the small bouts of nausea as they came and went as he picked apart Briarcliff. He meandered the streets alone, giving up his firm reserve to search ceaselessly for her after only a couple hours. Night came too soon, he shivered, he was suffocated under the weighted blanket of the sky. Maybe if he had resisted his urges to drink, maybe if he had brought his guards with him, maybe if he had eaten a full meal sometime in the past week, then maybe he would have noticed the slight weirdness going on in Briarcliff. Downtrodden, defeated, outsmarted; Jefferson wrapped his arms tightly around his chest, fighting both his breaths in and out, absorbed in his own universe of hurt, he failed to notice the vans, all eerily identical to the one he had ridden in with Sam and Adonis shortly ago, dotted throughout the town. 

The pot Odin had destroyed and left behind had geraniums hand-planted in it by Aspen. As the plant’s roots were left exposed to the air, the small flowers withered, curling drily at their edges and turning from a cheery magenta-pink to brown. 

***
	
Aspen trotted down the hill, tucking her hands into her armpits to try to warm them. She needed her fingers to be nimble. She followed almost the same route she had before, when she first found her garden razed, except she wound around the back of the house. She didn’t want to use the main path in case Odin had started slapping guards on the paths around the house. 
Briarcliff Valley was far north, in Montana, tucked away from Helena and the other cities. Therefore, since it was winter, the sun would fall faster each day until the twenty-first. It was only four in the afternoon, but already the sun was retiring. At least the darkness will help cover me, Aspen thought. The help is welcome, but I have to admit that I’ve gotten rather good at sneaking around my own house. 
She dodged underneath the trees’ boughs and between their trunks until she reached the bottom of the hill and the house came into view, just a hundred feet away. She was at the back of it again, and looking from its left to its right, she could see the popularly-used laundry room, the curve of the tower library, the glass cap of the great foyer, and finally the kitchen after a long blank space. The laundry room before had only been protected with the single security camera; now Aspen picked out two others subtly hidden near the door. The only other possible way she could think to get in was through the kitchen’s windows, but they were seven feet off the ground, and if she managed to get that high, she wasn’t sure if she would be able to fit through the gap that was only one foot tall and two feet wide. 
But what other choice do I have? There’s no way I can go through the laundry room anymore, I think trying to enter through the front is too risky… She thought about it for as long as she dared, but couldn’t think of any other way. I guess I’m small, I should be fine. Wait, do these even open? Am I going to have to smash it? She shook off her worries, bounced lightly on her toes, and wiggled her fingertips. 
Relax. It’s all over soon.
Breathe in.
I just need to get to Jeff’s office and talk to him. I just need to stall. 
Exhale slowly. 
Now!
She leaped from her spot in the trees and sprinted across the land, feeling the little crunches of an ice layer snapping. Up, how do I get up? She only needed a foot, maybe foot-and-a-half boost; she could jump up the rest of the way. She slid her sprint to a stop and lunged as she saw the tacky fake rock the gardeners used to cover up the sprinkler timers. It was hollow, light, and hopefully durable enough to hold her weight for a mere moment. Crouching low to balance, she hoisted the cover in her right hand and chucked it in front of her, letting it freely slide across the pavement and then bonk into the wall, skittering slightly. That’s fine. Close enough. She scrutinized the windows again, surmised she was going to have to smash the glass to get in, and plucked a big, real, rock from right beside the sprinkler timers. She sidled a bit closer to the windows, picked one, and threw the rock as hard as she could into it. It immediately shattered and Aspen winced at the loud crashing and cringed at every crystally tinkle the pieces made as they littered the pavement and, Aspen assumed, the entire kitchen. The rock landed inside densely, coming to rest on the lip of a counter after slamming into a few pots and sliding around. 
The glass broke peculiarly. Curious, Aspen bent to pick up a piece and had to resist cheering when she saw its shape; the piece she pinched between her fingers, along with all the other pieces, were in various-shaped chunks, but all were smooth on the faces and had rounded corners. The window is tempered glass. This is going to be so much easier. The chances of slicing her back and thighs open on tempered glass was much lower than the typical kind of heat glass she had expected.
She brushed glass pieces out of her way with her gloved palm and froze as she heard an exclamation from inside. She fell back onto her palms and craned her neck, attempting to peer through the windows, and scrambled to lie flat against the wall as someone’s curly afro peeked out. 
“Is anyone there? C-can I help you?” the woman inside asked uncertainly, not sure how to respond to a shattered window. She clearly had not spotted Aspen yet. 
No! I thought everyone was supposed to be looking for me outside of the house! Aspen grumped, angry that she had been found out again while trying to sneak into her own house. Sadly she thought, I always get caught right before I actually make it in.
Praying that whoever was at the window did not exude the same sickening, slimy confidence that Carter had in the storm drains, Aspen asked if she had any genuine allegiance to Odin. The woman at the window started, still not seeing Aspen pressed against the wall, then quietly said no, she did not like Odin one bit.
“Then I am your friend, here to help you.” Aspen rolled to standing and stepped back slightly from the wall to look at the window woman. “Do you work at the house? I don’t think I’ve seen you before.” 
The woman nodded, her curls bouncing lightly. “Yes. I’m Odin’s secretary. I don’t know many people here because I’m pretty new and also because Odin doesn’t leave me a lot of free time. I’m Cassie.”
Cassie waited a polite beat for Aspen’s name, and Aspen was a bit shocked that Cassie didn’t recognize her. I guess Odin really didn’t want me to meet her. Maybe she has some information he doesn’t want me to hear. When Aspen didn’t give her name, Cassie just moved on.
“Would you like some help?” Cassie asked, reaching out her left arm and leaning over the edge. She pulled off her glasses with her other hand so they wouldn’t fall. Their large square rims were purple, her favorite color. “I’m guessing you’re trying to break in?”
Aspen grinned sheepishly, pushed the fake rock into place, and accepted Cassie’s arm, hauling herself through the small window. She asked, “Do you know if Odin is here?”
Cassie shook her head. “No, he’s gone. He just left a moment ago to look for his wife.”
“Is anyone here besides you?” Aspen asked as she straightened from the floor.
“Not that I know of,” Cassie said, walking ahead of Aspen and pushing the kitchen door open for her. “Where do you want to go?”
“I need to go to Je-” Aspen cleared her throat. “Odin’s office.”
They walked quickly through the hall, an awkward silence resting between them. Trying to start a conversation, Cassie asked, “So how are you going to take down Mr. Odin?”
Aspen, who still hadn’t provided her name or any personal information, started explaining the outline of the plan to Cassie. Cassie didn’t believe her fantastical plan at first, but when Aspen told her about breaking out the children, Cassie became ecstatic. She thought happily, Finally, someone is taking responsibility for them.
As Aspen and Cassie walked through the foyer, Aspen cut herself off as she saw the destroyed plant pot. “Ah! What happened here?” she asked, dropping next to it and scooping up some of the bigger pieces. 
“Right before he left, he threw the pot across the room. I think he was throwing it at someone because he was screaming before that, but I’m not sure. I was heading to the kitchen to have dinner, but then you smashed the window,” Cassie said sorrowfully. “Lucky your rock didn’t hit me, huh?”
Aspen didn’t respond for a moment. She was kneeling on the ground, soiling the knees of her pants with the dirt. Her back curved and she was weary, holding what felt like the weight of the universe on her back. Defeated. I feel defeated. She struggled to talk past the lump in her throat. “Yeah… I’m sorry. I didn’t know you were there.”
Cassie hesitantly asked, “Is there something on the pot? Or can we keep moving?”
“I painted this as a part of a set for him. For our anniversary."

"You're his wife." Cassie didn't really ask. "Why didn't you tell me?"
"I have known him for years. I have been married to him for years. Somehow, he’s a stranger to me." Aspen spoke haltingly, and still hadn't moved from the ground. Out of all the things he had done to her, this smashed pot hurt the most. She had painted swirling koi, her favorite animal, playing with white cats, his favorite animal. She had painted three pots in total, each taking a month to design, sketch, paint and glaze. A shard with a cat's green eye looked up at her, seeming to laugh at her misery. Another piece with a spotted koi swam towards her. "I didn't tell you because I thought he might do something to you if you knew but didn't tell him. I don't know. I’m sorry.”
Cassie was silent for a moment. She yelled in disbelief, “What do you mean you don’t know what he would do? He would do exactly what he always does!” Aspen was startled by the rage in her voice. Aspen looked over her shoulder, but fell back onto her hands as Cassie stepped closer. Her palms were sliced by the broken pottery. “Pull your head out of the clouds! Join us back on earth! You probably think life is peachy, and how tragic it is that the worst thing Odin could do is smash a pot! Where is your awareness?” Cassie was easily 5’8” and had lean muscles all over her body. She bent over and effortlessly scooped Aspen off the ground by the collar of her jacket. Aspen panicked for a second, but stilled when she saw that Cassie’s eyes were burning with tears, not hatred.
“Cassie, I have no idea what Odin does. He shielded me on purpose, but believe me, I am not naive,” Aspen said slowly. “I was abused by him. I’ve seen his sick collection of children. I saw Sam walking through the halls on Thanksgiving, covered in blood and seizing. I don’t know how it happened. You have to believe me, I am here to help you! I am not your enemy, but right now, we are wasting precious time, time I need.” Cassie wasn’t moved by her plea for time. Sighing, Aspen asked, “It seems like this can’t wait till later; what did he do to you?”
“All I did was barge into his office inopportunely. I served him every day, catered to his every need, and one day I barged into his room shortly after he told me he would not tolerate interruptions.” Cassie’s arms shook. She still had Aspen’s collar curled in her fist. “He captured my mother, father and brother who all lived in the valley. He wanted to test a new concoction he had just invented, with deadly amounts of medicinal and recreational drugs, causing hallucinations, internal bleeding, and countless physical ailments. My interruption was convenient timing, and it gave him three good test subjects. 
“What’s your name?” Cassie asked Aspen. 
“Aspen,” she answered quietly.
“Aspen, there are people dying in your basement. I had to watch my mom, dad and brother die because of your husband.” Cassie was glaring at Aspen, but they both knew the anger wasn’t for Aspen. Unfortunately, Aspen was the only outlet Cassie had to let out her fury. She finally lowered Aspen to the floor and waited for her to respond. 
Aspen stared at the floor. Cassie couldn’t see her face, but after a while, her shoulders started shaking and she covered her face with her hands, smearing blood all over her skin, tangling her fingers in her hair roots. 
Cassie felt guilt wrench her stomach. She really didn’t know.
Aspen screamed, “I’m sorry! I had no idea, I’m so sorry!” Tears poured through the slits in between her fingers. “God, I’m so embarrassed! You’re right! I had no idea! I had no idea I married the-the damned devil! Agh!” She slid to the ground and banged her right fist against the tile, bruising the edge of her hand. Her fist left a partial blood print on the marble. Her hair, already soiled from the gutter water, was now matted with clots of her own blood. Maroon spots expanded on her pants, growing with each drip, mixing with drops of her tears. She tore her hands away from her deranged face and looked up at Cassie. “I’M SORRY I MARRIED A MURDERER!”
Aspen’s chest heaved and Cassie’s cheeks burned. Cassie didn’t have a response. Aspen stood again and poked a finger into Cassie’s chest, forcing her to walk backwards. “And don’t you dare tell me none of this is my fault! I needed to hear that months ago, when I had no support from anyone. I helped everyone I can, but I’m no god! I’m fallible, I’m not perfect, but I have nothing else to give, and for the longest damn time, I had no one else to give me anything. I am tired Cassie, I’m tired of being treated like a child by every single person, yet I’m expected to comfort everyone like their damned therapist when they aren’t okay! No one gave a horses’ ass about me in the years I was forced to live here, nor in the years before! So just-” Aspen dropped her hands and screamed with her mouth closed, frustrated at everything. Blink. A mask of practiced calm snapped over her features. Her voice fractured but she continued: “I need to go to Odin’s office. Follow me if you want. I’m sorry for what happened to your family, as well as countless others, but I’m trying to fix it. Sorry.” She whipped around and stomped to the staircase, kicking the chunks of pottery out of her way. 
Aspen had climbed up the levels and was walking on the balcony when Cassie called, “Wait. Aspen. I want to help.” Cassie had been tailing behind her and was at the stairwell, waiting for Aspen to signal for her to proceed. Aspen turned around and jerked her head, allowing Cassie to walk with her. “What do you need me to do?”
Aspen pushed away the sickening sensation that crawled on her skin when she looked at Cassie, composing herself. Despite what had just happened, she needed to keep moving forward with the plan, and if Cassie was offering help, she was going to take it. “I want to confront Odin in a place where I have the advantage. Basically, I just want to talk with him; I’m pretty sure he wants me back, and that I’m probably the only person he’ll listen to. So, I’m going to his office because it’s tucked in the back, and I know if I need to get out, I can jump from his window to the ledge below. Later, there are going to be more agents coming; two of them, the leaders, you will tell to come here. For now, I want you to clean up the pottery downstairs and if you see Odin, tell him I’m waiting in the office.”
“How will I know which two are the leaders?” Cassie asked. They had reached the imposing double doors of Odin’s office. 
A slight smile spread on Aspen’s face. “Don’t worry. They’ll stand out.” After a pause she said, “After you find them, I would suggest you run and hide in case this doesn’t work.”
Aspen started to close the door as she walked in, but Cassie grabbed the edge of it. “Can I open up the basement instead?”
Aspen stopped and looked Cassie up-and-down. “You’re digging your own grave.”
“I think you’re already standing thigh-deep in yours,” Cassie responded.
“I think I like you,” Aspen grinned. “I hope I see you again after.”
“And you as well,” Cassie said. She reached out her hand to Aspen and they shook. Cassie pulled the door closed the rest of the way.
Aspen fisted her hands and placed them on her hips, breathed the deep, woody air into her lungs. She doubled over and coughed violently as the pungent scent of wine cut her throat. 
Disgusting. She walked to Odin’s desk and plucked the opened, half-drunk bottle of white wine by its neck and threw it into the fireplace. The weak coals leftover from an old fire crackled feebly, sputtering weak protests at the glass bottle as it covered their flames. She threw another log from the basket on the fire and relit it from Odin’s tinderbox. She stood frozen at the fire’s edge, her vision glazing over as the golden flames licked and played in the air. Now I wait.
She drifted around the room for a bit, scuffing the dark stains on the floor that she knew was her blood with the toe of her shoe, leisurely dragging her finger across the spines of books on the shelf. 
Her hands were still bleeding from Cassie forcing her back into the pottery, so Aspen grabbed a pair of scissors from Odin’s desk and cut two pieces of the curtains off. The plastic handles slipped in her hands, slick from the blood, but she just gripped them harder. The pressure pushed a few smaller shards deeper into her tender skin and made her hands throb. I’ll have to get the pieces out later. Right now, not fainting from blood loss is more important, she thought as she used her teeth to cinch the knots in the curtain tightly. 
She plopped back in his chair and tossed the scissors back on the table, staring through the fireplace bricks. She closed her eyes and her head fell back as she released a pent-up breath. She had no idea how long she was going to have to wait, but the tension was killing her, and night had fallen. While the mission had felt dangerous before (despite the sun’s lightness egging them onwards), it now felt eerie, mysterious in it's silky nighttime shroud. 
With her eyes still closed, she splayed over the chair, firmly planting both her forearms on the armrests. Cassie must have exaggerated right? Despite everything, some part of her couldn't quite accept that part of Jeff. I know he hid things, but I've been to the basement many times in the past year. 
One basement. Odin manor had two; how could she have forgotten? But that doesn't make sense. Sam and Adonis came from a basement, but they told me it was unfinished. The basement I’m thinking of is finished with a movie theatre. Odin didn't throw them in this ‘other’ basement, right? Aspen puzzled over it until her head started to hurt. I know every staff member, I think, but I’ve never even seen Cassie...she has something I’m not supposed to know.
Aspen pushed out of the chair and tiptoed to the doors. Even though she knew no one was home, she still felt paranoid enough to sneak around. After listening through the crack between the doors, she eased one open and looked around the hall. To the right, there was a desk and when she got closer, she saw a small sign with Cassie’s name on it. She walked around the desk and shuffled through the papers on the top. Her fingers were stiff from the curtain bandages, and she had tied them so tightly her fingertips did not have enough blood circulation; they were a pale-yellowish color. She wasn’t sure what she was looking for in the papers, but she was hoping to find something, anything that could explain some part of her life for the past three years. 
The overhead lights were off, so she put the small flashlight back in her mouth and started digging through the drawers. Slowly, as she mindlessly sifted through papers and knicknacks, her chest got heavier and it was hard to breathe as memories trickled in. She remembered moving to Odin manor, how she and Jeff redid the interior to fit both their tastes, how Jeff and she laughed and joked so often in the first year. She remembered the days she and Jeff had where they walked the forest together, pausing often so she could draw or point something out. She remembered the time Jeff went shopping with her in the valley and helped her pick out a dress, even modeling the dress himself to ‘see if it looked good on him.’
She was so happy it hurt. 
What went wrong? How could I allow this to happen?
These two questions had been churning in her for months now, at first just about her and how she managed to get locked inside her own home, but then about Sam and Adonis and the workers and the children and the plots.
When did everything change?
Jeff had always felt like an outcast in school, being a transfer kid from a new country forced to live with his extended family. He had felt misunderstood, sure, but he was never violent. Aspen dug through more papers, now barely scanning the titles, feeling like her chest pressed deeper inward the longer she sat like this with her turbulent mind. 
When was the first time he slapped me? That question shocked her, releasing the pressure in her chest. She stopped searching momentarily, but went back to her mindless work. 
Forcing herself to relive these horrible memories hurt just as much as the happy ones had, but she knew that she needed to figure this out for herself. She had to reassure herself that there was nothing she could’ve done to stop all of this. She had to reassure herself that she definitely, undoubtedly, had played no part in his violence at all. 
She tried to remember when the first time was that she felt the sting of Jeff's hand on her face, but one memory demanded precedence. 
Hot, yet breezy day. March 28, 2017. Aspen was digging in the forest, searching for native flora and sketching them. She was outlining the yellow petals of a Salsify when she heard rustling through the underbrush nearby. She feared a bear was lumbering about, but the afternoon was so calm, with golden-syrup beams pouring through the trees’ branches and birds chirping, that she presumed it was probably a bunny. She started, dropping her pencil in the loam, when Jeff's shadow covered her as he walked around a tree. He was clearly upset, so she asked him what was wrong.
“My grandpa just died, and instead of having a funeral, my family is celebrating my brother being accepted onto the olympic team,” he had said hollowly. Jeff had inherited this manor early, before his grandfather died, so that his grandfather could move back to Europe and be taken care of by Jeff’s parents. Jeff had inherited the manor instead of his other two, older, more accomplished, brothers, so his grandpa had clearly favored Jeff over them for whatever reason.
“Oh, oh no, Jeff, I’m so sorry,” Aspen had said, standing and wrapping her arms around his middle. 
In a shaky voice he had lamented, “They couldn’t care less about him. My parents only care about my stupid brothers. Apparently, he passed almost a week ago, and they forgot to tell me until now. Why can’t they just care about me? It’s like I don’t exist. I am a clump of mold that got attached to their rotting trunk and I can’t get off.” Aspen felt his eyes watering and spilling onto her.
“No, Jeff. Do not say that, ever. You are special and unique. Everyone has special talents, and sometimes families aren't present to support them. It's okay to be separated from your family, it's okay if you have talents they don't appreciate, because the only person that needs to realize how unique and amazing you are is you. You can trust I'll always be at your side for you because I need you, I love you.”
Aspen was jerked back to reality when she stumbled into the last drawer, which refused to open. It didn't appear to have a lock, but when she tugged on it, it stubbornly refused to move. She slid from the desk chair to the floor and dug her fingers underneath the lip of the drawer, feeling around for something on the rails that might have stopped the drawer. Feeling nothing she took her hand back, dejected.
The important papers I want are definitely inside here. She glared at the metal and reached under again, feeling for a latch or button. Frustrated, she simply slapped her hand against the bottom and jumped in surprise when something heavy fell into her palm. She dragged it out and found she was holding the entire drawer, minus the front of it, in her hand. Clever. The front of it was fake.
She placed the drawer-box next to her and momentarily took the flashlight out of her mouth. Her jaw was getting sore from holding it so long, so she transferred it to one hand and started digging through the random papers inside the drawer, hoping that something exciting would surface; if nothing did, she would probably have to concede and just continue waiting for Odin in the office. 
She reached the bottom of the stack and still nothing had caught her eyes. It was all just taxes, or bills, or information sheets on the townspeople or workers. She left the papers on the floor and flipped the box over, looking for another secret compartment. When she flipped it, a very thin folder slid out from a slit in the side. She held the flashlight up to it and saw that it said:

RESTRICTED


DO NOT READ. DO NOT REMOVE FROM DRAWER.
DO NOT CREATE COPIES UNLESS INSTRUCTED.

	Aspen sat in awe for a moment. I’m definitely not supposed to see this! she thought excitedly, and tore open the cover. There were many sheets of paper with long blocks of text in small font; she closed the cover and returned to Odin’s office. She left Cassie’s desk messy because she just didn’t care if Odin found it anymore.
	The moonlight glowed through the windows and she angled herself so she could read without the flashlight. The more she read, she felt her stomach drop. It hit her just how much Odin had lied and deceived her, even when she had concluded he hadn’t been that bad yet. 
	The folder was like a deconstructed journal, with receipts and thoughts and random scribbling. The pages weren’t in the proper order as she read the entries and she skipped from month to month. This is a lunatic’s compendium of random ideas. I’ve been married to a maniac, Aspen thought feverishly before diving in with a head-first attitude. 
	
	January 1, 2018: $3,000 donated BP. 
February 6, 2019: Supplier delivered 3.5 kg acetaminophen, 1.0 kg melatonin. Acetaminophen refined, inputted. Hives, itching, swelling, blistering/sores. No effects other than drowsiness in melatonin.
	May 13, 2018: $267.43 transacted Aspen-Fauna Odin. Birdfeeders, swimsuits, PC upgrades purchased. -A-F
	September 7, 2019: $1,200 paid to Officer [redacted]. Officer wishes to stay anonymous. -Cassie
	April 2, 2019: Aged out: Alfonza Y-U. Unkleas, Bianca V. Sanchez, Ella A. Brown, Elaine L. Johnson, Finlay T. Banq, Genevieve T. Fil-Penn, Greyson F. Flamesen, Josh B. Whitlan, Lacy A. Grasiela, Lindsey F. Flannegan, Octavian S. Yulson, Taylor B. Camal, Tyler M. Patch. 
Notes/Comments: Unkleas, Brown, Banq, Flamesen, Whitlan, Camal, should be carefully monitored through initiation. All have displayed signs of resistance before. -Captain Nathan H. Lee-Chen.
	December 23, 2017: 36 security cameras added to house. Aspen knows of 30.
	May 6, 2018: $15,000 transacted BP.
	October 31, 2019: Six caskets of No.1 1900’s Red ordered and delivered to wine cellar. -Cassie
	October 31, 2019 (cont.): Rumor of SOS signal sent to Helena. Unsure whether tip will be taken seriously; investigation is due. Recommended to Odin to delve deeper into situation. Who sent, where it was received, unclear. -Cassie
	December 30, 2018: $5,000 transacted Dr. [redacted]. Dr. wishes to stay anonymous.
April 14, 2017: We are thinking of possibly redesigning the kitchen. Aspen wants a copper theme, as well as an abundance of plants. “Hanging plants! They have to be hanging plants!” (she interjected). “I will do my best to fill that kitchen with so many lively plants you’ll drown in their leaves!” I answer. I guess I will be finding the nearest plant nursery now. 
January 2, 2019: ~150 cameras added to Briarcliff.  ~60 indoor.
July 25, 2019: Resupplied acetaminophen. Ketamine discussed (much emphasis that it will be used strictly as anesthetic). Idea is not favored, LSD and other hallucinogens are discussed as alternatives. 
November 23, 2018: The trials have been rather successful. More melatonin will be incorporated. Preferred length of time for subjects to be rendered unconscious is between fifteen and thirty hours. Hallucinations are improving. More testing to come. 
December 1, 2018: $3,000 donated HPF. 
February 3, 2019: Promoted Boyer F. Johnson, Frederik G. Tremblay, Lucia S. Sanchez. 
March 10, 2019: New “PlayStation” purchased. Lady has also purchased “The Occupation,” “The Walking Dead,” “Life is Strange 2,” and pre-purchased “Mortal Kombat 11.” -Elizabeth
April 20, 2018: $6,000 transacted BP. $1,000 donated to Helena General Hospital. 
July 21, 2018: First group of house staff briefed and added. Aspen introduced. Lady was not made aware as to where they came from. -Jordan

She found more and more receipts piled on top of each other, but they all were for the same things: innumerable child-sized scarves and socks, painkillers, antidepressants, alcohol, cameras. Notes, staff lists, thumbnail sketches of--what? Aspen found that ‘Jordan’ and ‘Cassie’ and ‘Elizabeth’ were just another two names lost in the long list of people Aspen had never heard of but supposedly worked in and around her house. 
And the strangest of all: where on earth were these enormous sums of money going? As far as Aspen knew, Odin had not binge-bought any items close to those numerical values. Could he have paid people off? Aspen hissed out a breath. No, no, that’s stupid. I think. But the abbreviation… 
Two pieces of paper were left. Aspen’s heart beat as she knew time had passed, how much she wasn’t sure, but enough for it to be dangerous to keep reading. Odin could burst through his office doors at any moment now. She sucked in a deep, rattling breath and shifted her shoulders to let more light bleed across the papers; these text blocks were longer than the others.

July 9, 2018: Aspen and I took a walk through the forest today, and we came across a beautiful clearing in a small valley. It really was nothing more than a small dip in the land with waist-high swaying grass, but she immediately envisioned a garden and helped me imagine her vision for it along with her. She and I are now planning to plant rows of non-invasive native flowers, and she wants to take a stone carving class so she can learn how to carve a dragon centerpiece. I am excited to help her on her project :)
	
	May 14, 2019: Order pushed to all house members: Lady of the House, Miss Aspen-Fauna, is to be left out of all meetings with staff. Lady is to be protected at all costs, all her wants and needs are expected to be met instantly. Do not disturb the Lady as she has dealt with much; you are not to include her in any meetings nor give her any information.

She thought she had reached the end of the stack, which she was grateful for. These last two entries about her hurt. A lot. 
But the very last entry, hastily scribbled on the inside of the paper folder, that she spotted only after she squinted right at the yellowed folder, broke her.

March 27, 2018: Grandfather has passed. My family does not care, but Aspen has been amazing. She promised to always be by my side, and she made me my favorite spaghetti dinner. I've realized that my family always hurts me, even if it is by accident, so I've decided I'm going to let them go. I don't resent them; no, I forgive them, but I also am learning how to protect myself. How to put up walls, one would say. Protection. 
It's also made me realize how I want to protect Aspen, forever. The sour side of me is happy that she doesn't have a family. I'm sure that if she did know her biological family, they would be lovely people, yet any parents can inflict damage on their children. Perhaps it's just better for a child to have no parents at all. They still need rules and values to shape them, but they certainly don't need to worry about being yelled at, or being a failure, or even worrying about whether their parents are going to divorce, whether their parents even actually love each other. 
I've fought with that idea forever. My parents, I thought they loved each other, but I had to let go of that after seeing so much drunken yelling. I don't think that's what love looks like, and I'm sad that's all I've learned from them. Why do I even bother hoping they're in love? It won't affect me either way, and I'm just putting faith in a crumbling bridge. 
The most insulting thing is when they would say something rude to me and apologize by just saying they love me. Or they would say "we're human, we make mistakes." Am I a mistake, then? Maybe I'm humanity's mistake.
This is exhausting for me to think and write about. Families are exhausting. Maybe I just need to go to bed and sleep for a long, long time. An eternity; long enough to forget who my parents are and what they've done to me.

Aspen's hands shook. This explained everything, even more than she had even come looking for. It was all right here, all along. 
His demented explaination for the children.
His secrets.
Him.
Her.
Him and her.
She slapped the papers back into a stack and hurled it at the far wall. Small slips fluttered off the stack as it flew, but the main clump hit the wall’s paint with a smack. Her hands curled into her hair and she hunched her torso over her legs. Pressure built in her throat, burning, her head, throbbing, behind her eyes, dripping, everything was blurry and the silence pressed in so loudly and she felt like clawing her face off-
Cold air suddenly stung her, shakily filling her lungs like the crack of a whip on her back. 
Carefully pulling her hands away from her head, she opened and closed her fists, flexed her palms.
She looked around the room, his room, again. There was a chip in her eyes that wasn't there before. A chip with a razor-sharp paper-thin edge, like the shards of her broken pottery in the foyer. This chip could slice through the physical flesh of men and the figurative thoughts in her mind alike, of which it did; she felt her hurt feelings rip then drain away as if they had never existed at all. They all were pushed to the recesses of her mind: betrayal, anger, sadness, confusion, all compacted into a burning coal that simmered underneath a stiff layer of nothing. She felt nothing. Nothing at all.
She stood from the overstuffed chair, the worn leather and downy feathers springing back to their fullness. Aspen reached her right arm high in the air, grabbed her elbow with her left hand, and leaned to the side, cracking her back. She twisted her neck around and rolled her shoulders, wishing she could roll back, roll away, Odin (or is he Jefferson?) from her mind. She stared hollowly through the far-away doors.
I love him. No, I loved him. But he still loves me. He thinks this is what love is like, she thought distantly. I think he knows this is bad. 
I hate this.
I hate that I still want to find the good in him. He doesn't deserve another chance. But this is all he knows! How was he supposed to learn basic morals when his parents had no desire to teach him?
Aspen looked away from the door, instead finding her eyes to be attracted to the sword on the wall. 
He isn't a good person. He isn’t a good person. He is demented and twisted and sick and needs hella therapy. He isn’t a good person. He isn’t a good person! He isn’t a good person!
Aspen walked around the desk, up to the fireplace, and wrapped her hand around the hilt, painfully squishing the bandages against her tender skin. The sword was heavy, jerking her hand to the ground when she fumbled it off its hooks. She righted herself and stalked back to Odin's chair, scarring a thin groove in the wooden floor by lazily dragging the sword tip across it. Crossing one leg over the other, she balanced the blade across her thighs and once again stared at the office’s doors, her stare so intensely lethal that the scars indented from long-ago fights seemed to shirk away from it.
