# Human Remains

She balanced on the crest of a roughly textured boulder, legs crossed, back to the camp and warmly flickering fire, back and shoulders bowed. Her hair, greying just slightly at the roots, was swept into a messy bun at the crown of her head; Trinity couldn’t see her face, but wished that she could so that she could read her emotions. 
	“Ariadne.” Trinity called her. Ariadne didn’t respond at all. Trinity looked around the small circle of her friends, the agents, laughing and chatting and throwing jokes of insults at each other and she wondered how none of them noticed Ariadne. Her gaze drifted back to Ariadne. Sure, she was naturally separated from them, a wraith perched on a cold grey rock, swathed in fog, an unknown in this group that all knew each other, but Ariadne’s family was a big part of why Trinity and her coworkers were all camped in this distant mountain.
	Maybe the agents simply chose to ignore her. 
Trinity looked at each of her coworkers again, her mind practically begging for one of them to make eye contact with her. To just acknowledge that she and Ariadne existed within this group, that Ariadne was not separate and that Trinity was not separate because she noticed Ariadne’s separation, but no one sensed Trinity’s eyes. Trinity jiggled her knee, her boot shifting the gravel beneath it, and her fingers twitched. The noise of her friends started to be stifling; her breaths weren’t satisfying her lungs because her chest was too heavy to rise, so she rose from the circle and crept over to Ariadne. 
	“Hey. How’re you doing?” Trinity asked, plopping down on the gravel next to Ariadne’s rock and gently leaning her head against its textured surface. Ariadne still did not respond, so Trinity looked across the water, sighed, palmed a smooth pebble and skipped it across the glassy surface with a flick of her wrist. Mist swirled off the water, the white coils slowly fading into the night and wobbling slightly as gentle ripples spread out from each rock skip. Trinity crossed her legs together and curled into a tight ball, already shivering even though she only stepped away from the fire a couple minutes before. How is Ariadne not freezing? These pebbles are freezing! she humphed and lightly stomped the toes of her boots, trying to shake warmth into her feet. She decided to wait for Ariadne, either until she talked or until she retreated to the fire. 
	“Olly,” Ariadne looked over her right shoulder and called. Trinity almost fell over; she had been leaning against the rock in silence for fifteen or twenty minutes now and was slipping in and out of a sleepy state. Olly’s head popped up from his ramen, looking for Ariadne in the darkness. “Can you throw me a blanket? Thank you.” Trinity heard a whumpf as the fluffy mass smacked into Ariadne’s arms. 
	“Come on up here,” Ariadne smiled at Trinity. Trinity cautiously rose and squished next to Ariadne, who wrapped the blanket around her shoulders. Trinity tried to share it with her, but Ariadne refused, saying she was already plenty warm.
	“Is something wrong though? You seem really quiet tonight,” Trinity finally asked her. 
	Ariadne slowly exhaled through her nose. “No, nothing’s really wrong...I’m just worried about Francis and my kids.”
	Trinity’s head bobbed. “I totally see that, and it’s a reasonable worry. But our team is professionally trained and…” she trailed off as Ariadne laid a hand on her wrist. She looked into Trinity’s face and smiled again, much more sadly this time.
	“I believe in you and your team,” Ariadne reassured Trinity. “I’m not worried about that. I’m worried that Ambar and Colibans’ convergence with us will be strange. Along with the rest of the children.”
	Trinity cocked her head, not quite understanding. “What do you mean? Francis’ll get too excited or protective and somehow screw up the mission?”
	“Have you ever worked with kids before, Trinity?” Ariadne asked. Trinity shook her head slightly. “Well, they’re very impressionable, especially when they’re younger. Coliban and Ambar aren’t incredibly young, but they just disappeared so fast...I’m not afraid that Francis will become crazily overprotective. I’m afraid that my kids won’t even know who we are.” 
	Trinity was even more confused. “Surely they’ll remember you. You’re their mother and Francis their father. How could they possibly not know who you are when they were just ripped away from you, making a big scene and whatever. It seems pretty unlikely to me that would happen,” Trinity huffed out, peeved that Ariadne was being slightly silly in her worries. The cold air was also starting to nip at Trinity again through the blanket.
	Ariadne pulled deeper into herself. She knew Trinity thought she was overreacting, and she hated that. “No, I don’t want to fight you on this, but that’s just the crux of this. I think you misheard the story. Odin didn’t force his guards to come in and pillage all of the village houses and steal away the children. He had somehow organized it behind the scenes, having it be a school field trip. But they never came home that night,” Ariadne explained to Trinity, desperately wanting to show that she wasn’t just an overreactive helicopter parent. When Trinity didn’t think of a response quickly enough, she continued, “No one’s kids did; they were all just gone! The teachers too. Francis and I almost wish that there was some big, dramatic night with guards clad in all black brandishing guns or knives or something! Just to get some freaking closure on where my kids are!
	“They might as well be dead!” she screamed across the water. She clenched her hand and thumped it against the side of the rock. Growling, Ariadne picked a slightly heftier pebble and chucked it as far as she could, holding none of the same grace Trinity’s skipping had. It’s loud splashes did nothing to calm the clawing rage inside of her. 
	Trinity’s ears burned. She shifted and pulled the blanket tighter around herself, and after remembering it was Ariadne who provided it, her fingernails became really interesting and she couldn’t help picking at them. They sat in silence for long minutes, only the sounds of the crackly fire and their coworker’s politely lowered voices accompanying them. Trinity stared blankly at her cuticles, seeing an entirely different image in her mind’s eye. 
	Why am I so stupid? Now Ariadne probably thinks that I think she’s too immature for this, but I don’t want her to think that! Why am I so bad at empathizing with people? Trinity lamented. I know I have a short temper, but that’s no excuse to be a big jerk. I’m so selfish. Naturally she’s going to be worried about her kids. I only snapped because I was cold. And I shouldn’t be cold because she got me a blanket. Give her the blanket then. You don’t need and you’re really not THAT cold, are-
	“Trinity? Are you okay?” Ariadne touched her fingertip to Trinity’s chin and turned Trinity’s face to her. “Do you want another blanket?”
	“No, I’m alright, thanks,” Trinity whispered. Ariadne didn’t remove her finger yet. “I’m sorry I was quick with you. I don’t mean to invalidate your worries in any way. 
	“Don’t worry, I don’t see it like that. It’s nice to be slapped with blunt reason sometimes.” Trinity smiled weakly. “So don’t hold on to guilt over this, alright? You needed to hear the full story, one way or another. Let’s go back to the fire now.”
	She let go of Trinity’s chin and rolled off the boulder, waiting at its side for Trinity to follow. 
	“Are you sure you want to go back now? You don’t want another moment just to yourself?” Trinity asked. 
	“No, if I spend any more time with myself, I’ll go clinically insane,” Ariadne replied smartly, plastering on a big smile. Trinity laughed at that. “You’re cold. I’m cold. Let's go warm ourselves.
	“We’ll get through this together, me and you and our team. My kids might not know me, but that doesn’t mean I don’t want to make them remember.”

↞⇼↠
	
	Crunch. Crunch. Crunch. Crunch. Swoosh-slsh-psh-slidsh. The regular, repetitive crunch of Adonis’ boot stepping on layers of ice and leaves and crispy dirt stopped as he startled, slipped, began falling, but roughly caught himself by clutching onto a jagged tree trunk. His eyes, mostly closed as a result of his lingering exhaustion, snapped open and widened dramatically. His pupils shrunk as he really saw what startled him. His nose tip trembled. 
	“...Sam?” Adonis cleared his throat. “Sam! Get over here!” he whisper-yelled, unable to tear his eyes from the mound in the dirty snow that had caught his attention. He looked away, biting back his revulsion, and slowly released the tree.
	The mission technically had not even started yet. Right now, Sam and Adonis’ team was spread out around the valley, ringing its edge. They were just barely concealed by the foliage and readying their gear and prepping last-minute things, all waiting for the start signal to descend onto the children. Adonis, of course, had to pee. He had crept a short distance into the forest, finished his business, and was coming back when a strange smell made him divert his path. He supposed there was a decaying deer or bear somewhere near and wanted to check it out. He truly had no desire to see it as he was pretty squeamish, but he thought it would be better to find it now and deal with it than have a small kid find it later and totally freak out. 
	He had carefully stepped around, wasting precious minutes to find the decomposing creature, straining to see in the dark without his flashlight. He found it, the thing-creature, and that’s when he slid, trying to avoid the thing on the ground, and called Sam. 
	Sam huffed as he saw Adonis standing awkwardly away from a tree, holding his arms tightly to himself. “What? You got scared of your own peeing sounds or something?” Sam dramatically flicked on his flashlight and dropped his vexed air now that he could actually see the terror suffusing features of Adonis’ face. He skipped to Adonis and caught his bicep, looking into him to try to see what was bothering Adonis so. “Hey, what is it? What’s wrong?” 
	Adonis jerkily pointed his thumb to the mass behind him. Sam’s lips pressed into a hard, unflinching line, not able to comprehend it yet. He cautiously stepped around Adonis, protectively putting himself in front of his rattled friend, and stared at it. The back of Sam’s eyes felt hot and his face hardened. 
	The guard’s uniform was tattered. Shredded, but identifiable. 
“How long do you think they’ve been dead?”
