# eGaD! pOsitivEly gHastLy, thiS Is!

“Hey! Sampson, Adonis, Aspen has been on her own for nearly an hour!” Prince called over to them, looking at his watch. “You guys gotta go, she’s bound to be on her own with Odin now.”
“Alright, alright, we have to move faster. Adonis, head of the group! Prince, rear! Everyone else, walk on the outside of the group! Leave no one behind!” 	Sam called and jogged to the front. 
Some of the children were resistant, protesting the sudden change in who they were supposed to listen to by screeching or crying or kicking at kneecaps, but most of them listened to Adonis when he promised they could see their parents soon if they listened and did what he told them to do. 
Except the most fickle kids in the group. A pair of two thrashed their arms about and screamed incessantly, refusing to let the world they had adjusted to get turned over again. Before they were prisoners, they were just Briarcliff children doing whatever their regular child things were. And then they had been captured, brought here, and indoctrinated with Odin’s agenda. And now, with camp life finally being normal, they were just supposed to follow these new, random adults? What if they were bad adults too, maybe even worse? What if they were just being taken prisoner all over again, and what if where they were going now was worse than it had already been?

Taylor knew these thoughts scampered haplessly around in their stressed minds. While she sympathized with them, she had no patience and was eager to prove her usefulness to her rescuers. She wanted to be integrally important in Odin’s demise. She placed her hands on her hips, nodding and mhm-ing as Sam commented that pair was being a bit of a nuisance. Their antics kept the whole camp's attention on them, trickling away precious, precious time one pitiful punch and vocal protest at a time. An idea blossomed in her mind. Raking her eyes around the camp, she suddenly dashed off and wrestled the fabric from one off the collapsed tents off the poles. 
Running back to the middle, arms full of bunched-up canvas, she saw Sam and the other adults, who hadn’t the chance to introduce themselves yet, approach those two darn kids and try to soothe them, resting hands on their backs, trying to explain what was going on. 
A hundred watchful eyes, shining in the weak flames of the almost-put-out fire, watched Taylor as she waltzed up, said, “Back off! I got this!” and proceeded to rip the fabric into two sections, quickly straight-jacketing both of the children by tightly wrapping them in the fabric. 
“There!” she said. She looked around, feeling rather proud and amused by her own resourcefulness, hoping to catch an approving eye in her audience. Sam grinned at her, laughing incredulously. “This solves the problem? A’ight. Okay, to the rest of you,” she spread her hands, spinning one slow circle to encompass 


Taylor, who had no patience, only had to fashion two tent-canvas straightjackets on a pair of especially obnoxious little devils who thrashed their arms and screamed incessantly before the rest of them understood and willingly (or perhaps fearfully) followed her to the forest without any struggle. Taylor was the only familiar person in this mysterious  adult-group, so it was only natural that she had such easy authority over the kids. She followed Adonis’ lead as he wound through the trees, slick ground-leaves, and patches of ice, wading through the thick ground cover uphill all the way back to the grate. Two agents lifted the grate, shoving a boulder underneath it to prop it open, dropped in, and helped person-after-person climb down the ladder and assemble in the vestibule below. Taylor extracted a promise from the troublesome pair she had wrapped up in tent canvas: if they wanted to be released, they would have to listen to instructions and not cause any more trouble. She kind of wanted to leave them wrapped up because their little legs trying to waddle fast enough to keep up was really funny, but Adonis would not let her do that, playfully scolding her while she giggled and unwrapped the devils. 
 The troublesome pair of rascals from before were unwrapped by Adonis, who scolded a giggling Taylor while doing it, the stragglers crested the hill and dropped down the ladder, and some of the kids were already being broken into groups and following agents back down the hill as they realized the vestibule was filling far too quickly. 
Finally, only Prince, Adonis, Taylor, and Sam were standing amongst the forest’s pines. Modestly impressed with their pace, Prince announced that the emptying of the camp had taken them only slightly more than thirty-three minutes. 
“Don’t jinx it now. You’ve still got to get all of them to the other side of Briarcliff,” Sam half-joked. He shook hands with Prince and said, “See you on the other side of this.”
“Yeah. And Taylor, you better keep an eye on those losers, alright?” Adonis nodded at the captured guards who waited beneath the grate. Prince and Taylor were now reassigned to making sure they did not try to contact Odin or trying to escape. “Good luck.”
Prince crouched, put his penlight in his mouth and his hands on the edge of the concrete, and swung into the muggy drainage system’s stagnant water with tinkling splashes. Taylor crouched too and placed one foot on the ladder to go down in a less chaotic way than Prince, but she paused.
“Hey Sam?” She asked timidly to get his attentionthis sentence is meh. “I know one other guard at the house who is willing to help you guys. His name is Finlay, and he’s fifteen. He’s got, like, the same length of hair as you, and his bangs are cut so they always go in his eyes, dirty blond, and I think he is about five-foot-ten or -eleven. Oh, and brownish-hazel eyes, and freckles on his nose. Just-just so you know there’s others like me. He’s a great guy,” she finished with a smile. 
The placement of the crinkles from her smile felt like they were in the same places where Sam’s face was cracking. He smiled back tightly and reassured that he and Adonis would look out for Finlay, then said goodbye woodenly and closed the grate behind her. 
He twisted to Adonis. “Uh-oh.”
“Uh-oh,” Adonis agreed. 
They stared at each other for a second. Odin was, is, will be, wildly unpredictable. Anger at Aspen was expected by both of them, but his reaction? Incalculable. 
We have to be unpredictable first. We have to be louder, more attention-grabbing, more distracting so he focuses on that instead of us or Aspen or anyone, Sam thought. He had an idea...unfortunately. An idea so sacrilegious, a concept that he hated he even thought of doing, but it would hopefully be crazy enough to stab  Odin's conscious. He fervently explained his idea to Adonis.
"Sam, no...no…" Adonis groaned and balled up his hands.
"We're wasting time, Adonis. We have to get the upper hand, and we both know shock works nearly every time." Sam continued, slower, "I'm sorry that we have to do this to ourselves, but we have to use what's been handed to us."
Adonis nodded sorrowfully. Sam was right; shock leads to fear, leads to freeze, fight, or flight. "He better freeze, Sam, you better be right, or I swear…"
"Got it." Sam apologized again. Adonis resented his brain as it willed his arm to move, to toss a small rucksack to Sam's outstretched hand. Sam resented his mind as it willed him to walk through the forest. He was stupid this was stupid this side idea was the worst thing he had ever dreamed up. But maybe it would make this godforsaken night end sooner. Maybe the payoff he hoped for was going to be worth it; maybe he could make Odin freeze long enough, step away from Aspen and Adonis long enough to follow through his own version of 'the plan.' 
The gun still hung heavy in his pocket. Sam almost wished Adonis hadn’t given it back. He exhaled and shook his head. He hated who he was allowing himself to become tonight.
He stopped. He looked down. Finlay. A name to you.
I am so sorry, Finlay. WTF WTF WTF WTF WTF WTF ???? GET HELP U ****** **** U UGLY DUMB BAD NO ONONONO WHY DID HE HAVE TO DIE WTF
Sam lifted his shirt and drew the knife from its fashioned sheath.

↞⇼↠
	
Wham! Francis jumped and twisted around at a loud boom. He quickly recovered and said, "Uhh...hello," to the small upturned face that waited right outside his van door. 
The girl stared at Francis for long, tense moments. "Dad?" she finally asked tentatively. 
"Ambar?" Francis whispered incredulously. She didn't forget us. Francis could have laughed out loud from pure joy as she launched herself through the door and strangled him in a neck-hug.
"I’ve missed you so much, Dad," Ambar whispered. "It was so cold." 
"I missed you too, A. More than you even imagine," he said, gently skimming his fingers over Ambar’s back. "Where's Coliban? Is he alright?" 
"Yeah, he's okay. We got split apart somewhere," she shrugged. Coliban always managed to get lost, but they'd find him eventually. 
Francis laughed. "Sure, I'm sure that happened accidentally, hm?"
Ambar finally disentangled herself from Francis. "There's a woman with us who told us to get in your truck, Dad." Right then, Francis finally saw the clump of shivering kids watching them silently. A couple tween-agers and an agent poked their head around too. 
"What are you all waiting for? Come on, come on, pile in!" Francis waved his hand. They didn't need any more encouragement; Francis turned his attention back to watching the road for anyone patrolling while they all dogpiled in the back, drumming the steering wheel. Ambar slid next to Francis on the passenger seat.
Once everyone was made comfortable (as comfortable as they could be with thirty people crammed in an eleven-person van), Francis revved the engine and made Ambar buckle her seatbelt. He started the drive to Silver Lake. 
"Prince, do you copy?" He waited ten seconds then switched to Adonis. "Adonis, do you copy?"
Over a crackly connection, Francis heard, "Yes, I copy. We are almost at the Manor's edge. Radio silence soon. Updates?" a few seconds later. 
"Waiting on word from Prince. I'm driving to Silver Lake now."
"Good. Oh, you found Ambar and Coliban?"
"Yes, sir, I've got one of them," Francis smiled and glanced at Ambar. She blushed and looked away with a ghost of a smile on her lips.
"Congrats, man!" His voice cut off suddenly. "Oh, sorry, Sam told me I gotta shut up. Over and out."
"Over and out!" Francis switched back to Prince. He was nearing the edge of the business part of Briarcliff, about to drive past the residential area. So far, only one van had picked up behind him. The main residential area is the last bit of civilized Briarcliff before the wilderness creeps up and takes over again. Francis hesitated, then unrolled his window and stuck his hand out to signal the driver behind to pull over. Prince hadn’t answered yet, and as the head driver, Francis knew he should wait for at least a couple more vans to join the convoy. 
“Why are we stopping?” someone called from the back.
“Because we need to wait for the other vans. I’m sure we’ll only be here a second,” Francis answered while keeping his eyes on the road they had just driven and his hand on the radio’s volume dial. 
Headlights. Were the golden beams washing over the vans friend or foe? Was Odin still trying to look for Aspen or Adonis or Sam or himself? Friend, Francis concluded as the headlights puttered out and pulled behind the second van. Tip-tap tip-tap. He was drumming the steering wheel again. Another set of headlights closely follows the first, which also switched off as they joined the line. 
Where is Prince? Francis’ thought summoned him.
“Francis, do you copy?” Prince finally radioed.
“Yes sir. What’s the delay?” Francis felt pressure settle on his shoulders as thirty perceptive pairs of eyes swiveled to the front at the radio sound.
“We have a couple of resistors captured. Continue to the lake.”
“That’s all? Alright we’ll-”
“Wait. Odin is still trying to find you, specifically. One of his radio signals randomly ran into mine, and I only heard something about killing you. I suggest you go on radio silence after this.”
Francis scoffed, then shook his head. “Alright then,” Ambar looked to her father fearfully. Francis saw her look and brushed off Prince’s warning with: “That’s- that’s a delightful tidbit. See you at the top.”
"Over and out."
Francis signaled again. The vans prepped, and then followed him closely as he zoomed off. He could not wait until this was all over, and he prayed that Silver Lake was far away enough for Odin to not find him tonight.
