# stompy stompy odin angy

Sequestered in the infamous office, chipping away her boredom by spinning in the office chair, Aspen stopped spinning when she faintly heard the tell-tale creak of the front doors opening, a pause, and then again as they swung closed. She shut her eyes and dropped her head to the chair’s headrest, her chest rising with an uneven skip of a breath. 
	Anytime now. Her eyes drifted to the window, the frosted spiderweb-by glass fascinating her with its endless fractals. Fractals. An endless shape; no beginning, no end, just repetition repetition repetition repetition endless, beginningless, repetition, repetition. A dizzying array of hairline fractures indeterminably mingling. Ice-crusted glass was all it was, just whitish ice on clearness. 
	And beyond that, a sea. No, a mountain. No, just a forest. A forest waving to her. No, no, that’s the air moving the treetops. A swirling, waving, liquidy forest. 
	And all around her. The sounds. Fire crackling. A repetitive sound, a typical pattern beating regularly. Not quite chaotic enough to be natural. Tap tap tap. Footsteps. No, that’s the fire! Or is it something moving outside? What was that strange black outline out there? Adonis? Probably. 
	You’re going crazy. Shut up, Aspen told her mind. Tell me something I don’t know. 
	Tap. Tap. Tap. Too regular. Not fire. Has to be footsteps. Tap. Tap. Thud. 
	Aspen gave herself a little shake. She switched off herof her mind, a mind with far too much anxiety and overthinking for right now. She fiddled with the sword edge and trained all her focus to the door. Odin was on the other side; she could practically sense him waiting there. Why isn’t he walking in?
	She got tired of waiting for him to let himself in. Fine. If he isn’t man enough to walk in on me, I’ll help him. She marched herself over, carefully keeping a tight hold right under the crossguard. With a huff she raised the sword, grabbed the handle and-
	“Stop!” 
	Oh finally, a voice to listen to other than myself, Aspen thought sarcastically. And she did stop. She stopped because she wasn’t the one saying to stop, Odin had.???????? What  Had he heard her walking over? She supposed she hadn’t exactly tried to be quiet. She waited a moment longer, and then decided with a shrug that she didn’t feel like listening to Odin anymore, even though that pitiful sounding ‘stop!’ hadn’t sounded like it was directed to her. She yanked open the door.

↞⇼↠
	
	…Maybe make switch to odin more obvious ???“Hey-! Oh-” I jumped. My hand stayed hovering at where it wasis was just before, resting on the doorknob to let myself in my office. “Hi.”
	I was’m fifteen all over again. Too aAwkward, all flustery because she was she’s way too pretty to be with me, and I kneow it. I’m not fifteen, that was basically ten years ago! I remind myself. Why can’t I say anything? She’s here. She came back. I had so much to say just…just an hour ago…so why..? Eghhhhhh dont love it, like the idea but the wording not so much
	I toreear my gaze away from her stunned face. Aspen’s mouth is hanging open just a fraction, and her eyes are slightly blank, so I know her mind is reeling. With what? How well do I really know my wife? I can only look down, at my hand so self-consciously waiting for the door handle to come back to rest on it. I could brush my fingertip across the back of her hand, I could feel the softness of her hand right now. Sniffing, I push away that and quickly move my hand to my pocket, almost knocking into the wall in my haste to not touch her stable hand. 
Say something. Anything. Literally just spit the first words that come to your mouth- I cleared my throat. “I…I checked out that build you were telling me to in your single-player. It looks really good,” I muttered. 
She did not care to hear what I had to say. I had lost Aspen. After everything, after all the control I had over every aspect of my life, over every aspect of everyone’s life, Odin had lost it all. 
“Well, that's nice,” Aspen replied coolly.  “Whilst you did that, I hid from you because I thought you were going to kill me.”
“Aspen, I could never kill you. You mean so much to me, and I’ve been doing a lot of thinking-” Aspen’s face switched to disgust mixed with disbelief. A corner of her mouth quirked up, and Jeff cut himself off before he said something stupid. He awkwardly wiped his nose and looked to the floor. Nose wiping part feels a little awkward not that believable !!A LOT OF THIS NEEDS TO BE PAST TENSE!!
Aspen twisted back to the office and waved the sword around carelessly, almost catching the tip on the wall. “I’ve been doing a lot of thinking Aspen! I love you Aspen! You know me, Aspen!” she mimicked. “No Jefferson! No, I don’t know you! And whatever ‘thinking’ you’ve been doing could ever explain away what you’ve already done! How do you not see it, man? How-” her throat caught and she sunk onto the edge of the desk in a defeated way. Quietly, she asked, “How far gone are you?”
Jeff looked away miserably. He huffed, stepped in, and gently closed the door behind him. “Aspen…” He trailed off, not sure how to finish his sentence. 
“What? What’s on your mind Jeff, after not seeing me for a couple days? What’s it like without me here for you to yell at?”
“You want me to yell at you Aspen?” Odin had a whisper of threat in his voice. “I’m rather tired, but if you really want me to, I’m sure I have just enough energy to scream at you. I would ask you how your days have been, but I’ll bet they sure as hell haven’t been cold! Adonis is a good bed warmer, isn’t he?” ohhhhh shiiiiiiiiii—--
Aspen pushed her palms into her eyes. A migraine was threatening to bloom with all these mind games fueling it. “What is your problem, Jeff! I may have run away but I’m no cheater! I can’t-”
“Oh, so it’s Sam then, huh? If it’s not one it’s got to be the other,” Odin spat bitterly. His words were vicious, but he still stood awkwardly near the doors, carefully staying out of range of Aspen and the sword. 
“Sweet mother of….why are we even talking about me? Hah, why are we even talking about ME! HOW MANY PEOPLE HAVE YOU KILLED! HOW MANY PEOPLE HAVE YOU MURDERED!” Aspen screamed at the top of her lungs, leaping off her desk-perch, the sword clattering loudly to the ground. She was ferocious, lunging at Odin poking him in his chest with her finger, forcing him into the far corner of his office.
“DON’T TOUCH ME YOU CHEATING WENCH!” wench feels a little old-englishy? Idk if u want to use a curse word but maybe something more rough and less fancy Odin hurled back, roughly seizing her wrists and yanking her to him. His face twisted murderously.
“NO! I am so sick of you pulling this- this-” Aspen screeched in pain  as Odin moved his hands up to her improvised bandages and clenched. His face flickered, his eyelid twitched. 
And he smiled.
Aspen cried out again. A sudden black rush flooded from the back of her head and she thought she might pass out. “Odin- I- 
“Jefferson! You’re hurting me!”  good line
Jeff’s face relaxed imperceptibly. He let go of her in a flash. Aspen curled around her hands, instinctually arranging her back to face Odin, accidentally leaving herself very vulnerable to him. Odin sighed heavily and rubbed out his forehead with the bottom of his palm.
“C’mere, love, let me see your fingers. Let’s go get-” the air whuffed out of him as Aspen quickly stood and jammed her elbow into his stomach. He coughed, half-bent over but refusing to go down, holding his chest?????????????breast with his hand. Aspen gave him no time to recover: whipping around, she lifted her right knee, and screwing up her face?? screwing??, jabbed her heel hard onto the top of his foot. He crumpled to the ground.
Aspen stood over him. Watched him struggle to breathe for a few seconds. She turned around, scooped up the wayside sword, and faced him again, slowly turning the hilt around and around in her hands. Odin watched her, his pupils shrinking to pinpoints. He slowly shifted to sitting criss-cross on the floor, one hand still hovering over his breast as he panted. 
Their eyes burned through each other. Emerald-green depths, hidden behind golden rimmed glasses. Sea, sky, forested depths, framed in dark lashes. Each, both, all, eh welling with tears.
“Why,” Aspen coaxed. One syllable. Infinite weight behind it. eh
“I’m sorry.” Odin pulled away his hands, staring at the gentle folds of skin creasing each finger and palm. good He dropped them, looking at Aspen again. He shook his head slightly. “I’m so, so, sorry, Fauna.” yesss i like the way u use their names
Aspen swallowed. Idk if its on purpose but i like the detail of ‘aspen swallowed’ instead of ‘fauna swallowed’ “I don’t even know what to say, Jeff. Look at us. Look at you. Look at what you’ve done.” Her voice was low, strained.
“I know, oh God, I know.” He cussed. “I know! What would my grandfather think now? And my family! Oh God, what have I done?” he groaned. His chest shook. Wait why is he sorry now? Genuinly confused.
“Jeff, ‘sorry’ isn’t gonna cut it. This,” she waved at nothing, “is beyond what a sorry could ever fix. Ever.” She still lightly twirled the sword in her hand. Good line
“Fau- Aspen-”YESSS he chewed his lip, looking askance at the doors. “It was a pit. It is a pit…I used to stand on its edge but I got yanked in and sank to the bottom and I know I can never fix it, but damn I so wish I could. The farther I went the farther I had to go because after one time I knew I couldn’t go back to the way I was so I had to accept the way I was going and looking back I was such an idiot what was I thinking. Run-on sentence. Maybe split up into little sentences? Like how people are at a loss for words when angry You deserve none of this and I hurt you so many times and I’m so sorry and the children and the families deserved none of this I just went and ruined everything. That’s what I’ve been thinking of, that’s what’s been making me drink so carelessly, I just-” 
He cut off as Aspen crouched in front of him. She grabbed his chin with her hand, her stomach knotted, her chest hot.her chest what? She glowered at him, rolling her upper lip around her teeth. He sat loosely. Broken. Chipped. Nothing burned in his eyes. Just surprisingly clear, roiling black pits that had sucked him under and were now looking for another victim to enstrangle in the inky depths. She laid the sword on the wood floor, mere inches away from Odin’s hand. 
And she pulled his lips to hers. Why tho
Closing her eyes, she breathed him, leaned into him, pushing his back against the wall. Jeff’s hands omitted the sword, an integral tool to freeing him from this mess, and chose to caress the back of the far more dangerous weapon in his lap. Wait are they sitting now?? A breathing, livingalive weapon. Aspen. 
Aspen ran her fingers through his hair, pulling him even closer to her. Jeff shifted again, freeing one hand, and trailed her jawline lightly with one fingertip. He rested his palm on her right cheek, scratching the skin right behind her ear where her neck started. 
Gently moving her lips to his ear, Aspen murmurmered in disbelief, “Hmm, are you trembling, Jefferson?” 
He pushed her face back to his lips and answered after a pause, “No, of course not.” But his burning blush gave a different answer. Yes, Aspen, I am trembling. For you, only for you. 
“Maybe you’re the cold one then,” Aspen suggested, teasing. She loved this, every second of this. She scratched his side, drawing her fingers up his ribs. Whispering into his mouth, she whispered “Are you ticklish?”
He flinched from her, concealing a grin. “No.” But he carefully pressed her hand down, wrapping it around to his back. 
Electricity hummed through them. Jeff could feel Aspen’s heart hammering and likewise Aspen could feel his. I miss tenth grade… 
Aspen longed to escape back to high school. Odin dreamed of making Aspen forget everything that happened in the past year and start fresh. 
Slam! 
“They’re in the office by now!”
“Shh! Be quieter-” lol
Aspen jerked away from Jeff as Adonis’ and Sam’s voices echoed from somewhere in the manor. She crawled away backwards on her palms, ignoring their throbbing through the bandages. She wiped her lips self-consciously as Odin’s attention flickered between the doors and her burning face. 
The door groaned open. A key of light washed over the floor, then Aspen, then glazed the edge of Jeff’s shoe. Adonis stepped in, looking first at Aspen’s upturned flushed face then at Odin lounging in the corner. Not breaking eye contact with Odin, Adonis stuck out his arm to Aspen, who pulled herself up with it. Odin then surreptitiously(?) tried reaching for the sword discarded at his side, but Aspen quickly grabbed the blade from him.
“Aspen? What are you doing?” Jeff asked. Oddly, he sounded genuinely surprised. But his voice twisted to spit when he looked at Adonis and said, “And why do you need to be here? My wife and I were just having a very touching moment. Alone.”
“Sounds pleasant. Guess your distraction worked pretty well, huh?” an unfazed Adonis asked Aspen. She nodded sheepishly. Wait still dont get why she would kiss him? Why not just talk?? Wouldnt she *not* want to kiss him????
Maybe a little too well, she admitted to herself, somewhere in the depths of her mind. She brushed away that string of words like an old, dusty cobweb. OOF
“One second, you’re denying your cheating, the next you’re kissing me, and then you’re back with Adonis? What the hell is your problem Aspen? You make me sick,” Odin hissed venomously, double-backing from the vulnerability he displayed seconds ago. “And you, Adonis? Where’s your big companion? Not got much of a tongue without him?”
Sam walked through the door too. 
“Aspen, prepare yourself,” Sam commanded. Forcing his face to stay blank, he produced a misshapen satchel hanging from his side. Sam overturned the bag so the foreign lump inside it fell straight towards Odin’s shriveled carcass of a heart. 
“Boo,” he said when it landed. A frozen-solid, shriveled and grey-skinned severed hand thumped against Odin’s coat.
