# Gir

The hand thunked to the floor as Odin shirked from it. Revulsion tainted Odin’s face while Aspen’s eyes grew impossibly wide and she blanched. 
	“What is this?” Odin asked flatly.
	“Another one of your victims,” Sam replied coolly, gently tossing the bag to Odin who quickly stuffed the hand in it. 
	Odin scoffed. With all the drama he could muster, he rolled his eyes and looked to Aspen, asking, “They forced you into this, didn’t they? C’mere Aspen, I can get rid of Sam, Adonis, and their whole silly plan.” He offered his hand to her. Smiled. “I love you, butterfly.” pet name adds realism i like it good sentance
	Adonis looked ready to spit. “You have a sick way of showing love,” he said, clenching his jaw. Odin twisted to them, furious, a muscle twitching in his temple. He gave up and faced Aspen again when Sam stepped in front of Adonis and stamped his foot.
	“Odin, the plan-” Aspen started whispering. 
	Cutting her off, Odin continued his argument, desperate to win back his wife again. Jeff let his hands hang, chagrined, and said, “Aspen, before I loved you, my life was pitifully boring. I was flawed, imperfect, unlovable. After I met you, you beautiful, amazing woman, when you came along, you took my sorry tune and you turned me into a choir’s symphony. You are my composer, my conductor, my everything. Please. Look at me! I am yours! I am your soulmate, I am your twin flame, I am your everything-!” awkwarrrdddddddd
	“Are you done yet? Are you done with your sordid tune crap?” Aspen crossed her arms. The tiniest, mocking snort followed by a giggle came out of her, and she arched one eyebrow and tilted her head at him. “I made the entire invasion plan, ding-dong.” good sentance but still dont get why kiss??
	Realization hit Odin. Aspen could almost picture the waves of shock buffeting him as his face changed again, his dramatic and ‘loving’ airs dropping.
	Aspen could see the rage starting to shine through Odin’s thick layers. Her heart quivered, a small tremor running through her body; she knew without a doubt that this night could go exactly how countless other lonely, cold and dark nights had gone. 
But it’s different this time, she reminded herself. Adonis and Sam were here. They bolstered her confidence. She forced away her fear, shoving down her tremors so the sword still clutched in her hand wouldn’t shake. “My love is long gone for you. It’s been gone ever since you’ve so kindly imprisoned me.”
	“Then what was-” yeah good question man.
	“Oh, what I just did? Don’t even try to fool yourself. That was just an act. I don’t even lust for you anymore,” Aspen said, grinning. Though a small swivel of her wrist betrayed the little lie in that. Sheesh and yipes“I needed closure. I needed to know why on earth you did this to me,” she flared her fingers, “and other atrocities to hundreds of kids and families, and I guess I know now. But it still doesn’t make sense. You’re a monster, Jefferson. Your twisted plans are a million times worse than anything your family ever did to you. Everything you’ve built, in this house, in this valley, all ‘for me;’ you were lying to yourself! I understand feeling a dark pit trying to suck you under, but Jeff, it’s not hard to not kill people! Cmon show some empathy aspen thats ur hubby ur talking to Just think of how many lives? people you’ve ruined! You have destroyed everything good in Briarcliff Valley!” Aspen declared. 
	Silence. It was heavy, physical, taut and becoming tighter every second. Aspen, Adonis, and Sam watched Odin carefully. He kept his gaze trained on the ground and breathed carefully timed breaths. 
	In the quietest voice, Jeff asked, “Aspen?”
	“What?”
	He sniffed and wiped his nose, but Jeff took a moment longer still to raise his gaze to Aspen’s. His face was slack and expressionless. Aspen had finally gutted him. It didn’t feel good, she actually felt quite sick to her stomach, realistic i like it but what choice did she have?
	Jeff opened and closed his mouth. Pausing, he closed his eyes for a half-second and slowly exhaled again. 
	A flicker of expression. “Go to hell.” Odin launched from his crouch and slam-tackled Aspen. Cool cool.His face terrified Aspen. In all their years together, she had never seen such twisted, unmasked rage on Jeff’s tender face. In a matter of seconds, Odin was straddled atop a struggling Aspen, his knee pressed into her chest, squeezing out her lungs, and one hand forced her throat to the floor and the other fought for the sword. Sam and Adonis responded instantly, both shouting for Odin to get off her! and trying to pull him off, but Odin swept at them with his legs and kept them just out of range. 
Aspen gurgled and had a sudden vertigo attack as the ground disappeared and now she was flying. Curious black spots crept over her eyes. What was with all the loud sounds? Adonis’ yells and Sam’s threats were slowly becoming a confusing high-pitched ringing. And what was Odin saying now? She wasn’t sure, but Sam’s voice came through again.
“We should’ve killed the bastard when we had the chance!” Sam’s voice was hoarse. The water filled her ears again after he yelled, and the high-pitch was back. 
Kill… no, we’re not supposed to kill him, that makes us just as bad as him… she thought dreamily. Her hand flashed with pain just then; she still had her grip on the sword! Just as bad…as him…
Bad…
The world went black. She was swimming in an ocean. How pleasant. A spot of pink was next to her, and when she moved her eyes to it, the spot materialized into a flower. She smiled and cupped its bulb, pulling it close to her face to smell it. Something wasn’t right. 
She tried to breathe and found that she couldn’t do it. Her nose refused to let in air and her chest refused to expand. Troubled, she let go of the flower and faced the ocean just behind her. The turquoise water lapped at her ankles, but she didn’t hear it. The waves crashed just in front of her, their sea-spray profused the air with salty flecks, but they were mute. Alarmed, she started to run into the water, but someone latched onto her arm and turned her around again. A warm hand, a brown curl, a smattering of freckles across a shapely nose bridge below mismatched eyes. Adonis.
“What are you doing? It’s time to go. We have to go.”
“Where?” Her lips moved around the word but her throat couldn’t make sound either. Adonis must’ve read her lips, because he still understood her. 
“We have to go. Come on?” Adonis’ face glitched for a second. His outline was blurry, actually, everything was quite blurry, but Aspen swore half of Adonis’ face had melted to the likeness of liquid wax for a moment before snapping back to flesh. 
“No, please, where are we going?” she pleaded mutely.
“We have to go!” Adonis was getting agitated now. His face glitched again, or melted, or whatever was going on, but this time it wasn’t fixing itself. Adonis’ voice took on Odin’s roar as his face appeared out of the warped melting mess of Adonis’, and he yelled “We’re leaving! Now!”
	She was blinded. The sun rays framing Odin-Adonis’ face expanded suddenly, growing, growing, growing, till it filled her entire vision with a glorious golden explosion. Fire rained from the sky. Hellfire. Hellstorm. It burned her skin, ripping blisters and innumerable sores up her arms and legs and chest, the sand became glass, the ocean boiled and the pink flower burned up instantly. The light kept expanding, worsening, the fire trained itself on Aspen’s chest and hands, and suddenly, as her skin was rent open and blood seeped from her raggled skin, sound returned. 
	Adonis was yelling again, but so was Sam and Odin and maybe even her. She snapped back to reality as the blinding light reined in itself, minimizing into the distant hallway light shining through the door-crack. She cringed away from the light, the sound, the overwhelming blindness of it all. Adonis and Sam had managed to scoop Odin under his arms and were hauling him off Aspen. She breathed. I can breathe again, she thought with relief. Her chest was free from his knee, and that was what brought her back. Her chest shuddered as she drew in another breath, found her arms and legs and hands; how the hell was the sword still clutched in both her and Odin’s hand? She wasn’t sure. But her brain barely registered what she was doing as she flicked her wrist and turned the sword around. 
	Odin was almost off her, but he sensed her movement and restarted fighting his captors in full force. Aspen’s head still spun and she was beyond disoriented, but with a fierce cry she pushed herself up to her knees. “Let go of him!” she screamed at Sam and Adonis.
	They listened, dropping Odin unceremoniously. 
What Aspen did next shocked Adonis and Sam, but neither were fast enough to stop her. Even before Odin’s knees hit the floor, Aspen wrapped both hands around the hilt, pulled back and angled the sword above her right shoulder, and though she barely absorbed what she was doing, her aim was true.
The sword tip caught on the slightly-distressed roughness of Odin’s coat. The blade became a flash of silver as Aspen plunged it into his chest. It was a long sword, old and antiqued, but well-kept with regular polishing and sharpening. Aspen pushed it all the way through his chest and out his back, puncturing skin, lungs, grazing his heart. She cringed and shuddered as she felt the blade scrape his bones. Her momentum kept her going forward; Odin fell back to the wood floor. The wood floor, already cut and stained from previous abuse, now acquired new stains as it clotted with Odin’s ruby gore. She leaned heavily on the sword, still on her knees but hunched and bow-backed so her face hovered mere centimeters above Odin’s. Her golden hair slipped out of its updo, becoming a curtain. The tips of her hair strands were stained cherry where they brushed Odin.
Adonis and Sam were frozen, unable to decide what to do. 
Jeff looked up to Aspen’s eyes.Their green used to calm him with images of peaceful, tucked-away forests, but now all he saw was churning treetops whipping up a  frenzy. He was shivering, tears streaking from the corner of his eyes to his cheeks, bubbles of blood and saliva mixing at the edges of his lips. 
“I thought you loved me,” Jeff whispered.
Aspen sobbed. “I did love you. But you took everything way too far and you hurt me and a thousand other people.”
“I’m sorry…”
“I know Jeff. I know you are,” she carefully moved her left hand from the sword to cup his face. She kept a firm hold on the hilt with the other, still needing its support to hold herself steady.
Jeff coughed pitifully, a bit of thinned blood misting from his mouth. “I’m sorry…You never deserved this….if I could go back, make you never meet me, so you could have been…happy…..I would, I would go back…”
“No, Jeff, no, I was happy, I promise I was happy.” Aspen put her head down next to Jeff’s and gave him a neck hug. Her tears mixed with his on his cheek. “I loved you, Jefferson, I swear I did.”
“Mm..” He didn’t say anything else.
“Jefferson?” Aspen reeled back. She tapped his face. “Jeff! Jeff!....He’s gone! Nooo!” she screamed. If there was a fine line between love and hate, that line had been blurred, twisted, woven into something strange and unknown a long time ago. Adonis and Sam finally broke their reverie and launched into action now that Aspen had her final moments with Jeff. “No, no no no no no, what have I done! He’s gone! I’m a murderer!” Aspen shook with her sobs and pounded a fist on Jeff’s unresponsive body.
Adonis pulled her off him and sat with her like he did that day she ran away from Odin. “It’s ok Aspen, it’s alright. You’re ok, you’re ok,” Adonis hugged her tightly and quietly reassured her over and over but she still cried. 
Sam walked just  out of the office, pulled out his radio, and called for any and all free persons to come to the manor immediately. He tucked it away and pondered Odin. His nose wrinkled with the overwhelming copper tang in the air. Adonis started freaking out and Sam went over to kneel next to them.
“Aspen? Aspen, are you here with us? You’re not a monster, Odin left you no choice, you hear me? So just-” Aspen tried to listen to Adonis but the world was like sand slipping between her fingers. 
“Stay with us Aspen! Listen to me!” A wavering lilt overtook the words…she was happy to go wherever, the words were not compelling commands…The tropical ocean was back, and this time the sun was not exploding in furious heat. It was just a nice, constant heat wrapped around her body. 
“...stay with me….” But the ocean foam tumbled like pearls around her, pushing, pulling, receding, coming back in a turquoise rush, pushing, pulling, receding…drifting. 

↞⇼↠
