# "Love"

Odin padded into his office, his trench coat soaked through from walking in the rain. His quick perimeter check showed that there was no evidence left behind from the agents, but no matter. He was certain the agents would creep into his mansion soon, one way or another. He slipped off his dripping coat and hung it by the fire to dry, then meandered over to his chair. In his head, he fantasized the many ways his empire would soon come together: first he would take over the valley, then expand his borders out until he felt safe within his self-drawn property lines. He loved thinking of the fine details of his plans late into night when there was no bustle from the helpers and the whole world was serene. He twisted his chair to the massive arched window looking out into the tall pine trees, the ancient evergreens standing stoically, with columns of clouds left over from the storm and a few faint stars, scattered across the sky like ice chips. He tumbled deeper into his thoughts, getting lost in his own mind until he heard the heavy door creak open on its rusted hinges. He almost yelled “get out!” thinking it was another ‘urgent’ message that had just come in, but cut himself off when he heard the light footsteps that only Aspen-Fauna, his enchanting wife, could make.
“Hi baby. I’ve missed you recently,” this girl seemingly made out of light, glass and elegance said in a slightly sleep-deprived raspy voice. She traipsed her way over to Odin and straddled his body with her legs, burying her face into his chest. He smiled into her hair and rubbed her back gently. Aspen-Fauna has been the love of Odin’s life since high school, when they became such good friends they decided to take their relationship to the next level. She was the first thing he thought of when he woke in the morning, the last thing he saw at night, his only weakness.
“Have I ever told you how pretty your name is?” he whispered into her ear as they relaxed deeper into each other's arms. “And why are you up this late? You should be asleep, baby,” worried he had kept her awake, but also selfishly glad she was here right now.
“I don’t mind staying up. And you’ve been too busy recently; I miss you a lot,”she quietly said into his shirt, the fabric muffling her voice.
“I’m sorry,” his voice breaking a little as he realized he missed her too. “I promise I’ll be more available next week. For now, let’s just cuddle a little longer before I have to go back to work. We had a bit of a security problem today, and I have to review this footage while it's fresh.”
“Okay,” she barely mumbled into his chest.
Odin held her in his arms for a long time, watching the clouds thin to nothingness in the darkness outside and feeling her breathing slow. After almost an hour, he knew that he should put her to bed so she could sleep well, and that he must get back to his work. He took a deep shaky breath, admiring for a few more short minutes the precious girl that straddled his lap, desperately wishing he didn’t have to cut this off. Finally, mustering the strength he needed, he gathered this delicate pile into his arms and carried her out of his office to their bedroom. He placed her gently on the bed, pulling her covers all the way up to her chin the way she liked, kissed her softly on the cheek, and quietly left the room, smiling to himself.
As he walked over to the security wing in the house, he remembered highschool dating with Aspen-Fauna, the way everything she did captivated him and distracted him to no end. Odin was always the smart, slightly cocky kid in class who loved to be the most intelligent, the model student, the most admired. Aspen-Fauna was clever and pretty, and all the boys dreamed about asking her out, but knew they had no chance. She was funny and sweet, if a little shy and soft-spoken. Odin still didn’t see what Aspen was attracted to in him, but they were the best of friends in ninth grade, poking fun at each other, hanging out, and playing games on the weekend. He had always crushed on her, but thought she would friendzone him if he asked her out, so he suffered in silence for another year. In tenth grade, Aspen suddenly grabbed his face and kissed him while they were splashing water at each other in the ocean. Odin, of course, kissed her back, eyes closed and leaning into her fully. It was actually his first kiss, and he remembered each detail vividly: how her blond hair crusted in the salt water, how her green-blue eyes seemed to hold both the sea’s tempest and the deepest forest, how her light-blue tie dye swimsuit framed her body beautifully. Just thinking about that fateful day in the crashing waves seven years ago still makes him woozy with joy.
Odin snapped back to reality when the door to security came up far too quickly, his happiness melting into seriousness as he rewinded the footage. Looking deeper into it, he noticed the video started to loop seamlessly, near perfectly at right about 7:00 P.M. until about 7:13 P.M. At 7:14, Odin finally saw a clip of the two tall agents running away from his garage, with the unfit night-shift security guard chasing after them while wailing into his walkie talkie. Bored, Odin looked away and thought of how he could convince the agents to either leave or lure them onto the property. They might need a quick trip to the basement; I think they know too much already. Odin continued to overthink his possible solutions until he glanced up and noticed the clock now read 4:00 A.M. Crap. I’ve spent too much time here. I need to go back.

↞⇼↠

	Adonis rubbed his bleary eyes and reluctantly pulled himself up from his cot. He had not slept well, tossing and turning the whole night from anxiety and the constant sound of the wind and rain. He sat on the edge of the canvas for a moment, attempting to wake up fully. Suddenly he jumped up, having almost forgotten about the state Sam was in. He pushed open the flaps of his tent and ran over to the ajar doors of the SUV, where a larger, nicer bed had been temporarily set up for Sam. Sam didn’t stir at the sound of his footsteps, and Adonis’ shoulders slumped slightly. Last night, after making it back up to the camp, Adonis and Jeff had called Selena and asked her what to do. Normally they would have called 911, but since technically the perimeter check was trespassing, and sirens would have revealed their hiding spot, calling Selena for advice seemed better. She recommended monitoring his heart rate, keeping him warm, and wrapping the contact area (where it left a burn mark) with sterile non-sticking gauze. 
	Now in the morning, the sun just rising and the sky clearing from the storm yesterday, Adonis checked Sam’s pulse again using his wrist. Jeff still wasn’t up yet, so Adonis couldn’t use his vitals computer. Assured that Sam was doing alright, Adonis stumbled over his tired feet to the kitchenette to make some coffee and eat a banana. He sat on the edge of the van with his coffee, nice and black the way he liked it. Watching the trees shake off the water droplets in the breeze, Adonis waited for Jeff to wake up and ask him why the plan failed; in the craziness of last night, he’d missed the chance as both of them gave medical attention to Sam.
	Finally, after almost half an hour, Jeff walked into the camp from the perimeter. He had presumed Sam and Adonis would be raucous neighbors and did not want to be bothered by them, so he made his tent a little deeper into the woods than the other two. However, last night there had not been very much noise. Jeff stretched and walked closer to the kitchenette, but was swiftly grabbed by the back of his shirt and silently pulled away by Adonis back to the edge of the camp. 
	“Why didn’t the security measures work last night? I thought you gave us the all clear and you said yourself we were good to go. So then why am I covered in scratches and Sam is passed out in the truck?” Adonis whispered angrily to Jeff. He was trying to be quiet so Sam could get the best rest possible.
	“I really am sorry. I made a mistake last night that I didn’t catch until it was too late. It was an honest mistake,” Jeff answered back slowly, glaring all the while at Adonis.
	“Aren’t you supposed to be the best in your field? Some kind of professional?” Adonis demanded of Jeff. Before Jeff could answer he cut in and said, “whatever. I hope your antics don’t get you fired,” shoving Jeff away and stalking back towards the camp.
	Jeff stood still for a moment, angry that Adonis was blaming everything on him. He watched Adonis push the curls of his hair back that had fallen loose in his tantrum. Watching him be angry only forced Jeff into an even worse mood. He turned away from the camp, away from the prospect of breakfast, and stomped deeper into the woods. This isn’t even my fault! If only Sampson had not been an idiot and injured himself! And I AM the best in my field! I just made a small mistake! He wished he could go back in the past and change things so he could at least earn some respect from Adonis. He was the real pinheaded problem here. 
↞⇼↠

	
	A breeze stirred the high reaches of the pine trees, brushing their needles together to create irregular music. Distant bird calls echoed between the trunks, adding their piercing chirps to the natural cacophony. Watery sunlight dimly poked through the boughs, stretching its weak rays to the forest floor. Mice and rabbits meandered among the trees’ roots, scrambling through detritus in search of nuts and seeds. Sampson stirred slightly in his sheets, slowly waking up from his slumber. His eyelids twitched and his brow creased while a fever-induced drop of sweat languidly slid past his temple.
I’m dead, was the first and only thing he could think when he finally came to. His whole body ached, and he could feel fresh bruises around his body, as well as the burn mark on his hand. Realizing the pain likely meant he had not died, he lifted his throbbing head to look around him. He noticed he was in the back of the van, doors open, and Adonis was quickly walking back toward camp, his face reflecting a storm of anger. At the edge of his vision, he saw Jeff slink deeper into the forest, which was much brighter and alive-feeling after the rain. 
	Adonis saw Sam’s head poking up, and walked over to him:
	“Hey. You were out for a while. Are you feeling okay?”
	“Not really. What did you do to me? I feel like I fell off a cliff,” Sam groaned quietly, finding talking made his headache worse.
	“I mean, yeah kinda. I had to chuck you over a fence. You’re lucky you didn’t break a bone. I’d rather have you covered in bruises than interrogated by that freaks’ police force,” Adonis half-chuckled, happy that Sam had finally woken up. He had been scared that the kitchen remedies would not work for the burn. “Anyways, you should still sleep some more. I think that’s when the body heals best.”
	Adonis gave Sam some more tylenol for pain, forced him to drink water, then let him sleep. He stood up and walked to the kitchenette to finish his sparse breakfast, barely noticing and hardly caring that Jeff had disappeared.
