# Betrayal

Sam opened his eyes in the pitch-blackness and lifted his head, groaning as the small movement sent pain lancing throughout his entire body. He blearily stared into nothingness, waiting for his eyes to adjust to the darkness. When he had waited for a while and still could see nothing, he gave up and started feeling around with his hands, attempting to get his bearings. His wrists were tightly bound at his lower back; after attempting to loosen them, he accepted that they were stuck there. 
Great. I have no idea where Adonis and I are at (I don’t even know if Adonis is here!) and I can’t  move or see. Fantastic. I should check whether Adonis is here, but if I call and there’s guards near me, they’d know I am awake. Sam debated the issue, then decided it would not make a very big difference if they knew whether he was asleep or awake. 
“Adonis! Are you here?” he whisper-yelled, straining his ears for any kind of noise. He groaned again and swore as talking made his head throb. Did they drug me? 
“Yeah, I’m in here. What the hell did they do to us? It hurts to breathe,” Adonis responded through clenched teeth, chills traveling down his back and legs with every beat of his heart. His fingers and toes curled from discomfort. 
“How long have you been awake?”
“I just woke up when you called me.”
“Yeah, same. Let’s try to find each other?”
“It’s gonna hurt, but sure,” Adonis agreed. “Try to follow my voice.”
Barely inching along, Sam ignored the pain shooting through his limbs and crawled on his knees to where he thought Adonis might be. Adonis moved likewise and the men met in the middle, both collapsing and panting from the effort. Although they had each crawled less than ten feet, whatever the guards had done to them rendered them weak. 
“They either drugged us or beat the living crap out of us,” Sam huffed. “Do you have any idea where we could be, Adonis?”
“I’m assuming we have to be in the mansion. The brutes must be working for the guy we were sent to check out for the bomb threat, but I’m deducing that the threat was a hoax to cover up something. Something big is brewing, I can just feel it. This is bigger than just a bomb threat,” Adonis paused to gasp air. “As to where we could possibly be in the mansion, I have no idea. I would guess somewhere underground because of the chill and darkness. The real question is how long we’re going to be here, and whether we can get out.”
“I think the best thing to do for now is to wait and see whether we get checked on in the near future. Plus, do you think Jeff is in here? I hope he got away and is notifying the agency or something,” Sam whispered back to Adonis.
"I bet he got out. He slipped away from us for a whole day, I’m sure he can probably manage a single phone call."
"Yeah, you're probably right."
We fell silent after, both pondering what we had gotten ourselves into. There was no need to try to escape; even if we got out of our bondage, where would we go? 
We have no idea where we are, exactly who captured us, or whether help is on the way, Sam thought bleakly. The simplest solution is to wait until someone checks on us and see if we can get information out of them. If only I had my watch to tell the time…. He continued to lament the loss of his watch. Up until they were captured, he had always worn the watch his grandfather had given to him. Not having it on his wrist felt wrong, like he was missing a body part. I suppose no amount of wishing is going to bring it back. I might as well forget about it now. 
Although the agents could not tell as they sat in the quiet darkness, alternately sleeping and staying awake, nearly four hours passed before a door creaked from somewhere in the room. 
“Adonis! Did you hear that?” Sam whispered in an undertone.
“Yeah. Wanna team up and tackle them?” Adonis breathed back, keeping his voice as low as possible. 
Staying as silent as they could, they stood together and shuffled around the room, avoiding the key of light that spread across the floor as the door swung open. Thank goodness my pain is fading, Sam thought. He shrugged and reasoned, or perhaps I’m just on an adrenaline spike. Whatever the reason, they had enough energy to creep around opposite sides of the room to meet the door-opener, whomever it may be. The shaft of light that lit the floor allowed the agents to see their room for the first time. It was massive, stretching so long that the far sides away from the door faded into fuzzy blackness. For all its length, the ceiling was rather low, maybe ten feet tall. Adonis and Sam reached the door, standing as mirror images on both sides of it. Where are they? Why haven’t they shown themselves yet? Sam puzzled. Finally, a large figure lumbered in.
“Hello? Anyone in he-”
	“SAMMY! NOW!” Adonis yelled. They launched into action, sprinting towards each other in order to pin the man between them. They crashed together and all three fell to the floor, Adonis and Sam on top and pinning the third man with their weight, and the third man landing back-first. 
	“What the fu-” the nameless flustered man was cut off again as Adonis shoved his shoulder into his mouth to muffle him.
	“Listen to me,” Adonis locked his cool brown and grey eyes onto the man's scared black ones. “We know how to kill men without using our hands. You are going to answer my questions. If you scream or refuse, we can and will use force on you.” It was no idle threat. With two heavy, clearly muscular, men sitting on his chest, the nameless man had no choice whether to negotiate. His eyes flashed and his brows pulled together before he nodded consent. 
	“Good,” Adonis grunted, shifting himself so the man could speak. “Where are we? Who has captured us? Why did you capture us? Who are you?”
	“You are in a basement. I cannot say who has captured you, but you’ll probably meet them later. We captured you because our master told us to. I wasn’t actually one of the men sent on the mission. I’m just a groundskeeper, I swear. I was just checking on you.” He tried to lift his hands to gesture to his large gut, trying to prove that he was just a gardener and nothing more. Adonis and Sam did not let him.
	“You didn’t really answer my questions. If you are just a lowly gardener, why are you permitted to see the prisoners?”
	“Well, I’m also a part-time nurse. My master sent me to make sure that neither of you had died.”
	“Well, thank goodness for that. I’m so glad that you have found out we are not dead,” Sam finally added to the conversation, voice heavy with sarcasm. “Are you going to answer his questions now?”
	“Please sirs! I cannot reveal more without putting myself and family in danger. I swear I’ve told you everything I can!” Sam and Adonis glanced over to each other. Though neither of their faces betrayed it, both questioned why his family would be involved in his punishment. 
	“You better not be lying,” Adonis said cautiously, looking up and down the gardener-nurse, trying to see if he had a hidden weapon. He and Sam stood slowly and backed away from the man so he could stand as well. He was quite a squat, portly man who clearly had never been trained in self defense. He wheezed as he stood, clutching his chest. 
	“I think you two broke something in me,” he chuckled nervously.
	“Sorry. You seem like a decent enough person, but we’re more focused on trying to get out of here than sparing you,” Sam said from the shadows he hid in. 
	“I....I understand. I wish that I…” he trailed off. “Ah well, I suppose I should’ve been expecting something like that. Oh, and my name is Francis. If you ever need treatment, you can ask for me,” he told them while backing out the door.
	“Wait! Don’t go-!” Adonis was cut off by the door slamming and the lock clicking into place.
	“Well that went fantastic,” Sam sighed, plopping down onto the floor.
	“Hey, at least we didn’t make any enemies. And we’re hopefully gonna get to meet this leader guy soon,” Adonis replied. Silence settled over the pair yet again.
	
↞⇼↠

	Finally, footsteps could be heard echoing through the door from the hallway after an indeterminable period of time. Sam and Adonis perked up as they heard two ‘Yes sir!’s  from outside. They must have added guards after the last visit, Sam thought. Good. They should be afraid. If he had been anywhere else, he would have chuckled at this mysterious, all-powerful leader being scared enough of two wounded, restrained men that he would post a guard for each.
	Waiting with anticipation, Adonis and Sam inched closer together, subconsciously looking to each other for protection. With brows drawn down low on their faces, they quickly glanced at each other, steeling their resolve before they met this commander. 
	Keys jangled. The lock slid out of place. The door swung in silently on oiled hinges. And Adonis and Sam sat slack-jawed, shock slapping them across their dumbfounded faces.
