# Prologue {.unnumbered}

I watched the flames flick higher in the brick fireplace as they desiccated the wood. My own mind was flickering with anticipation of what I was planning to do. The utter control I would soon have. No one would look down on me anymore. I would control them. I would own them. They would regret-
“Sir? We have n-new intel,” the new intern stuttered loudly as she opened the door abruptly.
“Cassie, darling, didn’t I warn you how many have failed me before you? Do you want to end up like your predecessors?” I ask in annoyance, angry that she had interrupted my thinking. She won’t last long. She already was proving to be replaceable. “And details; what kind of intel?”
Realizing her mistake, Cassie bowed deeply; “My humblest apologies. It slipped my mind, Sir Odin. Intel of possible interruptions to your plans. May I correct myself with a fresh cup of matcha and the files?”
Better, although she might need some more motivation to stay focused. Personal motivation, I presume. It typically works the best. “You have 30 seconds to bring me my tea and files and get out.”
Cassie rushed over and plopped the folders on his desk, then made a beeline for the entrance, closing the heavy oak door behind her. 
	“Now this is interesting,” I mumbled to myself, looking over the files. “A few agents arrest me. As if they could halt my plans.” I sat back in my chair slowly, gazing at the promise etched eons ago into my fathers’ sword hanging above the fireplace: ‘prove them wrong.’ I studied the script, looking at the swoops and dips of the letters, admiring the shapes. An idea formed in my head.
	“Cassie!” I yelled through the door.
“Yes, Sir? What may I do for you?” she asked, popping her head through the threshold.
“Prepare a report to send to my helpers. I need a way to get inside with the agents. I need to take them down from the inside.”
	“Of course,” she murmured, slowly retreating. 

↞⇼↠

	Cassie shut the door behind her. She breathed and leaned against the thick wood for support, her arms trembling. Slowly, she attempted to move back to her table, but her knees suddenly gave out and she collapsed to the floor. A sob rose in her throat, but she muffled it with her sweater sleeve, and her eyes burned with fresh tears. A small mistake. That’s all it was. I fixed it with tea. I said sorry. Surely, I won’t be punished further for simply not explaining myself. She drew herself up and rushed over to her sparse workspace down the hall, trying to sit in her chair before Odin’s posted door-guards noticed her outburst. 
	Fear hammered her heart. Her thoughts skipped, turbulent, panicked, tumbling, churning, bumbling. The only solid thought she could hold onto in the storm: Screw Odin. 
And: I need to visit my brother and parents one more time. One more time, tonight, before Odin discovers who they are. I need them to know I love them, and I’m sorry there isn’t any way I could help them more. 
